// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnteredBuilder Called by frontend when the user opens the builder panel
 */
export function EnteredBuilder(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.EnteredBuilder");
}

export function Equip(slotId: model$0.SlotName, itemRef: models$0.EntityRef<model$0.Item> | null): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Equip", slotId, itemRef);
}

export function GetAllClasses(): $CancellablePromise<model$0.CharacterClassTypeInfo[] | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.GetAllClasses");
}

/**
 * GetStats returns the computed stat sheet for the current loadout.
 */
export function GetStats(): $CancellablePromise<$models.StatSheet | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.GetStats");
}

export function LoadState(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.LoadState");
}

export function SaveState(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SaveState");
}

export function SetClass($class: model$0.CharacterClassType): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetClass", $class);
}

/**
 * SetLevel sets the character level the stat pipeline assumes (clamped to >=1)
 * and persists it.
 */
export function SetLevel(level: number): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetLevel", level);
}

export function ToggleMaxOnEquip(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.ToggleMaxOnEquip");
}

export function Unequip(slotId: model$0.SlotName): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Unequip", slotId);
}

export function UpdateMasteryConfig(data: $models.MasteryConfigSet): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.UpdateMasteryConfig", data);
}

export function Upgrade(slotId: model$0.SlotName, enhanceLevel: number, caphrasLevel: number): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Upgrade", slotId, enhanceLevel, caphrasLevel);
}
