// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../sources/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConsumable activates a consumable buff (idempotent by URN — the exact same
 * item can't stack, distinct consumables can). Returns false for an unresolvable
 * or non-consumable item.
 */
export function AddConsumable(itemRef: models$0.EntityRef<model$0.Item> | null): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.AddConsumable", itemRef);
}

/**
 * ClearCrystal empties one preset socket.
 */
export function ClearCrystal(slotId: model$0.CrystalPresetSlot): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.ClearCrystal", slotId);
}

/**
 * EnteredBuilder Called by frontend when the user opens the builder panel
 */
export function EnteredBuilder(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.EnteredBuilder");
}

export function Equip(itemRef: models$0.EntityRef<model$0.Item> | null, slotId: model$0.SlotName): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Equip", itemRef, slotId);
}

export function GetAllClasses(): $CancellablePromise<model$0.CharacterClassTypeInfo[] | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.GetAllClasses");
}

export function GetEquipHistory(): $CancellablePromise<sources$0.ListSourceEntry[] | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.GetEquipHistory");
}

/**
 * GetStats returns the computed stat sheet for the current loadout.
 */
export function GetStats(): $CancellablePromise<$models.StatSheet | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.GetStats");
}

export function LoadState(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.LoadState");
}

/**
 * RemoveConsumable deactivates a consumable by its item URN.
 */
export function RemoveConsumable(urnStr: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.RemoveConsumable", urnStr);
}

export function SaveState(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SaveState");
}

export function SetClass($class: model$0.CharacterClassType): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetClass", $class);
}

/**
 * SetCrystal places a jewel in a preset socket. Returns false on validation failure.
 */
export function SetCrystal(slotId: model$0.CrystalPresetSlot, itemRef: models$0.EntityRef<model$0.Item> | null): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetCrystal", slotId, itemRef);
}

/**
 * SetLevel sets the character level the stat pipeline assumes (clamped to >=1)
 * and persists it.
 */
export function SetLevel(level: number): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetLevel", level);
}

export function SetSlotsBlockStatus(slotsToBlock: model$0.SlotName[] | null, blocker: model$0.SlotName, block: boolean): $CancellablePromise<$models.EventSlotBlockUpdatedPayload[] | null> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.SetSlotsBlockStatus", slotsToBlock, blocker, block);
}

export function ToggleMaxOnEquip(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.ToggleMaxOnEquip");
}

export function Unequip(slotId: model$0.SlotName): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Unequip", slotId);
}

export function UpdateMasteryConfig(data: $models.MasteryConfigSet): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.UpdateMasteryConfig", data);
}

export function Upgrade(slotId: model$0.SlotName, enhanceLevel: number, caphrasLevel: number): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/gear.BuilderService.Upgrade", slotId, enhanceLevel, caphrasLevel);
}
