// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/models/models.js";

export interface EventLoadoutUpdatedPayload {
    "gearMastery": MasteryConfigSet;
    "level": number;
    "class"?: model$0.CharacterClassTypeInfo;
    "slots": Slot[];
    "maxOnEquip": boolean;
    "stats": StatSheet | null;
}

export type MasteryConfigSet = { [_ in model$0.LifeSkillType]?: MasteryData } | null;

export interface MasteryData {
    "rank": number;
    "lvl": number;
}

export interface Slot {
    "id": model$0.SlotName;
    "itemRef": models$0.EntityRef<model$0.Item> | null;

    /**
     * True when we've equipped an item which "blocks" other slots, for ex, life skill gear, "manos fisher's clothes"
     */
    "locked": boolean;

    /**
     * The enhancement level of the item
     */
    "enhanceLevel": number;

    /**
     * The caphras level of the item
     */
    "caphrasLevel": number;

    /**
     * Mainly for frontend
     */
    "info": model$0.SlotNameInfo;
    "item": model$0.Item | null;

    /**
     * The enhancement info of the item
     */
    "enhancement": model$0.EnchantLevel | null;

    /**
     * The caphras info of the item
     */
    "caphras": model$0.CaphrasLevel | null;
}

/**
 * StatSheet is the computed character sheet: headline AP/AAP/DP plus every stat
 * keyed by its StatId (see model.StatId(key).Info() for label/category/unit).
 */
export interface StatSheet {
    /**
     * sheet main-hand AP, floor((apMin+apMax)/2)
     */
    "ap": number;

    /**
     * sheet awakening AP
     */
    "aap": number;
    "dp": number;
    "score": number;
    "stats": { [_ in model$0.StatId]?: StatValue | null } | null;
}

/**
 * StatSource is one contribution to a stat, kept for the breakdown display.
 */
export interface StatSource {
    "name": string;
    "value": number;
}

/**
 * StatValue is an accumulated stat: its total and where each part came from.
 */
export interface StatValue {
    "total": number;
    "sources": StatSource[] | null;
}
