// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../sources/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/models/models.js";

export interface EventEquipHistoryUpdatedPayload {
    "equipHistory"?: sources$0.ListSourceEntry[] | null;
}

export interface EventLoadoutUpdatedPayload {
    "gearMastery": MasteryConfigSet;
    "level": number;
    "consumables": (model$0.Item | null)[] | null;
    "class"?: model$0.CharacterClassTypeInfo;
    "slots": SimpleSlotData[];
    "maxOnEquip": boolean;
    "stats": StatSheet | null;
}

export interface EventSlotBlockUpdatedPayload {
    "slotId": model$0.SlotName;
    "locked": boolean;
    "lockedBy": model$0.SlotName | null;
    "previousItem"?: model$0.Item | null;
}

export type MasteryConfigSet = { [_ in model$0.LifeSkillType]?: MasteryData } | null;

export interface MasteryData {
    "rank": number;
    "lvl": number;
}

/**
 * SimpleSlotData a lightweight version we can stream down to frontend
 */
export interface SimpleSlotData {
    "id": model$0.SlotName;
    "itemRef": models$0.EntityRef<model$0.Item> | null;

    /**
     * True when we've equipped an item which "blocks" other slots, for ex, life skill gear, "manos fisher's clothes"
     */
    "locked": boolean;

    /**
     * The slot which is locking this slot, if any
     */
    "lockedBy"?: model$0.SlotName | null;

    /**
     * The enhancement level of the item
     */
    "enhanceLevel": number;

    /**
     * The caphras level of the item
     */
    "caphrasLevel": number;
    "info": model$0.SlotNameInfo;
    "item"?: sources$0.ListSourceEntry | null;
    "enhancementTitle"?: string;
    "enhancementMinLevel"?: number;
    "enhancementMaxLevel"?: number;
    "caphrasMinLevel"?: number;
    "caphrasMaxLevel"?: number;
}

export interface StatSheet {
    /**
     * sheet main-hand AP, floor((apMin+apMax)/2)
     */
    "ap": number;

    /**
     * sheet awakening AP
     */
    "aap": number;
    "dp": number;
    "score": number;
    "stats": { [_ in model$0.StatId]?: StatValue | null } | null;
}

/**
 * StatSource is one contribution to a stat, kept for the breakdown display.
 */
export interface StatSource {
    "name": string;
    "value": number;
}

/**
 * StatValue is an accumulated stat: its total and where each part came from.
 */
export interface StatValue {
    "total": number;
    "sources": StatSource[] | null;
}
