// Code generated by enumgen from character_classes.yml. DO NOT EDIT.

export const CharacterClassTypes = {
  Unknown: -1,
  Warrior: 0,
  Hashashin: 1,
  Sage: 2,
  Wukong: 3,
  Ranger: 4,
  Guardian: 5,
  Scholar: 6,
  Drakania: 7,
  Sorceress: 8,
  Nova: 9,
  Corsair: 10,
  Lahn: 11,
  Berserker: 12,
  Reserved13: 13,
  Reserved14: 14,
  Maegu: 15,
  Tamer: 16,
  Shai: 17,
  Reserved18: 18,
  Striker: 19,
  Musa: 20,
  Maehwa: 21,
  Reserved22: 22,
  Mystic: 23,
  Valkyrie: 24,
  Kunoichi: 25,
  Ninja: 26,
  DarkKnight: 27,
  Wizard: 28,
  Archer: 29,
  Woosa: 30,
  Witch: 31,
  Seraph: 32,
  Dosa: 33,
  Deadeye: 34,
  Reserved35: 35,
  Reserved36: 36,
} as const;

export type CharacterClassType = (typeof CharacterClassTypes)[keyof typeof CharacterClassTypes];

// Const-only boundaries, excluded from the tables below.
export const CharacterClassTypeMAX = 37;

export interface CharacterClassTypeInfo {
  value: CharacterClassType;
  name: string;
  reserved?: boolean;
  title?: string;
}

export const CharacterClassTypeInfos: Record<CharacterClassType, CharacterClassTypeInfo> = {
  [CharacterClassTypes.Unknown]: {
    value: CharacterClassTypes.Unknown,
    name: "Unknown",
    reserved: true,
  },
  [CharacterClassTypes.Warrior]: {
    value: CharacterClassTypes.Warrior,
    name: "Warrior",
    title: "Warrior",
  },
  [CharacterClassTypes.Hashashin]: {
    value: CharacterClassTypes.Hashashin,
    name: "Hashashin",
    title: "Hashashin",
  },
  [CharacterClassTypes.Sage]: {
    value: CharacterClassTypes.Sage,
    name: "Sage",
    title: "Sage",
  },
  [CharacterClassTypes.Wukong]: {
    value: CharacterClassTypes.Wukong,
    name: "Wukong",
    title: "Wukong",
  },
  [CharacterClassTypes.Ranger]: {
    value: CharacterClassTypes.Ranger,
    name: "Ranger",
    title: "Ranger",
  },
  [CharacterClassTypes.Guardian]: {
    value: CharacterClassTypes.Guardian,
    name: "Guardian",
    title: "Guardian",
  },
  [CharacterClassTypes.Scholar]: {
    value: CharacterClassTypes.Scholar,
    name: "Scholar",
    title: "Scholar",
  },
  [CharacterClassTypes.Drakania]: {
    value: CharacterClassTypes.Drakania,
    name: "Drakania",
    title: "Drakania",
  },
  [CharacterClassTypes.Sorceress]: {
    value: CharacterClassTypes.Sorceress,
    name: "Sorceress",
    title: "Sorceress",
  },
  [CharacterClassTypes.Nova]: {
    value: CharacterClassTypes.Nova,
    name: "Nova",
    title: "Nova",
  },
  [CharacterClassTypes.Corsair]: {
    value: CharacterClassTypes.Corsair,
    name: "Corsair",
    title: "Corsair",
  },
  [CharacterClassTypes.Lahn]: {
    value: CharacterClassTypes.Lahn,
    name: "Lahn",
    title: "Lahn",
  },
  [CharacterClassTypes.Berserker]: {
    value: CharacterClassTypes.Berserker,
    name: "Berserker",
    title: "Berserker",
  },
  [CharacterClassTypes.Reserved13]: {
    value: CharacterClassTypes.Reserved13,
    name: "Reserved13",
    reserved: true,
    title: "",
  },
  [CharacterClassTypes.Reserved14]: {
    value: CharacterClassTypes.Reserved14,
    name: "Reserved14",
    reserved: true,
    title: "",
  },
  [CharacterClassTypes.Maegu]: {
    value: CharacterClassTypes.Maegu,
    name: "Maegu",
    title: "Maegu",
  },
  [CharacterClassTypes.Tamer]: {
    value: CharacterClassTypes.Tamer,
    name: "Tamer",
    title: "Tamer",
  },
  [CharacterClassTypes.Shai]: {
    value: CharacterClassTypes.Shai,
    name: "Shai",
    title: "Shai",
  },
  [CharacterClassTypes.Reserved18]: {
    value: CharacterClassTypes.Reserved18,
    name: "Reserved18",
    reserved: true,
    title: "",
  },
  [CharacterClassTypes.Striker]: {
    value: CharacterClassTypes.Striker,
    name: "Striker",
    title: "Striker",
  },
  [CharacterClassTypes.Musa]: {
    value: CharacterClassTypes.Musa,
    name: "Musa",
    title: "Musa",
  },
  [CharacterClassTypes.Maehwa]: {
    value: CharacterClassTypes.Maehwa,
    name: "Maehwa",
    title: "Maehwa",
  },
  [CharacterClassTypes.Reserved22]: {
    value: CharacterClassTypes.Reserved22,
    name: "Reserved22",
    reserved: true,
    title: "",
  },
  [CharacterClassTypes.Mystic]: {
    value: CharacterClassTypes.Mystic,
    name: "Mystic",
    title: "Mystic",
  },
  [CharacterClassTypes.Valkyrie]: {
    value: CharacterClassTypes.Valkyrie,
    name: "Valkyrie",
    title: "Valkyrie",
  },
  [CharacterClassTypes.Kunoichi]: {
    value: CharacterClassTypes.Kunoichi,
    name: "Kunoichi",
    title: "Kunoichi",
  },
  [CharacterClassTypes.Ninja]: {
    value: CharacterClassTypes.Ninja,
    name: "Ninja",
    title: "Ninja",
  },
  [CharacterClassTypes.DarkKnight]: {
    value: CharacterClassTypes.DarkKnight,
    name: "DarkKnight",
    title: "Dark Knight",
  },
  [CharacterClassTypes.Wizard]: {
    value: CharacterClassTypes.Wizard,
    name: "Wizard",
    title: "Wizard",
  },
  [CharacterClassTypes.Archer]: {
    value: CharacterClassTypes.Archer,
    name: "Archer",
    title: "Archer",
  },
  [CharacterClassTypes.Woosa]: {
    value: CharacterClassTypes.Woosa,
    name: "Woosa",
    title: "Woosa",
  },
  [CharacterClassTypes.Witch]: {
    value: CharacterClassTypes.Witch,
    name: "Witch",
    title: "Witch",
  },
  [CharacterClassTypes.Seraph]: {
    value: CharacterClassTypes.Seraph,
    name: "Seraph",
    title: "Seraph",
  },
  [CharacterClassTypes.Dosa]: {
    value: CharacterClassTypes.Dosa,
    name: "Dosa",
    title: "Dosa",
  },
  [CharacterClassTypes.Deadeye]: {
    value: CharacterClassTypes.Deadeye,
    name: "Deadeye",
    title: "Deadeye",
  },
  [CharacterClassTypes.Reserved35]: {
    value: CharacterClassTypes.Reserved35,
    name: "Reserved35",
    reserved: true,
    title: "",
  },
  [CharacterClassTypes.Reserved36]: {
    value: CharacterClassTypes.Reserved36,
    name: "Reserved36",
    reserved: true,
    title: "",
  },
} as const;

export const CharacterClassTypeValues: readonly CharacterClassType[] = [
  CharacterClassTypes.Unknown,
  CharacterClassTypes.Warrior,
  CharacterClassTypes.Hashashin,
  CharacterClassTypes.Sage,
  CharacterClassTypes.Wukong,
  CharacterClassTypes.Ranger,
  CharacterClassTypes.Guardian,
  CharacterClassTypes.Scholar,
  CharacterClassTypes.Drakania,
  CharacterClassTypes.Sorceress,
  CharacterClassTypes.Nova,
  CharacterClassTypes.Corsair,
  CharacterClassTypes.Lahn,
  CharacterClassTypes.Berserker,
  CharacterClassTypes.Reserved13,
  CharacterClassTypes.Reserved14,
  CharacterClassTypes.Maegu,
  CharacterClassTypes.Tamer,
  CharacterClassTypes.Shai,
  CharacterClassTypes.Reserved18,
  CharacterClassTypes.Striker,
  CharacterClassTypes.Musa,
  CharacterClassTypes.Maehwa,
  CharacterClassTypes.Reserved22,
  CharacterClassTypes.Mystic,
  CharacterClassTypes.Valkyrie,
  CharacterClassTypes.Kunoichi,
  CharacterClassTypes.Ninja,
  CharacterClassTypes.DarkKnight,
  CharacterClassTypes.Wizard,
  CharacterClassTypes.Archer,
  CharacterClassTypes.Woosa,
  CharacterClassTypes.Witch,
  CharacterClassTypes.Seraph,
  CharacterClassTypes.Dosa,
  CharacterClassTypes.Deadeye,
  CharacterClassTypes.Reserved35,
  CharacterClassTypes.Reserved36,
] as const;

export const CharacterClassTypeByName: Record<string, CharacterClassType> = {
  "Unknown": CharacterClassTypes.Unknown,
  "Warrior": CharacterClassTypes.Warrior,
  "Hashashin": CharacterClassTypes.Hashashin,
  "Sage": CharacterClassTypes.Sage,
  "Wukong": CharacterClassTypes.Wukong,
  "Ranger": CharacterClassTypes.Ranger,
  "Guardian": CharacterClassTypes.Guardian,
  "Scholar": CharacterClassTypes.Scholar,
  "Drakania": CharacterClassTypes.Drakania,
  "Sorceress": CharacterClassTypes.Sorceress,
  "Nova": CharacterClassTypes.Nova,
  "Corsair": CharacterClassTypes.Corsair,
  "Lahn": CharacterClassTypes.Lahn,
  "Berserker": CharacterClassTypes.Berserker,
  "Reserved13": CharacterClassTypes.Reserved13,
  "Reserved14": CharacterClassTypes.Reserved14,
  "Maegu": CharacterClassTypes.Maegu,
  "Tamer": CharacterClassTypes.Tamer,
  "Shai": CharacterClassTypes.Shai,
  "Reserved18": CharacterClassTypes.Reserved18,
  "Striker": CharacterClassTypes.Striker,
  "Musa": CharacterClassTypes.Musa,
  "Maehwa": CharacterClassTypes.Maehwa,
  "Reserved22": CharacterClassTypes.Reserved22,
  "Mystic": CharacterClassTypes.Mystic,
  "Valkyrie": CharacterClassTypes.Valkyrie,
  "Kunoichi": CharacterClassTypes.Kunoichi,
  "Ninja": CharacterClassTypes.Ninja,
  "DarkKnight": CharacterClassTypes.DarkKnight,
  "Wizard": CharacterClassTypes.Wizard,
  "Archer": CharacterClassTypes.Archer,
  "Woosa": CharacterClassTypes.Woosa,
  "Witch": CharacterClassTypes.Witch,
  "Seraph": CharacterClassTypes.Seraph,
  "Dosa": CharacterClassTypes.Dosa,
  "Deadeye": CharacterClassTypes.Deadeye,
  "Reserved35": CharacterClassTypes.Reserved35,
  "Reserved36": CharacterClassTypes.Reserved36,
} as const;

const characterClassTypeByLowerName: Record<string, CharacterClassType> = {};
for (const [k, v] of Object.entries(CharacterClassTypeByName)) {
  characterClassTypeByLowerName[k.toLowerCase()] = v;
}

// parseCharacterClassType resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseCharacterClassType(name: string): CharacterClassType | undefined {
  return characterClassTypeByLowerName[name.trim().toLowerCase()];
}

export function* iterTitle(): Generator<string | undefined> {
  for (const v of CharacterClassTypeValues) {
    yield CharacterClassTypeInfos[v].title;
  }
}
