// Code generated by enumgen from crystal_preset_slots.yml. DO NOT EDIT.

import { CrystalSpecialSlots, type CrystalSpecialSlot } from "./crystal-special-slots.gen";
import { SlotNames, type SlotName } from "./slot-names.gen";

export const CrystalPresetSlots = {
  Base0: 0,
  Base1: 1,
  Base2: 2,
  Base3: 3,
  Base4: 4,
  Base5: 5,
  Base6: 6,
  Base7: 7,
  Base8: 8,
  Base9: 9,
  Base10: 10,
  Base11: 11,
  Costume: 12,
  HeartL: 13,
  HeartR: 14,
  LoMLL: 15,
  LoMLR: 16,
  DawnNecklace: 17,
  DawnRingI: 18,
  DawnRingII: 19,
  DawnEarringI: 20,
  DawnEarringII: 21,
  DawnBelt: 22,
} as const;

export type CrystalPresetSlot = (typeof CrystalPresetSlots)[keyof typeof CrystalPresetSlots];

// Const-only boundaries, excluded from the tables below.
export const CrystalPresetSlotMAX = 23;

export interface CrystalPresetSlotInfo {
  value: CrystalPresetSlot;
  name: string;
  title: string;
  kind: string;
  crystalGroup?: number;
  specialSlot?: CrystalSpecialSlot;
  dawnEquipSlot?: SlotName;
}

export const CrystalPresetSlotInfos: Record<CrystalPresetSlot, CrystalPresetSlotInfo> = {
  [CrystalPresetSlots.Base0]: {
    value: CrystalPresetSlots.Base0,
    name: "Base0",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base1]: {
    value: CrystalPresetSlots.Base1,
    name: "Base1",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base2]: {
    value: CrystalPresetSlots.Base2,
    name: "Base2",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base3]: {
    value: CrystalPresetSlots.Base3,
    name: "Base3",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base4]: {
    value: CrystalPresetSlots.Base4,
    name: "Base4",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base5]: {
    value: CrystalPresetSlots.Base5,
    name: "Base5",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base6]: {
    value: CrystalPresetSlots.Base6,
    name: "Base6",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base7]: {
    value: CrystalPresetSlots.Base7,
    name: "Base7",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base8]: {
    value: CrystalPresetSlots.Base8,
    name: "Base8",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base9]: {
    value: CrystalPresetSlots.Base9,
    name: "Base9",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base10]: {
    value: CrystalPresetSlots.Base10,
    name: "Base10",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Base11]: {
    value: CrystalPresetSlots.Base11,
    name: "Base11",
    title: "Crystal",
    kind: "base",
  },
  [CrystalPresetSlots.Costume]: {
    value: CrystalPresetSlots.Costume,
    name: "Costume",
    title: "Costume",
    kind: "costume",
    crystalGroup: 101,
    specialSlot: CrystalSpecialSlots.PearlAvatarChest,
  },
  [CrystalPresetSlots.HeartL]: {
    value: CrystalPresetSlots.HeartL,
    name: "HeartL",
    title: "Heart L",
    kind: "heart",
  },
  [CrystalPresetSlots.HeartR]: {
    value: CrystalPresetSlots.HeartR,
    name: "HeartR",
    title: "Heart R",
    kind: "heart",
  },
  [CrystalPresetSlots.LoMLL]: {
    value: CrystalPresetSlots.LoMLL,
    name: "LoMLL",
    title: "LoML L",
    kind: "loml",
  },
  [CrystalPresetSlots.LoMLR]: {
    value: CrystalPresetSlots.LoMLR,
    name: "LoMLR",
    title: "LoML R",
    kind: "loml",
  },
  [CrystalPresetSlots.DawnNecklace]: {
    value: CrystalPresetSlots.DawnNecklace,
    name: "DawnNecklace",
    title: "Necklace",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.Necklace,
    dawnEquipSlot: SlotNames.Necklace,
  },
  [CrystalPresetSlots.DawnRingI]: {
    value: CrystalPresetSlots.DawnRingI,
    name: "DawnRingI",
    title: "Ring I",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.RingI,
    dawnEquipSlot: SlotNames.RingI,
  },
  [CrystalPresetSlots.DawnRingII]: {
    value: CrystalPresetSlots.DawnRingII,
    name: "DawnRingII",
    title: "Ring II",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.RingII,
    dawnEquipSlot: SlotNames.RingII,
  },
  [CrystalPresetSlots.DawnEarringI]: {
    value: CrystalPresetSlots.DawnEarringI,
    name: "DawnEarringI",
    title: "Earring I",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.EarringI,
    dawnEquipSlot: SlotNames.EarringI,
  },
  [CrystalPresetSlots.DawnEarringII]: {
    value: CrystalPresetSlots.DawnEarringII,
    name: "DawnEarringII",
    title: "Earring II",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.EarringII,
    dawnEquipSlot: SlotNames.EarringII,
  },
  [CrystalPresetSlots.DawnBelt]: {
    value: CrystalPresetSlots.DawnBelt,
    name: "DawnBelt",
    title: "Belt",
    kind: "dawn",
    crystalGroup: 103,
    specialSlot: CrystalSpecialSlots.Belt,
    dawnEquipSlot: SlotNames.Belt,
  },
} as const;

export const CrystalPresetSlotValues: readonly CrystalPresetSlot[] = [
  CrystalPresetSlots.Base0,
  CrystalPresetSlots.Base1,
  CrystalPresetSlots.Base2,
  CrystalPresetSlots.Base3,
  CrystalPresetSlots.Base4,
  CrystalPresetSlots.Base5,
  CrystalPresetSlots.Base6,
  CrystalPresetSlots.Base7,
  CrystalPresetSlots.Base8,
  CrystalPresetSlots.Base9,
  CrystalPresetSlots.Base10,
  CrystalPresetSlots.Base11,
  CrystalPresetSlots.Costume,
  CrystalPresetSlots.HeartL,
  CrystalPresetSlots.HeartR,
  CrystalPresetSlots.LoMLL,
  CrystalPresetSlots.LoMLR,
  CrystalPresetSlots.DawnNecklace,
  CrystalPresetSlots.DawnRingI,
  CrystalPresetSlots.DawnRingII,
  CrystalPresetSlots.DawnEarringI,
  CrystalPresetSlots.DawnEarringII,
  CrystalPresetSlots.DawnBelt,
] as const;

export const CrystalPresetSlotByName = {
  "Base0": CrystalPresetSlots.Base0,
  "Base1": CrystalPresetSlots.Base1,
  "Base2": CrystalPresetSlots.Base2,
  "Base3": CrystalPresetSlots.Base3,
  "Base4": CrystalPresetSlots.Base4,
  "Base5": CrystalPresetSlots.Base5,
  "Base6": CrystalPresetSlots.Base6,
  "Base7": CrystalPresetSlots.Base7,
  "Base8": CrystalPresetSlots.Base8,
  "Base9": CrystalPresetSlots.Base9,
  "Base10": CrystalPresetSlots.Base10,
  "Base11": CrystalPresetSlots.Base11,
  "Costume": CrystalPresetSlots.Costume,
  "HeartL": CrystalPresetSlots.HeartL,
  "HeartR": CrystalPresetSlots.HeartR,
  "LoMLL": CrystalPresetSlots.LoMLL,
  "LoMLR": CrystalPresetSlots.LoMLR,
  "DawnNecklace": CrystalPresetSlots.DawnNecklace,
  "DawnRingI": CrystalPresetSlots.DawnRingI,
  "DawnRingII": CrystalPresetSlots.DawnRingII,
  "DawnEarringI": CrystalPresetSlots.DawnEarringI,
  "DawnEarringII": CrystalPresetSlots.DawnEarringII,
  "DawnBelt": CrystalPresetSlots.DawnBelt,
} as const;

export type CrystalPresetSlotNames = keyof (typeof CrystalPresetSlotByName)

const crystalPresetSlotByLowerName: Record<string, CrystalPresetSlot> = {};
for (const [k, v] of Object.entries(CrystalPresetSlotByName)) {
  crystalPresetSlotByLowerName[k.toLowerCase()] = v;
}

// parseCrystalPresetSlot resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseCrystalPresetSlot(name: string): CrystalPresetSlot | undefined {
  return crystalPresetSlotByLowerName[name.trim().toLowerCase()];
}
