// Code generated by enumgen from crystal_special_slots.yml. DO NOT EDIT.

export const CrystalSpecialSlots = {
  PearlAvatarChest: 14,
  Necklace: 17,
  RingI: 18,
  RingII: 19,
  EarringI: 20,
  EarringII: 21,
  Belt: 22,
} as const;

export type CrystalSpecialSlot = (typeof CrystalSpecialSlots)[keyof typeof CrystalSpecialSlots];

export interface CrystalSpecialSlotInfo {
  value: CrystalSpecialSlot;
  name: string;
  title: string;
}

export const CrystalSpecialSlotInfos: Record<CrystalSpecialSlot, CrystalSpecialSlotInfo> = {
  [CrystalSpecialSlots.PearlAvatarChest]: {
    value: CrystalSpecialSlots.PearlAvatarChest,
    name: "PearlAvatarChest",
    title: "Costume Armor",
  },
  [CrystalSpecialSlots.Necklace]: {
    value: CrystalSpecialSlots.Necklace,
    name: "Necklace",
    title: "Necklace",
  },
  [CrystalSpecialSlots.RingI]: {
    value: CrystalSpecialSlots.RingI,
    name: "RingI",
    title: "Ring I",
  },
  [CrystalSpecialSlots.RingII]: {
    value: CrystalSpecialSlots.RingII,
    name: "RingII",
    title: "Ring II",
  },
  [CrystalSpecialSlots.EarringI]: {
    value: CrystalSpecialSlots.EarringI,
    name: "EarringI",
    title: "Earring I",
  },
  [CrystalSpecialSlots.EarringII]: {
    value: CrystalSpecialSlots.EarringII,
    name: "EarringII",
    title: "Earring II",
  },
  [CrystalSpecialSlots.Belt]: {
    value: CrystalSpecialSlots.Belt,
    name: "Belt",
    title: "Belt",
  },
} as const;

export const CrystalSpecialSlotValues: readonly CrystalSpecialSlot[] = [
  CrystalSpecialSlots.PearlAvatarChest,
  CrystalSpecialSlots.Necklace,
  CrystalSpecialSlots.RingI,
  CrystalSpecialSlots.RingII,
  CrystalSpecialSlots.EarringI,
  CrystalSpecialSlots.EarringII,
  CrystalSpecialSlots.Belt,
] as const;

export const CrystalSpecialSlotByName = {
  "PearlAvatarChest": CrystalSpecialSlots.PearlAvatarChest,
  "Necklace": CrystalSpecialSlots.Necklace,
  "RingI": CrystalSpecialSlots.RingI,
  "RingII": CrystalSpecialSlots.RingII,
  "EarringI": CrystalSpecialSlots.EarringI,
  "EarringII": CrystalSpecialSlots.EarringII,
  "Belt": CrystalSpecialSlots.Belt,
} as const;

export type CrystalSpecialSlotNames = keyof (typeof CrystalSpecialSlotByName)

const crystalSpecialSlotByLowerName: Record<string, CrystalSpecialSlot> = {};
for (const [k, v] of Object.entries(CrystalSpecialSlotByName)) {
  crystalSpecialSlotByLowerName[k.toLowerCase()] = v;
}

// parseCrystalSpecialSlot resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseCrystalSpecialSlot(name: string): CrystalSpecialSlot | undefined {
  return crystalSpecialSlotByLowerName[name.trim().toLowerCase()];
}
