// Code generated by enumgen from family_stat_types.yml. DO NOT EDIT.

export const FamilyStatTypes = {
  Offence: 0,
  Defence: 1,
  HP: 2,
  MP: 3,
  Stamina: 4,
  Weight: 5,
  Inventory: 6,
  Accuracy: 7,
  Evasion: 8,
  EnhancementChance: 9,
  ValksLimit: 10,
  StackLimit: 11,
  None: 16,
} as const;

export type FamilyStatType = (typeof FamilyStatTypes)[keyof typeof FamilyStatTypes];

export interface FamilyStatTypeInfo {
  value: FamilyStatType;
  name: string;
  title: string;
}

export const FamilyStatTypeInfos: Record<FamilyStatType, FamilyStatTypeInfo> = {
  [FamilyStatTypes.Offence]: {
    value: FamilyStatTypes.Offence,
    name: "Offence",
    title: "All AP",
  },
  [FamilyStatTypes.Defence]: {
    value: FamilyStatTypes.Defence,
    name: "Defence",
    title: "All DP",
  },
  [FamilyStatTypes.HP]: {
    value: FamilyStatTypes.HP,
    name: "HP",
    title: "Max HP",
  },
  [FamilyStatTypes.MP]: {
    value: FamilyStatTypes.MP,
    name: "MP",
    title: "Max MP",
  },
  [FamilyStatTypes.Stamina]: {
    value: FamilyStatTypes.Stamina,
    name: "Stamina",
    title: "Max Stamina",
  },
  [FamilyStatTypes.Weight]: {
    value: FamilyStatTypes.Weight,
    name: "Weight",
    title: "Weight Limit",
  },
  [FamilyStatTypes.Inventory]: {
    value: FamilyStatTypes.Inventory,
    name: "Inventory",
    title: "Inventory Slots",
  },
  [FamilyStatTypes.Accuracy]: {
    value: FamilyStatTypes.Accuracy,
    name: "Accuracy",
    title: "Accuracy",
  },
  [FamilyStatTypes.Evasion]: {
    value: FamilyStatTypes.Evasion,
    name: "Evasion",
    title: "Evasion",
  },
  [FamilyStatTypes.EnhancementChance]: {
    value: FamilyStatTypes.EnhancementChance,
    name: "EnhancementChance",
    title: "Enhancement Chance",
  },
  [FamilyStatTypes.ValksLimit]: {
    value: FamilyStatTypes.ValksLimit,
    name: "ValksLimit",
    title: "Additional Enhancement Chance Limit",
  },
  [FamilyStatTypes.StackLimit]: {
    value: FamilyStatTypes.StackLimit,
    name: "StackLimit",
    title: "Enhancement Chance Stack Limit",
  },
  [FamilyStatTypes.None]: {
    value: FamilyStatTypes.None,
    name: "None",
    title: "None",
  },
} as const;

export const FamilyStatTypeValues: readonly FamilyStatType[] = [
  FamilyStatTypes.Offence,
  FamilyStatTypes.Defence,
  FamilyStatTypes.HP,
  FamilyStatTypes.MP,
  FamilyStatTypes.Stamina,
  FamilyStatTypes.Weight,
  FamilyStatTypes.Inventory,
  FamilyStatTypes.Accuracy,
  FamilyStatTypes.Evasion,
  FamilyStatTypes.EnhancementChance,
  FamilyStatTypes.ValksLimit,
  FamilyStatTypes.StackLimit,
  FamilyStatTypes.None,
] as const;

export const FamilyStatTypeByName = {
  "Offence": FamilyStatTypes.Offence,
  "Defence": FamilyStatTypes.Defence,
  "HP": FamilyStatTypes.HP,
  "MP": FamilyStatTypes.MP,
  "Stamina": FamilyStatTypes.Stamina,
  "Weight": FamilyStatTypes.Weight,
  "Inventory": FamilyStatTypes.Inventory,
  "Accuracy": FamilyStatTypes.Accuracy,
  "Evasion": FamilyStatTypes.Evasion,
  "EnhancementChance": FamilyStatTypes.EnhancementChance,
  "ValksLimit": FamilyStatTypes.ValksLimit,
  "StackLimit": FamilyStatTypes.StackLimit,
  "None": FamilyStatTypes.None,
} as const;

export type FamilyStatTypeNames = keyof (typeof FamilyStatTypeByName)

const familyStatTypeByLowerName: Record<string, FamilyStatType> = {};
for (const [k, v] of Object.entries(FamilyStatTypeByName)) {
  familyStatTypeByLowerName[k.toLowerCase()] = v;
}

// parseFamilyStatType resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseFamilyStatType(name: string): FamilyStatType | undefined {
  return familyStatTypeByLowerName[name.trim().toLowerCase()];
}
