// Code generated by enumgen from item_grades.yml. DO NOT EDIT.

export const ItemGrades = {
  None: -1,
  White: 0,
  Green: 1,
  Blue: 2,
  Yellow: 3,
  Red: 4,
  Purple: 5,
} as const;

export type ItemGrade = (typeof ItemGrades)[keyof typeof ItemGrades];

export interface ItemGradeInfo {
  value: ItemGrade;
  name: string;
  color?: string;
}

export const ItemGradeInfos: Record<ItemGrade, ItemGradeInfo> = {
  [ItemGrades.None]: {
    value: ItemGrades.None,
    name: "none",
  },
  [ItemGrades.White]: {
    value: ItemGrades.White,
    name: "white",
    color: "#e8eaed",
  },
  [ItemGrades.Green]: {
    value: ItemGrades.Green,
    name: "green",
    color: "#7dc86e",
  },
  [ItemGrades.Blue]: {
    value: ItemGrades.Blue,
    name: "blue",
    color: "#5b9dff",
  },
  [ItemGrades.Yellow]: {
    value: ItemGrades.Yellow,
    name: "yellow",
    color: "#e6c84e",
  },
  [ItemGrades.Red]: {
    value: ItemGrades.Red,
    name: "red",
    color: "#db4d3d",
  },
  [ItemGrades.Purple]: {
    value: ItemGrades.Purple,
    name: "purple",
    color: "#c084e6",
  },
} as const;

export const ItemGradeValues: readonly ItemGrade[] = [
  ItemGrades.None,
  ItemGrades.White,
  ItemGrades.Green,
  ItemGrades.Blue,
  ItemGrades.Yellow,
  ItemGrades.Red,
  ItemGrades.Purple,
] as const;

export const ItemGradeByName: Record<string, ItemGrade> = {
  "none": ItemGrades.None,
  "white": ItemGrades.White,
  "green": ItemGrades.Green,
  "blue": ItemGrades.Blue,
  "yellow": ItemGrades.Yellow,
  "red": ItemGrades.Red,
  "purple": ItemGrades.Purple,
} as const;

const itemGradeByLowerName: Record<string, ItemGrade> = {};
for (const [k, v] of Object.entries(ItemGradeByName)) {
  itemGradeByLowerName[k.toLowerCase()] = v;
}

// parseItemGrade resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseItemGrade(name: string): ItemGrade | undefined {
  return itemGradeByLowerName[name.trim().toLowerCase()];
}
