// Code generated by enumgen from item_types.yml. DO NOT EDIT.

export const ItemTypes = {
  Normal: 0,
  Equip: 1,
  Skill: 2,
  Tent: 3,
  Installation: 4,
  Jewel: 5,
  CannonBall: 6,
  Mapae: 7,
  Material: 8,
  Interaction: 9,
  ContentsEvent: 10,
  ToVehicle: 11,
  Reserved12: 12,
  Reserved13: 13,
  Reserved14: 14,
  Reserved15: 15,
  Reserved16: 16,
  Reserved17: 17,
  Reserved18: 18,
  Reserved19: 19,
} as const;

export type ItemType = (typeof ItemTypes)[keyof typeof ItemTypes];

export interface ItemTypeInfo {
  value: ItemType;
  name: string;
  title: string;
  reserved?: boolean;
}

export const ItemTypeInfos: Record<ItemType, ItemTypeInfo> = {
  [ItemTypes.Normal]: {
    value: ItemTypes.Normal,
    name: "Normal",
    title: "General",
  },
  [ItemTypes.Equip]: {
    value: ItemTypes.Equip,
    name: "Equip",
    title: "Equipment",
  },
  [ItemTypes.Skill]: {
    value: ItemTypes.Skill,
    name: "Skill",
    title: "Consumable",
  },
  [ItemTypes.Tent]: {
    value: ItemTypes.Tent,
    name: "Tent",
    title: "Holding Tool",
  },
  [ItemTypes.Installation]: {
    value: ItemTypes.Installation,
    name: "Installation",
    title: "Installable Object",
  },
  [ItemTypes.Jewel]: {
    value: ItemTypes.Jewel,
    name: "Jewel",
    title: "Socket Item",
  },
  [ItemTypes.CannonBall]: {
    value: ItemTypes.CannonBall,
    name: "CannonBall",
    title: "Cannonball",
  },
  [ItemTypes.Mapae]: {
    value: ItemTypes.Mapae,
    name: "Mapae",
    title: "License",
  },
  [ItemTypes.Material]: {
    value: ItemTypes.Material,
    name: "Material",
    title: "Crafting Material",
  },
  [ItemTypes.Interaction]: {
    value: ItemTypes.Interaction,
    name: "Interaction",
    title: "Enter Area",
  },
  [ItemTypes.ContentsEvent]: {
    value: ItemTypes.ContentsEvent,
    name: "ContentsEvent",
    title: "Special Items",
  },
  [ItemTypes.ToVehicle]: {
    value: ItemTypes.ToVehicle,
    name: "ToVehicle",
    title: "General",
  },
  [ItemTypes.Reserved12]: {
    value: ItemTypes.Reserved12,
    name: "Reserved12",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved13]: {
    value: ItemTypes.Reserved13,
    name: "Reserved13",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved14]: {
    value: ItemTypes.Reserved14,
    name: "Reserved14",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved15]: {
    value: ItemTypes.Reserved15,
    name: "Reserved15",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved16]: {
    value: ItemTypes.Reserved16,
    name: "Reserved16",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved17]: {
    value: ItemTypes.Reserved17,
    name: "Reserved17",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved18]: {
    value: ItemTypes.Reserved18,
    name: "Reserved18",
    title: "General",
    reserved: true,
  },
  [ItemTypes.Reserved19]: {
    value: ItemTypes.Reserved19,
    name: "Reserved19",
    title: "General",
    reserved: true,
  },
} as const;

export const ItemTypeValues: readonly ItemType[] = [
  ItemTypes.Normal,
  ItemTypes.Equip,
  ItemTypes.Skill,
  ItemTypes.Tent,
  ItemTypes.Installation,
  ItemTypes.Jewel,
  ItemTypes.CannonBall,
  ItemTypes.Mapae,
  ItemTypes.Material,
  ItemTypes.Interaction,
  ItemTypes.ContentsEvent,
  ItemTypes.ToVehicle,
  ItemTypes.Reserved12,
  ItemTypes.Reserved13,
  ItemTypes.Reserved14,
  ItemTypes.Reserved15,
  ItemTypes.Reserved16,
  ItemTypes.Reserved17,
  ItemTypes.Reserved18,
  ItemTypes.Reserved19,
] as const;

export const ItemTypeByName = {
  "Normal": ItemTypes.Normal,
  "Equip": ItemTypes.Equip,
  "Skill": ItemTypes.Skill,
  "Tent": ItemTypes.Tent,
  "Installation": ItemTypes.Installation,
  "Jewel": ItemTypes.Jewel,
  "CannonBall": ItemTypes.CannonBall,
  "Mapae": ItemTypes.Mapae,
  "Material": ItemTypes.Material,
  "Interaction": ItemTypes.Interaction,
  "ContentsEvent": ItemTypes.ContentsEvent,
  "ToVehicle": ItemTypes.ToVehicle,
  "Reserved12": ItemTypes.Reserved12,
  "Reserved13": ItemTypes.Reserved13,
  "Reserved14": ItemTypes.Reserved14,
  "Reserved15": ItemTypes.Reserved15,
  "Reserved16": ItemTypes.Reserved16,
  "Reserved17": ItemTypes.Reserved17,
  "Reserved18": ItemTypes.Reserved18,
  "Reserved19": ItemTypes.Reserved19,
} as const;

export type ItemTypeNames = keyof (typeof ItemTypeByName)

const itemTypeByLowerName: Record<string, ItemType> = {};
for (const [k, v] of Object.entries(ItemTypeByName)) {
  itemTypeByLowerName[k.toLowerCase()] = v;
}

// parseItemType resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseItemType(name: string): ItemType | undefined {
  return itemTypeByLowerName[name.trim().toLowerCase()];
}
