// Code generated by enumgen from item_enhancement_types.yml. DO NOT EDIT.

export const ItemEnhancementTypes = {
  None: 0,
  Equipment: 1,
  Blackstar: 2,
  Reserved3: 3,
  Reserved4: 4,
  Reserved5: 5,
  SlumberingOrigin: 6,
  LifeSkillClothing: 7,
  UtilityEquipment: 8,
  CaravelGalleassEquipment: 9,
  ImprovedCaravelGalleassEquipment: 10,
  CarrackPanokseonEquipment: 11,
  ChiroEquipment: 12,
  Accessory: 13,
  CapotiaAccessory: 14,
  LifeSkillAccessory: 15,
  TuvalaAccessory: 16,
  SealedAsulaAccessory: 17,
  QuestAccessory: 18,
  SovereignWeapon: 19,
  TarnishedSword: 20,
  KharazadAccessory: 21,
  PreonneAccessory: 22,
  TuvalaEquipment: 23,
  EdanaArmor: 24,
  ImperfectAlchemyStone: 25,
  SturdyAlchemyStone: 26,
  SharpAlchemyStone: 27,
  ResplendentAlchemyStone: 28,
  SplendidAlchemyStone: 29,
} as const;

export type ItemEnhancementType = (typeof ItemEnhancementTypes)[keyof typeof ItemEnhancementTypes];

export interface ItemEnhancementTypeInfo {
  value: ItemEnhancementType;
  name: string;
  title: string;
  reserved?: boolean;
}

export const ItemEnhancementTypeInfos: Record<ItemEnhancementType, ItemEnhancementTypeInfo> = {
  [ItemEnhancementTypes.None]: {
    value: ItemEnhancementTypes.None,
    name: "None",
    title: "None",
  },
  [ItemEnhancementTypes.Equipment]: {
    value: ItemEnhancementTypes.Equipment,
    name: "Equipment",
    title: "Equipment",
  },
  [ItemEnhancementTypes.Blackstar]: {
    value: ItemEnhancementTypes.Blackstar,
    name: "Blackstar",
    title: "Blackstar",
  },
  [ItemEnhancementTypes.Reserved3]: {
    value: ItemEnhancementTypes.Reserved3,
    name: "Reserved3",
    title: "Reserved 3",
    reserved: true,
  },
  [ItemEnhancementTypes.Reserved4]: {
    value: ItemEnhancementTypes.Reserved4,
    name: "Reserved4",
    title: "Reserved 4",
    reserved: true,
  },
  [ItemEnhancementTypes.Reserved5]: {
    value: ItemEnhancementTypes.Reserved5,
    name: "Reserved5",
    title: "Reserved 5",
    reserved: true,
  },
  [ItemEnhancementTypes.SlumberingOrigin]: {
    value: ItemEnhancementTypes.SlumberingOrigin,
    name: "SlumberingOrigin",
    title: "Slumbering Origin",
  },
  [ItemEnhancementTypes.LifeSkillClothing]: {
    value: ItemEnhancementTypes.LifeSkillClothing,
    name: "LifeSkillClothing",
    title: "Life Skill Clothing",
  },
  [ItemEnhancementTypes.UtilityEquipment]: {
    value: ItemEnhancementTypes.UtilityEquipment,
    name: "UtilityEquipment",
    title: "Utility Equipment",
  },
  [ItemEnhancementTypes.CaravelGalleassEquipment]: {
    value: ItemEnhancementTypes.CaravelGalleassEquipment,
    name: "CaravelGalleassEquipment",
    title: "Caravel and Galleass Equipment",
  },
  [ItemEnhancementTypes.ImprovedCaravelGalleassEquipment]: {
    value: ItemEnhancementTypes.ImprovedCaravelGalleassEquipment,
    name: "ImprovedCaravelGalleassEquipment",
    title: "Improved Caravel and Galleass Equipment",
  },
  [ItemEnhancementTypes.CarrackPanokseonEquipment]: {
    value: ItemEnhancementTypes.CarrackPanokseonEquipment,
    name: "CarrackPanokseonEquipment",
    title: "Carrack and Panokseon Equipment",
  },
  [ItemEnhancementTypes.ChiroEquipment]: {
    value: ItemEnhancementTypes.ChiroEquipment,
    name: "ChiroEquipment",
    title: "Chiro Equipment",
  },
  [ItemEnhancementTypes.Accessory]: {
    value: ItemEnhancementTypes.Accessory,
    name: "Accessory",
    title: "Accessory",
  },
  [ItemEnhancementTypes.CapotiaAccessory]: {
    value: ItemEnhancementTypes.CapotiaAccessory,
    name: "CapotiaAccessory",
    title: "Capotia Accessory",
  },
  [ItemEnhancementTypes.LifeSkillAccessory]: {
    value: ItemEnhancementTypes.LifeSkillAccessory,
    name: "LifeSkillAccessory",
    title: "Life Skill Accessory",
  },
  [ItemEnhancementTypes.TuvalaAccessory]: {
    value: ItemEnhancementTypes.TuvalaAccessory,
    name: "TuvalaAccessory",
    title: "Tuvala Accessory",
  },
  [ItemEnhancementTypes.SealedAsulaAccessory]: {
    value: ItemEnhancementTypes.SealedAsulaAccessory,
    name: "SealedAsulaAccessory",
    title: "Sealed and Asula Accessory",
  },
  [ItemEnhancementTypes.QuestAccessory]: {
    value: ItemEnhancementTypes.QuestAccessory,
    name: "QuestAccessory",
    title: "Quest Accessory",
  },
  [ItemEnhancementTypes.SovereignWeapon]: {
    value: ItemEnhancementTypes.SovereignWeapon,
    name: "SovereignWeapon",
    title: "Sovereign Weapon",
  },
  [ItemEnhancementTypes.TarnishedSword]: {
    value: ItemEnhancementTypes.TarnishedSword,
    name: "TarnishedSword",
    title: "Tarnished Sword",
  },
  [ItemEnhancementTypes.KharazadAccessory]: {
    value: ItemEnhancementTypes.KharazadAccessory,
    name: "KharazadAccessory",
    title: "Kharazad Accessory",
  },
  [ItemEnhancementTypes.PreonneAccessory]: {
    value: ItemEnhancementTypes.PreonneAccessory,
    name: "PreonneAccessory",
    title: "Preonne Accessory",
  },
  [ItemEnhancementTypes.TuvalaEquipment]: {
    value: ItemEnhancementTypes.TuvalaEquipment,
    name: "TuvalaEquipment",
    title: "Tuvala Equipment",
  },
  [ItemEnhancementTypes.EdanaArmor]: {
    value: ItemEnhancementTypes.EdanaArmor,
    name: "EdanaArmor",
    title: "Edana Armor",
  },
  [ItemEnhancementTypes.ImperfectAlchemyStone]: {
    value: ItemEnhancementTypes.ImperfectAlchemyStone,
    name: "ImperfectAlchemyStone",
    title: "Imperfect Alchemy Stone",
  },
  [ItemEnhancementTypes.SturdyAlchemyStone]: {
    value: ItemEnhancementTypes.SturdyAlchemyStone,
    name: "SturdyAlchemyStone",
    title: "Sturdy Alchemy Stone",
  },
  [ItemEnhancementTypes.SharpAlchemyStone]: {
    value: ItemEnhancementTypes.SharpAlchemyStone,
    name: "SharpAlchemyStone",
    title: "Sharp Alchemy Stone",
  },
  [ItemEnhancementTypes.ResplendentAlchemyStone]: {
    value: ItemEnhancementTypes.ResplendentAlchemyStone,
    name: "ResplendentAlchemyStone",
    title: "Resplendent Alchemy Stone",
  },
  [ItemEnhancementTypes.SplendidAlchemyStone]: {
    value: ItemEnhancementTypes.SplendidAlchemyStone,
    name: "SplendidAlchemyStone",
    title: "Splendid Alchemy Stone",
  },
} as const;

export const ItemEnhancementTypeValues: readonly ItemEnhancementType[] = [
  ItemEnhancementTypes.None,
  ItemEnhancementTypes.Equipment,
  ItemEnhancementTypes.Blackstar,
  ItemEnhancementTypes.Reserved3,
  ItemEnhancementTypes.Reserved4,
  ItemEnhancementTypes.Reserved5,
  ItemEnhancementTypes.SlumberingOrigin,
  ItemEnhancementTypes.LifeSkillClothing,
  ItemEnhancementTypes.UtilityEquipment,
  ItemEnhancementTypes.CaravelGalleassEquipment,
  ItemEnhancementTypes.ImprovedCaravelGalleassEquipment,
  ItemEnhancementTypes.CarrackPanokseonEquipment,
  ItemEnhancementTypes.ChiroEquipment,
  ItemEnhancementTypes.Accessory,
  ItemEnhancementTypes.CapotiaAccessory,
  ItemEnhancementTypes.LifeSkillAccessory,
  ItemEnhancementTypes.TuvalaAccessory,
  ItemEnhancementTypes.SealedAsulaAccessory,
  ItemEnhancementTypes.QuestAccessory,
  ItemEnhancementTypes.SovereignWeapon,
  ItemEnhancementTypes.TarnishedSword,
  ItemEnhancementTypes.KharazadAccessory,
  ItemEnhancementTypes.PreonneAccessory,
  ItemEnhancementTypes.TuvalaEquipment,
  ItemEnhancementTypes.EdanaArmor,
  ItemEnhancementTypes.ImperfectAlchemyStone,
  ItemEnhancementTypes.SturdyAlchemyStone,
  ItemEnhancementTypes.SharpAlchemyStone,
  ItemEnhancementTypes.ResplendentAlchemyStone,
  ItemEnhancementTypes.SplendidAlchemyStone,
] as const;

export const ItemEnhancementTypeByName = {
  "None": ItemEnhancementTypes.None,
  "Equipment": ItemEnhancementTypes.Equipment,
  "Blackstar": ItemEnhancementTypes.Blackstar,
  "Reserved3": ItemEnhancementTypes.Reserved3,
  "Reserved4": ItemEnhancementTypes.Reserved4,
  "Reserved5": ItemEnhancementTypes.Reserved5,
  "SlumberingOrigin": ItemEnhancementTypes.SlumberingOrigin,
  "LifeSkillClothing": ItemEnhancementTypes.LifeSkillClothing,
  "UtilityEquipment": ItemEnhancementTypes.UtilityEquipment,
  "CaravelGalleassEquipment": ItemEnhancementTypes.CaravelGalleassEquipment,
  "ImprovedCaravelGalleassEquipment": ItemEnhancementTypes.ImprovedCaravelGalleassEquipment,
  "CarrackPanokseonEquipment": ItemEnhancementTypes.CarrackPanokseonEquipment,
  "ChiroEquipment": ItemEnhancementTypes.ChiroEquipment,
  "Accessory": ItemEnhancementTypes.Accessory,
  "CapotiaAccessory": ItemEnhancementTypes.CapotiaAccessory,
  "LifeSkillAccessory": ItemEnhancementTypes.LifeSkillAccessory,
  "TuvalaAccessory": ItemEnhancementTypes.TuvalaAccessory,
  "SealedAsulaAccessory": ItemEnhancementTypes.SealedAsulaAccessory,
  "QuestAccessory": ItemEnhancementTypes.QuestAccessory,
  "SovereignWeapon": ItemEnhancementTypes.SovereignWeapon,
  "TarnishedSword": ItemEnhancementTypes.TarnishedSword,
  "KharazadAccessory": ItemEnhancementTypes.KharazadAccessory,
  "PreonneAccessory": ItemEnhancementTypes.PreonneAccessory,
  "TuvalaEquipment": ItemEnhancementTypes.TuvalaEquipment,
  "EdanaArmor": ItemEnhancementTypes.EdanaArmor,
  "ImperfectAlchemyStone": ItemEnhancementTypes.ImperfectAlchemyStone,
  "SturdyAlchemyStone": ItemEnhancementTypes.SturdyAlchemyStone,
  "SharpAlchemyStone": ItemEnhancementTypes.SharpAlchemyStone,
  "ResplendentAlchemyStone": ItemEnhancementTypes.ResplendentAlchemyStone,
  "SplendidAlchemyStone": ItemEnhancementTypes.SplendidAlchemyStone,
} as const;

export type ItemEnhancementTypeNames = keyof (typeof ItemEnhancementTypeByName)

const itemEnhancementTypeByLowerName: Record<string, ItemEnhancementType> = {};
for (const [k, v] of Object.entries(ItemEnhancementTypeByName)) {
  itemEnhancementTypeByLowerName[k.toLowerCase()] = v;
}

// parseItemEnhancementType resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseItemEnhancementType(name: string): ItemEnhancementType | undefined {
  return itemEnhancementTypeByLowerName[name.trim().toLowerCase()];
}
