// Code generated by enumgen from life_skill_grades.yml. DO NOT EDIT.

export const LifeSkillGrades = {
  Unknown: -1,
  Beginner: 0,
  Apprentice: 1,
  Skilled: 2,
  Professional: 3,
  Artisan: 4,
  Master: 5,
  Guru: 6,
} as const;

export type LifeSkillGrade = (typeof LifeSkillGrades)[keyof typeof LifeSkillGrades];

// Const-only boundaries, excluded from the tables below.
export const LifeSkillGradeCount = 7;

export interface LifeSkillGradeInfo {
  value: LifeSkillGrade;
  name: string;
  title: string;
  reserved?: boolean;
  minLevel?: number;
  maxLevel?: number;
}

export const LifeSkillGradeInfos: Record<LifeSkillGrade, LifeSkillGradeInfo> = {
  [LifeSkillGrades.Unknown]: {
    value: LifeSkillGrades.Unknown,
    name: "Unknown",
    title: "Unknown",
    reserved: true,
  },
  [LifeSkillGrades.Beginner]: {
    value: LifeSkillGrades.Beginner,
    name: "Beginner",
    title: "Beginner",
    minLevel: 1,
    maxLevel: 10,
  },
  [LifeSkillGrades.Apprentice]: {
    value: LifeSkillGrades.Apprentice,
    name: "Apprentice",
    title: "Apprentice",
    minLevel: 11,
    maxLevel: 20,
  },
  [LifeSkillGrades.Skilled]: {
    value: LifeSkillGrades.Skilled,
    name: "Skilled",
    title: "Skilled",
    minLevel: 21,
    maxLevel: 30,
  },
  [LifeSkillGrades.Professional]: {
    value: LifeSkillGrades.Professional,
    name: "Professional",
    title: "Professional",
    minLevel: 31,
    maxLevel: 40,
  },
  [LifeSkillGrades.Artisan]: {
    value: LifeSkillGrades.Artisan,
    name: "Artisan",
    title: "Artisan",
    minLevel: 41,
    maxLevel: 50,
  },
  [LifeSkillGrades.Master]: {
    value: LifeSkillGrades.Master,
    name: "Master",
    title: "Master",
    minLevel: 51,
    maxLevel: 80,
  },
  [LifeSkillGrades.Guru]: {
    value: LifeSkillGrades.Guru,
    name: "Guru",
    title: "Guru",
    minLevel: 81,
    maxLevel: 180,
  },
} as const;

export const LifeSkillGradeValues: readonly LifeSkillGrade[] = [
  LifeSkillGrades.Unknown,
  LifeSkillGrades.Beginner,
  LifeSkillGrades.Apprentice,
  LifeSkillGrades.Skilled,
  LifeSkillGrades.Professional,
  LifeSkillGrades.Artisan,
  LifeSkillGrades.Master,
  LifeSkillGrades.Guru,
] as const;

export const LifeSkillGradeByName = {
  "Unknown": LifeSkillGrades.Unknown,
  "Beginner": LifeSkillGrades.Beginner,
  "Apprentice": LifeSkillGrades.Apprentice,
  "Skilled": LifeSkillGrades.Skilled,
  "Professional": LifeSkillGrades.Professional,
  "Artisan": LifeSkillGrades.Artisan,
  "Master": LifeSkillGrades.Master,
  "Guru": LifeSkillGrades.Guru,
} as const;

export type LifeSkillGradeNames = keyof (typeof LifeSkillGradeByName)

const lifeSkillGradeByLowerName: Record<string, LifeSkillGrade> = {};
for (const [k, v] of Object.entries(LifeSkillGradeByName)) {
  lifeSkillGradeByLowerName[k.toLowerCase()] = v;
}

// parseLifeSkillGrade resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseLifeSkillGrade(name: string): LifeSkillGrade | undefined {
  return lifeSkillGradeByLowerName[name.trim().toLowerCase()];
}
