// Code generated by enumgen from life_skill_types.yml. DO NOT EDIT.

import { StatIds, type StatId } from "./stats.gen";

export const LifeSkillTypes = {
  Gathering: 0,
  Fishing: 1,
  Hunting: 2,
  Cooking: 3,
  Alchemy: 4,
  Processing: 5,
  Training: 6,
  Trading: 7,
  Farming: 8,
  Sailing: 9,
  Quest: 10,
  Bartering: 11,
  Reserved12: 12,
  Reserved13: 13,
  Reserved14: 14,
} as const;

export type LifeSkillType = (typeof LifeSkillTypes)[keyof typeof LifeSkillTypes];

// Const-only boundaries, excluded from the tables below.
export const LifeSkillTypeCount = 15;

export interface LifeSkillTypeInfo {
  value: LifeSkillType;
  name: string;
  title: string;
  nativeName: string;
  playable?: boolean;
  masteryStat?: StatId;
  reserved?: boolean;
}

export const LifeSkillTypeInfos: Record<LifeSkillType, LifeSkillTypeInfo> = {
  [LifeSkillTypes.Gathering]: {
    value: LifeSkillTypes.Gathering,
    name: "Gathering",
    title: "Gathering",
    nativeName: "gathering",
    playable: true,
    masteryStat: StatIds.GatheringMastery,
  },
  [LifeSkillTypes.Fishing]: {
    value: LifeSkillTypes.Fishing,
    name: "Fishing",
    title: "Fishing",
    nativeName: "fishing",
    playable: true,
    masteryStat: StatIds.FishingMastery,
  },
  [LifeSkillTypes.Hunting]: {
    value: LifeSkillTypes.Hunting,
    name: "Hunting",
    title: "Hunting",
    nativeName: "hunting",
    playable: true,
    masteryStat: StatIds.HuntingMastery,
  },
  [LifeSkillTypes.Cooking]: {
    value: LifeSkillTypes.Cooking,
    name: "Cooking",
    title: "Cooking",
    nativeName: "cooking",
    playable: true,
    masteryStat: StatIds.CookingMastery,
  },
  [LifeSkillTypes.Alchemy]: {
    value: LifeSkillTypes.Alchemy,
    name: "Alchemy",
    title: "Alchemy",
    nativeName: "alchemy",
    playable: true,
    masteryStat: StatIds.AlchemyMastery,
  },
  [LifeSkillTypes.Processing]: {
    value: LifeSkillTypes.Processing,
    name: "Processing",
    title: "Processing",
    nativeName: "processing",
    playable: true,
    masteryStat: StatIds.ProcessingMastery,
  },
  [LifeSkillTypes.Training]: {
    value: LifeSkillTypes.Training,
    name: "Training",
    title: "Training",
    nativeName: "training",
    playable: true,
    masteryStat: StatIds.TrainingMastery,
  },
  [LifeSkillTypes.Trading]: {
    value: LifeSkillTypes.Trading,
    name: "Trading",
    title: "Trading",
    nativeName: "trading",
    playable: true,
    masteryStat: StatIds.TradingMastery,
  },
  [LifeSkillTypes.Farming]: {
    value: LifeSkillTypes.Farming,
    name: "Farming",
    title: "Farming",
    nativeName: "farming",
    playable: true,
    masteryStat: StatIds.FarmingMastery,
  },
  [LifeSkillTypes.Sailing]: {
    value: LifeSkillTypes.Sailing,
    name: "Sailing",
    title: "Sailing",
    nativeName: "sailing",
    playable: true,
    masteryStat: StatIds.SailingMastery,
  },
  [LifeSkillTypes.Quest]: {
    value: LifeSkillTypes.Quest,
    name: "Quest",
    title: "Quest",
    nativeName: "quest",
  },
  [LifeSkillTypes.Bartering]: {
    value: LifeSkillTypes.Bartering,
    name: "Bartering",
    title: "Bartering",
    nativeName: "bartering",
    playable: true,
  },
  [LifeSkillTypes.Reserved12]: {
    value: LifeSkillTypes.Reserved12,
    name: "Reserved12",
    title: "Temp",
    nativeName: "temp2",
    reserved: true,
  },
  [LifeSkillTypes.Reserved13]: {
    value: LifeSkillTypes.Reserved13,
    name: "Reserved13",
    title: "Temp",
    nativeName: "temp3",
    reserved: true,
  },
  [LifeSkillTypes.Reserved14]: {
    value: LifeSkillTypes.Reserved14,
    name: "Reserved14",
    title: "Temp",
    nativeName: "temp4",
    reserved: true,
  },
} as const;

export const LifeSkillTypeValues: readonly LifeSkillType[] = [
  LifeSkillTypes.Gathering,
  LifeSkillTypes.Fishing,
  LifeSkillTypes.Hunting,
  LifeSkillTypes.Cooking,
  LifeSkillTypes.Alchemy,
  LifeSkillTypes.Processing,
  LifeSkillTypes.Training,
  LifeSkillTypes.Trading,
  LifeSkillTypes.Farming,
  LifeSkillTypes.Sailing,
  LifeSkillTypes.Quest,
  LifeSkillTypes.Bartering,
  LifeSkillTypes.Reserved12,
  LifeSkillTypes.Reserved13,
  LifeSkillTypes.Reserved14,
] as const;

export const LifeSkillTypeByName: Record<string, LifeSkillType> = {
  "Gathering": LifeSkillTypes.Gathering,
  "Fishing": LifeSkillTypes.Fishing,
  "Hunting": LifeSkillTypes.Hunting,
  "Cooking": LifeSkillTypes.Cooking,
  "Alchemy": LifeSkillTypes.Alchemy,
  "Processing": LifeSkillTypes.Processing,
  "Training": LifeSkillTypes.Training,
  "Trading": LifeSkillTypes.Trading,
  "Farming": LifeSkillTypes.Farming,
  "Sailing": LifeSkillTypes.Sailing,
  "Quest": LifeSkillTypes.Quest,
  "Bartering": LifeSkillTypes.Bartering,
  "Reserved12": LifeSkillTypes.Reserved12,
  "Reserved13": LifeSkillTypes.Reserved13,
  "Reserved14": LifeSkillTypes.Reserved14,
} as const;

const lifeSkillTypeByLowerName: Record<string, LifeSkillType> = {};
for (const [k, v] of Object.entries(LifeSkillTypeByName)) {
  lifeSkillTypeByLowerName[k.toLowerCase()] = v;
}

// parseLifeSkillType resolves a member by name, case-insensitively, mirroring the Go
// Parse method. Returns undefined when the name is unknown.
export function parseLifeSkillType(name: string): LifeSkillType | undefined {
  return lifeSkillTypeByLowerName[name.trim().toLowerCase()];
}
