// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../../../github.com/idevelopthings/bdo-data-extractor/pipeline/models.js";

/**
 * InstallInfo is everything the setup form needs to validate a candidate game dir in
 * one round-trip: the install summary (present == valid) plus the languages and region
 * variants (regionclientdata_<region>_.xml, e.g. na, kr, eu) that install ships.
 */
export interface InstallInfo {
    "meta": pipeline$0.Meta;
    "languages": string[] | null;
    "regions": string[] | null;
}

/**
 * SetupConfig is the frontend-facing snapshot used to prefill the setup form: the
 * configured install/data dirs (falling back to the default Steam path / data dir on
 * first run) and the persisted region variant. Both the wizard and settings seed from it.
 */
export interface SetupConfig {
    "defaultDir": string;
    "gameDir": string;
    "dataDir": string;
    "region": string;
}

/**
 * SetupState tells the frontend whether the setup/extraction flow is required and
 * why, so it can show a first-run wizard vs an "an update needs re-extraction"
 * prompt. Reason is empty on a first run (or when nothing's needed); otherwise it
 * explains the staleness (app updated, or the game was patched).
 */
export interface SetupState {
    "needsSetup": boolean;
    "firstRun": boolean;
    "reason": string;
}
