// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SetupState tells the frontend whether the setup/extraction flow is required and
 * why, so it can show a first-run wizard vs an "an update needs re-extraction"
 * prompt. Reason is empty on a first run (or when nothing's needed); otherwise it
 * explains the staleness (app updated, or the game was patched).
 */
export interface SetupState {
    "needsSetup": boolean;
    "firstRun": boolean;
    "reason": string;
}
