// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound frontend-facing surface for the setup wizard. It reaches
 * the running app via application.Get() rather than holding a reference, since
 * services are constructed before application.New returns.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../../../github.com/idevelopthings/bdo-data-extractor/pipeline/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AvailableLanguages lists the localization languages present in a game install.
 */
export function AvailableLanguages(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.AvailableLanguages", dir);
}

/**
 * AvailableRegions lists the region-variant suffixes a game install ships client
 * data for (regionclientdata_<region>_.xml), e.g. na, kr, eu — for the wizard's
 * and settings' region picker. Empty means only the base file exists.
 */
export function AvailableRegions(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.AvailableRegions", dir);
}

/**
 * DefaultDataDir returns the directory to prefill the data-dir picker with.
 */
export function DefaultDataDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.DefaultDataDir");
}

/**
 * DefaultGameDir returns the directory to prefill the game-dir picker with: the
 * previously configured install if any, else the default Steam path.
 */
export function DefaultGameDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.DefaultGameDir");
}

/**
 * ForceLoadData reloads the dataset from disk even when it's already in memory — for
 * an explicit "reload" that the idempotent LoadData would skip.
 */
export function ForceLoadData(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.ForceLoadData");
}

/**
 * LoadData loads the extracted dataset into memory and returns when it's done, so the
 * frontend can await it and then show the app. It's idempotent — a no-op if the data
 * is already loaded — so React re-mounts (StrictMode in dev, an F5 reload) don't
 * reload needlessly. Progress streams over the load:* events for the loading screen.
 * Concurrent calls serialize on loadMu; a second caller returns as soon as the first
 * finishes loading.
 */
export function LoadData(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.LoadData");
}

/**
 * NeedsSetup reports whether the first-run wizard is required.
 */
export function NeedsSetup(): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.NeedsSetup");
}

/**
 * PickDirectory opens the native directory picker and returns the chosen path
 * (empty string if the user cancels).
 */
export function PickDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.PickDirectory", title);
}

/**
 * RunExtraction validates inputs, persists the chosen directories, then runs the
 * pipeline in a background goroutine, streaming progress over Wails events and
 * loading the dataset on success. It returns immediately; completion arrives via
 * the setup:done / setup:error events. Only one run may be in flight at a time —
 * the pipeline drives process-global state (config + progress sink).
 */
export function RunExtraction(gameDir: string, dataDir: string, lang: string, region: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.RunExtraction", gameDir, dataDir, lang, region);
}

/**
 * Status reports whether setup is required and why.
 */
export function Status(): $CancellablePromise<$models.SetupState> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.Status");
}

/**
 * ValidateGameDir confirms dir is a readable BDO install, returning a summary.
 */
export function ValidateGameDir(dir: string): $CancellablePromise<pipeline$0.Meta> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.ValidateGameDir", dir);
}
