// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound frontend-facing surface for the setup wizard. It reaches
 * the running app via application.Get() rather than holding a reference, since
 * services are constructed before application.New returns.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../../../github.com/idevelopthings/bdo-data-extractor/pipeline/models.js";

/**
 * AvailableLanguages lists the localization languages present in a game install.
 */
export function AvailableLanguages(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.AvailableLanguages", dir);
}

/**
 * DefaultDataDir returns the directory to prefill the data-dir picker with.
 */
export function DefaultDataDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.DefaultDataDir");
}

/**
 * DefaultGameDir returns the directory to prefill the game-dir picker with: the
 * previously configured install if any, else the default Steam path.
 */
export function DefaultGameDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.DefaultGameDir");
}

/**
 * NeedsSetup reports whether the first-run wizard is required.
 */
export function NeedsSetup(): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.NeedsSetup");
}

/**
 * PickDirectory opens the native directory picker and returns the chosen path
 * (empty string if the user cancels).
 */
export function PickDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.PickDirectory", title);
}

/**
 * RunExtraction validates inputs, persists the chosen directories, then runs the
 * pipeline in a background goroutine, streaming progress over Wails events and
 * loading the dataset on success. It returns immediately; completion arrives via
 * the setup:done / setup:error events. Only one run may be in flight at a time —
 * the pipeline drives process-global state (config + progress sink).
 */
export function RunExtraction(gameDir: string, dataDir: string, lang: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.RunExtraction", gameDir, dataDir, lang);
}

/**
 * ValidateGameDir confirms dir is a readable BDO install, returning a summary.
 */
export function ValidateGameDir(dir: string): $CancellablePromise<pipeline$0.Meta> {
    return $Call.ByName("bdo-viewer/internal/setup.Service.ValidateGameDir", dir);
}
