// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Catalog is the thin facade the frontend binds against. It owns no dataset —
 * each source owns its own — and reads the data dir live from config so a
 * re-extraction to a new location is picked up without a restart.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/urn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DataDir returns the resolved data directory (for loading map/image assets).
 */
export function DataDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.DataDir");
}

export function GetItemVendorData(u: urn$0.URN): $CancellablePromise<$models.ItemVendorData[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetItemVendorData", u);
}

/**
 * GetItemsByURN resolves a list of item URNs to their items, skipping any that
 * don't resolve. The frontend passes URN strings (urn.URN serializes as one).
 */
export function GetItemsByURN(urns: urn$0.URN[] | null): $CancellablePromise<(model$0.Item | null)[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetItemsByURN", urns);
}

/**
 * GetNpcsByURN resolves NPC URNs to their NPCs, skipping any that don't resolve
 * (thin facade over the npc Store, owned by NpcSource).
 */
export function GetNpcsByURN(urns: urn$0.URN[] | null): $CancellablePromise<(model$0.NPC | null)[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetNpcsByURN", urns);
}

/**
 * GetPlacedNpcs returns every NPC the world places at least once — the map draws a
 * marker per placement. The unplaced ones (no spawn) have nowhere to go, so they're
 * left out rather than shipped and filtered on the frontend.
 */
export function GetPlacedNpcs(): $CancellablePromise<(model$0.NPC | null)[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetPlacedNpcs");
}

/**
 * GetWorldNodes returns every worldmap node (towns, gateways, farms and their
 * co-located sub-nodes) from world.json. Each carries its urn, position, kind,
 * main flag, contribution cost and child refs — the frontend map's "our data"
 * source, an alternative to the bundled bdolytics nodes.
 */
export function GetWorldNodes(): $CancellablePromise<model$0.WorldNode[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetWorldNodes");
}

/**
 * GetWorldRegions returns every map region from world.json with its position,
 * extra worldmap marks, world-space AABB bounds and NPC/monster spawn placements
 * — for drawing region overlays (bounds boxes, spawn points) on the map.
 */
export function GetWorldRegions(): $CancellablePromise<model$0.WorldRegion[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetWorldRegions");
}

/**
 * GetWorldTerritories returns the world's territories (Balenos, Serendia, …), so
 * the frontend map can resolve a node's territory ref to a name.
 */
export function GetWorldTerritories(): $CancellablePromise<model$0.Territory[] | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.GetWorldTerritories");
}

/**
 * Item returns the item with the given URN, or nil. Thin facade over the item
 * Store (owned by ItemSource) for the frontend's direct id lookups.
 */
export function Item(u: urn$0.URN): $CancellablePromise<model$0.Item | null> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.Item", u);
}

/**
 * Types anchors model-type generation for the frontend bindings (see BindingTypes).
 */
export function Types(): $CancellablePromise<$models.BindingTypes> {
    return $Call.ByName("bdo-viewer/internal/catalog.Catalog.Types");
}
