// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";

/**
 * BindingTypes isn't called at runtime - it exists purely so these model
 * types stay referenced, keeping the Wails TS generator emitting them.
 */
export interface BindingTypes {
    "zone"?: model$0.Zone | null;
    "worldRegion"?: model$0.WorldRegion | null;
    "territory"?: model$0.Territory | null;
    "knowledgeTheme"?: model$0.KnowledgeTheme | null;
    "knowledgeEntry"?: model$0.KnowledgeEntry | null;
    "character"?: model$0.Character | null;
}

export interface ItemVendorData {
    "name": string;
    "towns": string[] | null;
}
