// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/model/models.js";

/**
 * --- Wails binding type anchors ---------------------------------------------
 * 
 * Each dataset now lives in its own source rather than on Catalog, which removed
 * the bound query methods that used to reference these model types — so the Wails
 * TS generator stopped emitting them. The frontend still imports them for its own
 * typing (region / knowledge / grindspot details, source state), and the source
 * GetEntry/GetEntryDetails paths pass them through `any`, so nothing else anchors
 * them. Returning them here keeps the generator emitting the types (and their
 * nested types) into the frontend bindings. BindingTypes isn't called at runtime;
 * add a field when the frontend needs a model type no live bound signature covers.
 */
export interface BindingTypes {
    "zone"?: model$0.Zone | null;
    "worldRegion"?: model$0.WorldRegion | null;
    "territory"?: model$0.Territory | null;
    "knowledgeTheme"?: model$0.KnowledgeTheme | null;
    "knowledgeEntry"?: model$0.KnowledgeEntry | null;
    "character"?: model$0.Character | null;
}

export interface ItemVendorData {
    "name": string;
    "towns": string[] | null;
}
