// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as setup$0 from "../../../../../bdo-viewer/internal/setup/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "setup:done": {};
            "setup:error": setup$0.ErrorPayload;
            "setup:progress": setup$0.Progress;
            "time": string;
        }
    }
}
