// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetExtractedDataDir (bound) exposes the resolved data dir to the frontend.
 */
export function GetExtractedDataDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/config.Config.GetExtractedDataDir");
}

export function GetGameDir(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/config.Config.GetGameDir");
}

export function GetMarketRegion(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/config.Config.GetMarketRegion");
}

/**
 * GetPlayer returns the player settings (life-skill mastery), bound for the
 * frontend settings panel.
 */
export function GetPlayer(): $CancellablePromise<$models.PlayerInfo> {
    return $Call.ByName("bdo-viewer/internal/config.Config.GetPlayer");
}

/**
 * SaveIfDirty for frontend wails bindings
 */
export function SaveIfDirty(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/config.Config.SaveIfDirty");
}

/**
 * SetExtractedDataDir persists a user-chosen data directory.
 */
export function SetExtractedDataDir(dir: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/config.Config.SetExtractedDataDir", dir);
}

/**
 * SetGameDir persists the user's BDO install directory.
 */
export function SetGameDir(dir: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/config.Config.SetGameDir", dir);
}

/**
 * SetMarketRegion updates the central-market region and persists it.
 */
export function SetMarketRegion(region: string): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/config.Config.SetMarketRegion", region);
}

/**
 * SetPlayerMastery updates the global life-skill mastery and persists it.
 * Negative values clamp to 0.
 */
export function SetPlayerMastery(cooking: number, alchemy: number, processing: number): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/config.Config.SetPlayerMastery", cooking, alchemy, processing);
}
