// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PlayerInfo {
    "cooking_mastery": number;
    "alchemy_mastery": number;
    "processing_mastery": number;
}
