// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ErrorPayload {
    "message": string;
}

/**
 * EventReporter adapts the pipeline's progress sink to Wails events. Per-item
 * Progress can fire thousands of times, so it's throttled; Step/Phase/Log always
 * emit. Reporter methods are called from multiple worker goroutines, so state is
 * mutex-guarded.
 */
export interface EventReporter {
}

/**
 * Progress is one update in the setup:progress stream. Step/Steps track the
 * top-level command (1..5); Phase names the current substage; Done/Total carry
 * per-item counts when a stage reports them; Log carries a freeform status line.
 */
export interface Progress {
    "step": number;
    "steps": number;
    "phase": string;
    "done": number;
    "total": number;
    "log"?: string;
}
