// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stat is one formatted title/value pair, ready to render as-is. Raw is the
 * pre-format number, so a numeric consumer (e.g. item compare) can compare
 * two Stats without re-deriving the value from Value's display string.
 */
export interface Stat {
    "title": string;
    "value": string;
    "raw"?: number | null;

    /**
     * true if negative is better, ie lower weight is better
     */
    "negate"?: boolean;
}

export interface StatGroup {
    "title"?: string;
    "kind": StatGroupKind;
    "stats": Stat[] | null;
}

export enum StatGroupKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatGroupKindNone No group, or unknown group.
     */
    StatGroupKindNone = "none",

    /**
     * StatGroupKindCard Cards are top level stat cards, typically holding things like price, weight etc.
     */
    StatGroupKindCard = "card",

    /**
     * StatGroupKindEffects Effects are the main stat group, typically holding things like AP, DP, Accuracy, Evasion etc.
     */
    StatGroupKindEffects = "effects",
};
