// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound frontend surface for updates.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../../github.com/wailsapp/wails/v3/pkg/updater/models.js";

/**
 * Check looks for a newer release now, returning it when one is available (nil
 * when up to date or on a dev build). Progress/among the wails:updater:* events.
 */
export function Check(): $CancellablePromise<updater$0.Release | null> {
    return $Call.ByName("bdo-viewer/internal/updates.Service.Check");
}

/**
 * CurrentVersion returns the running build's version.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByName("bdo-viewer/internal/updates.Service.CurrentVersion");
}

/**
 * DownloadAndInstall downloads, verifies and stages the update; download progress
 * arrives via the wails:updater:download-progress event. Call Restart to apply it.
 */
export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/updates.Service.DownloadAndInstall");
}

/**
 * Restart relaunches into the staged update.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/updates.Service.Restart");
}
