// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../urn/models.js";

/**
 * EntityRef is a lazily-resolved foreign key: URN is the durable,
 * serialized identity; Value is a runtime-only cache populated on first
 * GetValue() call via whichever Store[T] was registered for T.
 */
export type EntityRef<T> = string;

/**
 * EntityRefList is the struct-of-arrays counterpart to []*EntityRef[T]:
 * one URN slice, one lazily/partially-populated Value slice, instead of
 * N separate EntityRef allocations. Resolution is still per-element and
 * on-demand — Get(i) only resolves index i; All() resolves everything,
 * so only call it when a consumer actually wants the full expansion.
 */
export interface EntityRefList<T> {
    "urns": urn$0.URN[] | null;
}
