// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meta is a lightweight summary of a game install's PAZ index, for confirming a
 * user picked a valid directory before extracting.
 */
export interface Meta {
    "version": number;
    "pazCount": number;
    "files": number;
    "folders": number;
    "fileNames": number;
}
