// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one item's live central-market listing.
 */
export interface Entry {
    "price": number;
    "trades": number;
    "stock": number;
}

/**
 * Status is the cache's current state, for the frontend's load indicator.
 */
export interface Status {
    "region": string;
    "count": number;
    "fetched"?: string | null;
    "loading": boolean;
    "error"?: string;
}
