// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the in-memory market-price cache. The zero value isn't usable; call
 * New. Safe for concurrent use.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/urn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Fetch pulls the central-market snapshot for region (empty = the configured
 * region) and replaces the cache. A fetch already in flight is a no-op that
 * returns the current status. It's a bound method — the frontend calls it to
 * (re)load prices.
 */
export function Fetch(region: string): $CancellablePromise<$models.Status> {
    return $Call.ByName("bdo-viewer/internal/market.Service.Fetch", region);
}

/**
 * Price returns an item's live listing and whether it's currently listed.
 */
export function Price(u: urn$0.URN): $CancellablePromise<[$models.Entry, boolean]> {
    return $Call.ByName("bdo-viewer/internal/market.Service.Price", u);
}

/**
 * Prices resolves a batch of item URNs to their listings, omitting any that
 * aren't listed. Keyed by URN so the frontend can look up its BOM entries
 * directly.
 */
export function Prices(urns: urn$0.URN[] | null): $CancellablePromise<{ [_ in urn$0.URN]?: $models.Entry } | null> {
    return $Call.ByName("bdo-viewer/internal/market.Service.Prices", urns);
}

/**
 * Snapshot returns the whole cached price map, keyed by item URN — the frontend
 * loads it once after Fetch so per-item lookups stay synchronous.
 */
export function Snapshot(): $CancellablePromise<{ [_ in urn$0.URN]?: $models.Entry } | null> {
    return $Call.ByName("bdo-viewer/internal/market.Service.Snapshot");
}

/**
 * Status returns the current cache state.
 */
export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByName("bdo-viewer/internal/market.Service.Status");
}
