// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../sources/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/urn/models.js";

/**
 * CraftPlan is the resolved crafting of a single target: the quantity/yield-
 * scaled tree for display and the base materials it rolls up to (gathered /
 * bought / un-craftable leaves).
 */
export interface CraftPlan {
    "tree": RecipeTree;
    "base": Requirement[] | null;
}

/**
 * CraftTarget is one item + quantity in the calculator's craft list, with the
 * per-node recipe selections chosen for its tree (keyed by RecipeTreeNode.Path).
 */
export interface CraftTarget {
    "item": urn$0.URN;
    "qty": number;
    "selections"?: { [_ in string]?: RecipeSelection } | null;

    /**
     * CraftOverrides forces a node (by path) to craft (true) or buy (false),
     * overriding the economic default — the tree's craft/buy toggle.
     */
    "craftOverrides"?: { [_ in string]?: boolean } | null;
}

/**
 * RecipeCluster is a family of an item's recipes that share a process + slot count,
 * collapsed to per-slot alternatives — the "16 draught recipes → 1 grid" view.
 */
export interface RecipeCluster {
    "type": string;
    "station"?: string;
    "slots": RecipeSlot[] | null;
}

/**
 * RecipeSelection is which cluster and which option per slot a node resolved with.
 * The frontend echoes it back (keyed by RecipeTreeNode.Path) to re-resolve.
 */
export interface RecipeSelection {
    "cluster": number;
    "slots": number[] | null;
}

/**
 * RecipeSlot is one ingredient position of a cluster and the alternative items that
 * can fill it (e.g. Elixir of Frenzy ×30 OR Elixir of Endless Frenzy ×10).
 */
export interface RecipeSlot {
    "options": RecipeSlotOption[] | null;
}

/**
 * RecipeSlotOption is one ingredient choice for a slot: the item and how many.
 */
export interface RecipeSlotOption {
    "item": urn$0.URN;
    "count"?: number;
}

/**
 * RecipeTree is the response of ResolveRecipeTree: the resolved Root, any byproduct
 * recipes, and the deduped item objects every id refers into.
 */
export interface RecipeTree {
    "root"?: RecipeTreeNode | null;
    "byproducts"?: RecipeTreeByproduct[] | null;
    "items": { [_ in urn$0.URN]?: sources$0.ListSourceEntry } | null;
    "status"?: string;
}

/**
 * RecipeTreeByproduct is a recipe the item only procs from (see Recipe.ByproductOf):
 * RealOutput is what you actually craft, Inputs is that recipe's ingredients.
 */
export interface RecipeTreeByproduct {
    "realOutput": urn$0.URN;
    "type"?: string;
    "station"?: string;
    "inputs"?: RecipeSlotOption[] | null;
}

/**
 * RecipeTreeNode is one item in the resolved tree. Clusters/Selected describe how it
 * can be (and was) crafted; Children are the resolved ingredients of the selection.
 */
export interface RecipeTreeNode {
    /**
     * stable position id ("root", "root/0", …) — the selection key
     */
    "path": string;

    /**
     * key into RecipeTree.Items
     */
    "item": urn$0.URN;
    "count"?: number;
    "gathered"?: boolean;

    /**
     * expansion stopped: item already on the path
     */
    "cycle"?: boolean;
    "clusters"?: RecipeCluster[] | null;
    "selected"?: RecipeSelection | null;
    "children"?: (RecipeTreeNode | null)[] | null;

    /**
     * Craftable is true when the item has a production recipe, so the UI shows a
     * craft/buy toggle even when the economic default is to buy it. A craftable
     * node with Children is being crafted; without, it's bought (in the shopping
     * list) but the user can expand it to force-craft.
     */
    "craftable"?: boolean;

    /**
     * Crafts/Yield are set only by ResolveCraftPlan (the quantity-scaled calculator
     * view): Crafts is how many times this node's recipe runs (ceil(Count/Yield)),
     * Yield the per-craft output multiplier at the player's mastery (>1 = proc
     * bonus). Both are absent in the plain item-detail tree.
     */
    "crafts"?: number;
    "yield"?: number;
}

/**
 * Requirement is an item and a total quantity in a rolled-up bill of materials.
 */
export interface Requirement {
    "item": urn$0.URN;
    "count": number;
}

/**
 * Use is one recipe that consumes a given item: what it produces, by which
 * process, and how many of the queried item it takes. Output is the slim display
 * entry (see itemEntry) — the recipe UI only needs its name/grade/icon.
 */
export interface Use {
    "output": sources$0.ListSourceEntry;
    "type": string;
    "station": string;
    "count": number;
}
