// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Resolver builds crafting trees from the item and recipe tables, keyed by
 * item URN.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/urn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BillOfMaterials rolls up the combined base materials to craft every target
 * (each at its quantity and with its own recipe selections) into one shopping
 * list, summed across targets and sorted by quantity.
 */
export function BillOfMaterials(targets: $models.CraftTarget[] | null): $CancellablePromise<$models.Requirement[] | null> {
    return $Call.ByName("bdo-viewer/internal/recipe.Resolver.BillOfMaterials", targets);
}

/**
 * IsCraftable reports whether the item has at least one (non-byproduct) recipe.
 */
export function IsCraftable(u: urn$0.URN): $CancellablePromise<boolean> {
    return $Call.ByName("bdo-viewer/internal/recipe.Resolver.IsCraftable", u);
}

/**
 * ResolveCraftPlan resolves crafting qty of target into a scaled tree (honouring
 * selections, keyed by node Path) plus its base-material rollup. Child counts are
 * cumulative — an intermediate needing N units runs ceil(N/yield) crafts and its
 * inputs scale by that — so the tree shows the true totals for the requested qty.
 */
export function ResolveCraftPlan(target: urn$0.URN, qty: number, selections: { [_ in string]?: $models.RecipeSelection } | null, craftOverrides: { [_ in string]?: boolean } | null): $CancellablePromise<$models.CraftPlan> {
    return $Call.ByName("bdo-viewer/internal/recipe.Resolver.ResolveCraftPlan", target, qty, selections, craftOverrides);
}

/**
 * ResolveRecipeTree resolves the item's crafting tree, honouring selections (keyed
 * by node Path); any node without a selection uses its default (pickRecipe). Only
 * the selected path is expanded — alternatives ride along as metadata for the UI.
 */
export function ResolveRecipeTree(u: urn$0.URN, selections: { [_ in string]?: $models.RecipeSelection } | null, craftOverrides: { [_ in string]?: boolean } | null): $CancellablePromise<$models.RecipeTree> {
    return $Call.ByName("bdo-viewer/internal/recipe.Resolver.ResolveRecipeTree", u, selections, craftOverrides);
}

/**
 * UsedIn returns every recipe that uses the item as an ingredient (deduped by
 * output+type+count) — the inverse of the item's own recipes.
 */
export function UsedIn(u: urn$0.URN): $CancellablePromise<$models.Use[] | null> {
    return $Call.ByName("bdo-viewer/internal/recipe.Resolver.UsedIn", u);
}
