// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../urn/models.js";

/**
 * BindType is the game's item binding behavior ("vestedType" internally — the
 * tooltip's bind label and the "will become bound" use-warning read it).
 */
export enum BindType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * never binds (boss gear stays market-listable after equipping)
     */
    BindNone = 0,

    /**
     * binds when obtained (season gear)
     */
    BindOnObtain = 1,

    /**
     * binds when equipped/used (Manos, Loggia, Tuvala)
     */
    BindOnEquip = 2,

    /**
     * obtain-bound variant (crow/abyss gear)
     */
    BindOnObtain2 = 3,
};

/**
 * Bounds is a region's world-space extent (union of its spatial boxes).
 */
export interface Bounds {
    "min": number[];
    "max": number[];
}

/**
 * BuffStackingCategories is a set of client-defined broad buff families.
 */
export type BuffStackingCategories = BuffStackingCategory[] | null;

/**
 * BuffStackingCategory is the client category used by broad buff-family rules.
 * Known consumable values include food (1), elixir/draught (2), perfume (6),
 * Cron-meal extras (10), and whale-tendon elixirs (21).
 */
export enum BuffStackingCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    BuffStackingCategoryFood = 1,
    BuffStackingCategoryElixir = 2,
    BuffStackingCategoryPerfume = 6,
    BuffStackingCategoryCronMealExtra = 10,
    BuffStackingCategoryWhaleTendonElixir = 21,
    BuffStackingCategoryDraughtResetControl = 26,
};

/**
 * CaphrasCategory is one Caphras-enhancement cost/stat chart from
 * cronenchant.bss ("CronEnchant" is the game's internal name for the Caphras
 * system). Items map to a category via the client's computed cronKey (the
 * mapping itself is not stored client-side); the chart is shared by every item
 * of the category. Key 1..10; categories with identical charts exist (1/2,
 * 7/8) — the game distinguishes them by slot kind.
 */
export interface CaphrasCategory {
    "urn": urn$0.URN;
    "key": number;
    "levels": CaphrasEnhancement[] | null;
}

/**
 * CaphrasEnhancement is a category's chart for one enhancement level
 * (18 = TRI, 19 = TET, 20 = PEN — the only levels Caphras applies to).
 */
export interface CaphrasEnhancement {
    "enchantLevel": number;
    "steps": CaphrasLevel[] | null;
}

/**
 * CaphrasLevel is one Caphras level step: Stones is the cost of this step
 * (from the previous level), TotalStones the cumulative cost to reach it (the
 * value the table stores), and Effects the total added stats while at it, in
 * the same DSL shape as EnchantLevel.Effects so one renderer computes both.
 * 
 * The func names reuse the enhancement DSL vocabulary where the game has one:
 * ALL_AP_INCRE (AP), ALL_HIT_INCRE (accuracy), ALL_EVA_INCRE (evasion),
 * ALL_DAM_REDUCE_INCRE (damage reduction), HP_UP, MP_WP_SP_UP. The two hidden
 * stats never appear in the game's DSL, so they use extension names following
 * the same pattern: HIDDEN_EVA_INCRE, HIDDEN_DAM_REDUCE_INCRE (in-game they
 * display as a second All Evasion / Damage Reduction line).
 */
export interface CaphrasLevel {
    "level": number;
    "stones": number;
    "totalStones": number;
    "stats": CaphrasStats;
    "effects"?: EffectGroup[] | null;
}

/**
 * CaphrasStats is the eight-column cumulative stat block stored for one
 * Caphras level.
 */
export interface CaphrasStats {
    "ap"?: number;
    "accuracy"?: number;
    "evasion"?: number;
    "hiddenEvasion"?: number;
    "damageReduction"?: number;
    "hiddenDamageReduction"?: number;
    "maxHp"?: number;
    "maxMp"?: number;
}

/**
 * Category is a Monster Zone Info main/sub category: its key, display name (from
 * loc, filled by the build) and UI icon id (from the dropui*categoryinfo table).
 */
export interface Category {
    "id": number;
    "name"?: string;
    "icon"?: string;
}

/**
 * Character is a knowledge subject — the loc-table-6 entity(-ies) a knowledge card
 * is about, keyed by name slug (urn::character:<slug>). loc table 6 mixes many
 * entity kinds under one id space and has duplicate names, so a subject can't be a
 * single NPC id; it's name-keyed and aggregates the same-named entities.
 * 
 * Kind is the subject's entity kind (the most character-like of its entities'
 * kinds; from the characterstatic npcKind field where clean, else the render model
 * prefix) — empty when no entity carries a model (a place/abstract). Npcs are the
 * same-named entities that also have an npcsimply record (spawns/dialogue) — so
 * "Islin Bartali" carries npc 40001 while "Kzarka Statue" is a kind=object subject
 * (npcKind 8) with no npcs. Entities is the full per-entity characterstatic data.
 */
export interface Character {
    "urn": urn$0.URN;
    "name"?: string;
    "kind"?: CharacterKind;
    "npcs"?: models$0.EntityRefList<NPC> | null;
    "entities"?: CharacterEntity[] | null;
}

/**
 * CharacterClassType is a int8-wide identifier. The zero-cost conversion CharacterClassType(x) is
 * intentional: the underlying value is the wire value.
 */
export enum CharacterClassType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CharacterClassTypeUnknown = -1,
    CharacterClassTypeWarrior = 0,
    CharacterClassTypeHashashin = 1,
    CharacterClassTypeSage = 2,
    CharacterClassTypeWukong = 3,
    CharacterClassTypeRanger = 4,
    CharacterClassTypeGuardian = 5,
    CharacterClassTypeScholar = 6,
    CharacterClassTypeDrakania = 7,
    CharacterClassTypeSorceress = 8,
    CharacterClassTypeNova = 9,
    CharacterClassTypeCorsair = 10,
    CharacterClassTypeLahn = 11,
    CharacterClassTypeBerserker = 12,
    CharacterClassTypeReserved13 = 13,
    CharacterClassTypeReserved14 = 14,
    CharacterClassTypeMaegu = 15,
    CharacterClassTypeTamer = 16,
    CharacterClassTypeShai = 17,
    CharacterClassTypeReserved18 = 18,
    CharacterClassTypeStriker = 19,
    CharacterClassTypeMusa = 20,
    CharacterClassTypeMaehwa = 21,
    CharacterClassTypeReserved22 = 22,
    CharacterClassTypeMystic = 23,
    CharacterClassTypeValkyrie = 24,
    CharacterClassTypeKunoichi = 25,
    CharacterClassTypeNinja = 26,
    CharacterClassTypeDarkKnight = 27,
    CharacterClassTypeWizard = 28,
    CharacterClassTypeArcher = 29,
    CharacterClassTypeWoosa = 30,
    CharacterClassTypeWitch = 31,
    CharacterClassTypeSeraph = 32,
    CharacterClassTypeDosa = 33,
    CharacterClassTypeDeadeye = 34,
    CharacterClassTypeReserved35 = 35,
    CharacterClassTypeReserved36 = 36,
    CharacterClassTypeMAX = 37,
};

/**
 * CharacterClassTypeInfo is the static metadata attached to a CharacterClassType.
 */
export interface CharacterClassTypeInfo {
    "CharacterClassType": CharacterClassType;
    "Name": string;
    "Reserved": boolean;
    "Title": string;
}

/**
 * CharacterEntity is one characterstatic.dbss record behind a subject (a subject
 * aggregates same-named loc-6 entities). It carries everything we currently read
 * from the record, including still-unidentified fields, so nothing is lost.
 */
export interface CharacterEntity {
    "id": number;

    /**
     * Kind is this entity's kind (from NpcKind where clean, else the Model prefix).
     */
    "kind"?: CharacterKind;

    /**
     * NpcKind is the raw characterstatic semantic-type bitfield (low values are the
     * clean kinds; higher values carry undecoded flags for combat entities). 0 when
     * the record's id didn't land cleanly.
     */
    "npcKind"?: number;

    /**
     * Model is the asset model path (render classification / kind fallback).
     */
    "model"?: string;

    /**
     * Scripts are the entity's interaction scripts verbatim (e.g. "getknowledge(1);").
     */
    "scripts"?: string[] | null;

    /**
     * Card is the knowledge card key from a getknowledge(N) script (id-based
     * entity→card link), 0 if none.
     */
    "card"?: number;

    /**
     * Fields are the still-unidentified structured u32s that follow npcKind, captured
     * raw for future RE.
     */
    "fields"?: number[] | null;
}

/**
 * CharacterKind is the coarse entity kind of a knowledge subject, derived from the
 * characterstatic.dbss model-path prefix. A typed string so Wails emits a TS union.
 */
export enum CharacterKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CharacterKindNPC = "npc",
    CharacterKindMonster = "monster",
    CharacterKindCreature = "creature",
    CharacterKindObject = "object",
    CharacterKindGatherable = "gatherable",
    CharacterKindStructure = "structure",
    CharacterKindMount = "mount",
    CharacterKindCash = "cash",
    CharacterKindSummon = "summon",
    CharacterKindPC = "pc",
};

/**
 * CrystalGroup is a socket crystal's transfusion group: at most Max crystals of
 * the same group can be transfused at once (Max 1000 = no limit).
 */
export interface CrystalGroup {
    "key": number;
    "name": string;
    "max": number;
}

/**
 * CrystalGroupRule limits how many crystals from one family may be equipped.
 */
export interface CrystalGroupRule {
    "key": number;
    "name": string;
    "sourceName"?: string;
    "max": number;
}

/**
 * CrystalPresetSlot is a int-wide identifier. The zero-cost conversion CrystalPresetSlot(x) is
 * intentional: the underlying value is the wire value.
 */
export enum CrystalPresetSlot {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CrystalPresetSlotBase0 = 0,
    CrystalPresetSlotBase1 = 1,
    CrystalPresetSlotBase2 = 2,
    CrystalPresetSlotBase3 = 3,
    CrystalPresetSlotBase4 = 4,
    CrystalPresetSlotBase5 = 5,
    CrystalPresetSlotBase6 = 6,
    CrystalPresetSlotBase7 = 7,
    CrystalPresetSlotBase8 = 8,
    CrystalPresetSlotBase9 = 9,
    CrystalPresetSlotBase10 = 10,
    CrystalPresetSlotBase11 = 11,
    CrystalPresetSlotCostume = 12,
    CrystalPresetSlotHeartL = 13,
    CrystalPresetSlotHeartR = 14,
    CrystalPresetSlotLoMLL = 15,
    CrystalPresetSlotLoMLR = 16,
    CrystalPresetSlotDawnNecklace = 17,
    CrystalPresetSlotDawnRingI = 18,
    CrystalPresetSlotDawnRingII = 19,
    CrystalPresetSlotDawnEarringI = 20,
    CrystalPresetSlotDawnEarringII = 21,
    CrystalPresetSlotDawnBelt = 22,
    CrystalPresetSlotMAX = 23,
};

/**
 * CrystalRules contains transfusion-family limits and special-slot restrictions.
 */
export interface CrystalRules {
    "groups": CrystalGroupRule[] | null;
    "specialSlots": CrystalSpecialSlotRule[] | null;
}

/**
 * CrystalSpecialSlot is a uint8-wide identifier. The zero-cost conversion CrystalSpecialSlot(x) is
 * intentional: the underlying value is the wire value.
 */
export enum CrystalSpecialSlot {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CrystalSpecialSlotPearlAvatarChest = 14,
    CrystalSpecialSlotNecklace = 17,
    CrystalSpecialSlotRingI = 18,
    CrystalSpecialSlotRingII = 19,
    CrystalSpecialSlotEarringI = 20,
    CrystalSpecialSlotEarringII = 21,
    CrystalSpecialSlotBelt = 22,
};

/**
 * CrystalSpecialSlotRule lists crystal families accepted by a special slot.
 */
export interface CrystalSpecialSlotRule {
    "slot": CrystalSpecialSlot;
    "allowedGroups": number[] | null;
}

export interface EffectGroup {
    "title": string;
    "marker"?: string;
    "pieces"?: number;
    "stats": StatMod[] | null;
}

/**
 * Effects is what a consumable applies on use: a cooldown/maximum duration, the
 * shown stat modifiers, and any hidden buffs the client doesn't display (kept
 * separate; their names may still be untranslated Korean pending a future map).
 */
export interface Effects {
    /**
     * item-use cooldown (skill.dbss)
     */
    "cooldownMs"?: number;

    /**
     * longest timed modifier
     */
    "durationMs"?: number;
    "stats"?: EffectGroup;
    "hidden"?: EffectGroup;

    /**
     * BuffCategories contains every broad family present in the complete buff chain.
     */
    "buffCategories"?: BuffStackingCategories;

    /**
     * ClearsBuffCategories lists broad families removed when the item is used.
     */
    "clearsBuffCategories"?: BuffStackingCategories;
}

/**
 * EnchantCombatStat is one damage-type lane from an enchant-curve row.
 */
export interface EnchantCombatStat {
    "apMin"?: number;
    "apMax"?: number;
    "ap"?: number;
    "accuracy"?: number;
    "accuracyDice"?: string;
    "evasion"?: number;
    "addedEvasion"?: number;
    "damageReduction"?: number;
    "addedDamageReduction"?: number;
    "unknownAttack167"?: number;
    "unknownAttack179"?: number;
}

/**
 * EnchantCombatStats preserves the melee, ranged, and magic lanes stored in an
 * enchant-curve row. The top-level EnchantLevel fields are their display maxima.
 */
export interface EnchantCombatStats {
    "melee"?: EnchantCombatStat | null;
    "ranged"?: EnchantCombatStat | null;
    "magic"?: EnchantCombatStat | null;
}

/**
 * EnchantIndexedStat preserves a populated slot from a fixed stat array whose
 * client enum index is not fully mapped yet.
 */
export interface EnchantIndexedStat {
    "index": number;
    "value": number;
}

/**
 * EnchantLevel is the gear stats + effects at one enhancement level.
 * 
 * Caphras is the Caphras chart for this level — the 20 Caphras step stats
 * stacked on top of the level's base stats. Only levels 18/19/20 (TRI/TET/PEN)
 * of a Caphras-enhanceable item carry it; nil otherwise. It lives here (rather
 * than as a parallel per-level array on Enhancement) because a Caphras chart is
 * inherently the stats added at a given enhancement level.
 */
export interface EnchantLevel {
    "level": number;

    /**
     * Name is the scheme-aware display label — "Base", "+1"…"+15", or a roman tier
     * "PRI (I)"…"DEC (X)" (accessories/endgame lines start at PRI, gear runs +1..+15
     * first). Precomputed so consumers don't re-derive the scheme.
     */
    "name": string;
    "apMin"?: number;
    "apMax"?: number;

    /**
     * display AP = round((min+max)/2)
     */
    "ap"?: number;

    /**
     * weapon accuracy (post-DSL tail; hidden in the tooltip for most weapons)
     */
    "accuracy"?: number;
    "evasion"?: number;
    "damageReduction"?: number;

    /**
     * = evasion + damageReduction
     */
    "dp"?: number;

    /**
     * AddedEvasion / AddedDamageReduction are the extra defense a sub-weapon/armor
     * piece grants on top of its own Evasion/DamageReduction (the "(+N)" in the
     * tooltip, e.g. Blackstar Horn Bow "Evasion 11 (+33)"). From the post-DSL tail.
     */
    "addedEvasion"?: number;
    "addedDamageReduction"?: number;
    "maxHp"?: number;

    /**
     * Durability is the item's max durability at this enhancement level — it rises
     * with enhancement (base 100 through TRI 160 / TET 180 / PEN 200), so it's a
     * real per-level value, not constant.
     */
    "durability"?: number;

    /**
     * EnhanceChance is the base success probability (0 failstacks) to enhance at this
     * level — a fraction 0..1 (@41 ÷ 1,000,000). Follows the game's curve: 1.0 for
     * +1..+7, then dropping (PRI ~0.13, TET ~0.005, PEN ~0.002).
     */
    "enhanceChance"?: number;

    /**
     * item + set effects (DSL formulas)
     */
    "effects"?: EffectGroup[] | null;

    /**
     * SourceDescription is the optional source-language enhancement description
     * embedded before the effect DSL. Ship equipment uses it for formatted stat text.
     */
    "sourceDescription"?: string;

    /**
     * CombatStats preserves the melee, ranged, and magic values independently.
     */
    "combatStats"?: EnchantCombatStats | null;

    /**
     * SpeciesAP preserves populated slots from the fixed species-damage array.
     */
    "speciesAp"?: EnchantIndexedStat[] | null;

    /**
     * EnhancementAids lists alternative enhancement items accepted at this level,
     * such as J's Hammer of Loyalty, Primordial Hammer, and Crystals of Origin.
     */
    "enhancementAids"?: models$0.EntityRefList<Item>;

    /**
     * the lowest enhancement level that can carry Caphras
     */
    "caphrasMinLevel"?: number;

    /**
     * the highest enhancement level that can carry Caphras
     */
    "caphrasMaxLevel"?: number;

    /**
     * Caphras steps at this level (18/19/20 only)
     */
    "caphras"?: CaphrasLevel[] | null;

    /**
     * @4 u32; high-cardinality internal value
     */
    "unknown4"?: number | null;

    /**
     * @8 u32
     */
    "unknown8"?: number | null;

    /**
     * @12 u32
     */
    "unknown12"?: number | null;

    /**
     * @16 u32
     */
    "unknown16"?: number | null;

    /**
     * @20 u32
     */
    "unknown20"?: number | null;

    /**
     * @24 u8
     */
    "unknown24"?: number | null;

    /**
     * @25 u32; rises with enhancement
     */
    "unknown25"?: number | null;

    /**
     * @29 u32
     */
    "unknown29"?: number | null;

    /**
     * @33 u32
     */
    "unknown33"?: number | null;

    /**
     * @37 u32
     */
    "unknown37"?: number | null;

    /**
     * @45 u32; commonly rate-like
     */
    "unknown45"?: number | null;

    /**
     * @49 u32
     */
    "unknown49"?: number | null;

    /**
     * @55 u16; enhancement parameter
     */
    "unknown55"?: number | null;

    /**
     * @57 u16; commonly 10
     */
    "unknown57"?: number | null;

    /**
     * @59 u8
     */
    "unknown59"?: number | null;

    /**
     * @60 u16; rises with enhancement
     */
    "unknown60"?: number | null;

    /**
     * @166 u8; combat-stat lane flag
     */
    "unknown166"?: number | null;

    /**
     * @251 u32; packed field before descriptions
     */
    "unknown251"?: number | null;

    /**
     * display tail +0 u8
     */
    "unknownDisplay0"?: number | null;

    /**
     * display tail +1 u8
     */
    "unknownDisplay1"?: number | null;

    /**
     * display tail +2 u32; normally 1,000,000
     */
    "unknownRate1"?: number | null;

    /**
     * display tail +6 u32; normally 700,000
     */
    "unknownRate2"?: number | null;

    /**
     * display tail +10 u8
     */
    "unknownDisplay10"?: number | null;

    /**
     * display tail +11 u8
     */
    "unknownDisplay11"?: number | null;

    /**
     * display tail +12 u8
     */
    "unknownDisplay12"?: number | null;

    /**
     * UnknownTail12 is the 65-byte structured block after three -1 sentinels and
     * before the counted enhancement-aid item list. JSON encodes it as base64.
     */
    "unknownTail12"?: string | null;

    /**
     * UnknownFooter is the final six bytes after the enhancement-aid item list.
     */
    "unknownFooter"?: string | null;
}

/**
 * Enhancement is an item's full per-level curve, linked via its EnchantKey (baseId).
 * 
 * CaphrasCategory keys the Caphras chart (caphras.json) the item follows at
 * enhancement 18-20; 0 = not Caphras-enhanceable. The game computes this key
 * inside the client executable, so it is DERIVED here from client-side fields
 * (slot kind x a buy-price tier: boss >= 10M, blue >= 2M, else green) --
 * validated chart-exact against 1,315 community-labeled items with no false
 * positives in the eligibility domain (max level 20 weapons/armor).
 */
export interface Enhancement {
    "urn": urn$0.URN;
    "baseId": number;
    "caphrasCategory"?: models$0.EntityRef<CaphrasCategory> | null;

    /**
     * the lowest level in Levels (usually 0, sometimes 1)
     */
    "minLevel": number;

    /**
     * the index of the EnchantLevel matching MinLevel
     */
    "minLevelIdx": number;

    /**
     * the highest level in Levels (usually 15, sometimes 20)
     */
    "maxLevel": number;

    /**
     * the index of the EnchantLevel matching MaxLevel
     */
    "maxLevelIdx": number;
    "levels"?: EnchantLevel[] | null;
}

/**
 * EquipInfo groups an equippable item's slot taxonomy.
 */
export interface EquipInfo {
    /**
     * Slot is the normalized, class-independent
     * equip slot (@14) — the only slot source for artifacts, life/gathering tools and
     * costume accessories whose Type is blank. Not omitempty: Main Weapon is slot 0,
     * and EquipInfo only exists for equippables, so the zero value is meaningful.
     */
    "slot": SlotName;

    /**
     * Kind is the broad gear class (Weapon/Armor/Other, itemenchant @15);
     */
    "kind"?: string;

    /**
     * Type is the specific EquipType (@7), the weapon class for weapons.
     */
    "type"?: string;

    /**
     * Slots lists every slot the item occupies (@14 + @16-18)
     * for multi-slot items like functional costumes; absent = single-slot.
     */
    "slots"?: SlotName[] | null;
}

/**
 * Item is the merged view of one game item, assembled from several decoded
 * client tables. Fields are omitted from JSON when empty/unknown so the output
 * stays compact. All values come from the client files (no scraping).
 */
export interface Item {
    "urn": urn$0.URN;
    "id": number;

    /**
     * languagedata_<lang>.loc
     */
    "name"?: string;

    /**
     * VariantOf groups reissued copies of the same item: the game mints bound
     * reward/season/box variants under new ids (e.g. Nouver Kunai exists 8x:
     * the tradeable base + 7 untradeable copies, some carrying slightly older
     * stat-curve snapshots). Copies matching on (name, itemType, category,
     * grade, icon) point at the canonical record — the tradeable/market item
     * when one exists. 0/absent = canonical. Ghost marks name-only records
     * (a localization entry with no item data behind it — retired/re-id'd
     * items); ghosts are kept for id coverage but carry nothing.
     */
    "variantOf"?: models$0.EntityRef<Item> | null;
    "ghost"?: boolean;

    /**
     * languagedata_<lang>.loc
     */
    "description"?: string;

    /**
     * languagedata_<lang>.loc  use/open confirmation; lists box/chest contents
     */
    "useText"?: string;

    /**
     * languagedata_<lang>.loc  NPC exchange offers (location + rate)
     */
    "exchangeInfo"?: string;

    /**
     * itemenchant.dbss  (embedded path)
     */
    "icon"?: string;

    /**
     * itemenchant.dbss  GradeType
     */
    "grade": ItemGrade;

    /**
     * itemenchant.dbss  ItemClassify (game category)
     */
    "category"?: string;

    /**
     * itemenchant.dbss EItemType; Title is the tooltip classification
     */
    "itemType": ItemType;

    /**
     * itemenchant.dbss  equip slot/kind/type (equipment)
     */
    "equipInfo"?: EquipInfo | null;

    /**
     * central-market main category (@200, or derived — see Marketable)
     */
    "marketCategory"?: string;

    /**
     * central-market sub category (@201, or derived)
     */
    "marketSubCategory"?: string;

    /**
     * the game's central-market-allowed flag (itemenchant iconEnd+0); a market category with marketable=false is derived for unlistable gear (Tuvala/boss gear)
     */
    "marketable"?: boolean;

    /**
     * BindType is the game's vestedType (binding behavior) — see the BindType
     * constants.
     */
    "bindType"?: BindType;

    /**
     * max units per market registration (gear 5, potions 500, mem frags 1000); absent = not listable
     */
    "marketRegisterLimit"?: number;

    /**
     * itemenchant.dbss  (LT)
     */
    "weight": number;

    /**
     * itemenchant.dbss  OriginalPrice
     */
    "buyPrice": number;

    /**
     * itemenchant.dbss  SellPriceToNpc
     */
    "sellPrice": number;

    /**
     * itemenchant.dbss  RepairPrice
     */
    "repairPrice": number;

    /**
     * itemenchant.dbss  (u16 @185, equipment)
     */
    "maxDurability"?: number;

    /**
     * class restriction (itemenchant mask @77); absent = all classes
     */
    "classes"?: string[] | null;

    /**
     * timed items, e.g. "(7 Days)" = 10080 (u32 @69)
     */
    "expirationMinutes"?: number;

    /**
     * required character level, e.g. 56 for awakening weapons (@97)
     */
    "requiredLevel"?: number;

    /**
     * explicit stack limit (u32 @101); absent = unlimited/default
     */
    "maxStack"?: number;

    /**
     * dyeable part count (@160)
     */
    "dyeParts"?: number;

    /**
     * crystal transfusion group (record footer + loc table 121)
     */
    "crystalGroup"?: CrystalGroup | null;

    /**
     * EnhancementGroupKey identifies the item's specific enhancement family.
     */
    "enhancementGroupKey"?: number;

    /**
     * EnhancementType identifies the broader enhancement system used by the item.
     */
    "enhancementType"?: ItemEnhancementType;

    /**
     * UnlocksDawnCrystalSlot is the client static-status predicate used to
     * unlock the matching necklace, ring, earring or belt crystal-preset slot.
     */
    "unlocksDawnCrystalSlot"?: boolean;

    /**
     * ReformsFrom / ReformsInto come from itemimprovement.dbss (gear reform chains).
     * source items that can reform into this one
     */
    "reformsFrom"?: models$0.EntityRefList<Item> | null;

    /**
     * results this item can reform into
     */
    "reformsInto"?: models$0.EntityRefList<Item> | null;

    /**
     * a raw/gathered material (itemmaking.xml node/collect/fishing)
     */
    "gathered"?: boolean;

    /**
     * ItemMaterial (@62) groups gear into material/model families: melee &
     * staff weapons 40, longbow 42, kunai 51, classic boss armor 71 vs other
     * armor 72, accessories by slot (necklace 73, ring 74, earring 75,
     * belt 76), horse gear 123. Named by reference-dictionary correlation
     * with 99% agreement; see FORMATS §3.
     */
    "itemMaterial"?: number;

    /**
     * The following were identified by correlating itemenchant rows against a
     * labeled reference field dictionary over the ~28k shared item ids
     * (two-sided agreement ≥93% unless noted; FORMATS §3).
     * @67 IsStack
     */
    "stackable"?: boolean;

    /**
     * @68 DoApplyDirectly — consumed/applied on obtain
     */
    "applyDirectly"?: boolean;

    /**
     * @73 — the classic binding enum; distinct from BindType (icon+15), which the tooltip/bind-warning UI reads
     */
    "vestedType"?: number;

    /**
     * @74 IsUserVested — character/family-bound
     */
    "userVested"?: boolean;

    /**
     * @75 IsForTrade — a trading-skill goods item (crates, trade packs)
     */
    "forTrade"?: boolean;

    /**
     * @76 — trade-goods subtype
     */
    "tradeType"?: number;

    /**
     * @105 — life-skill XP family
     */
    "lifeExpType"?: number;

    /**
     * @134 ContentsEventType (u8; 171/0 = none, omitted)
     */
    "eventType"?: number;

    /**
     * @136 ContentsEventParam1 (u32; often a content ref id)
     */
    "eventParam1"?: number;

    /**
     * @140 ContentsEventParam2 (u32)
     */
    "eventParam2"?: number;

    /**
     * @151 == 0 (inverse of HideFromNote; most items are hidden from the note UI)
     */
    "shownInNote"?: boolean;

    /**
     * @152 IsCash — pearl-shop item
     */
    "cash"?: boolean;

    /**
     * @153 CronEnchantcontrol
     */
    "cronEnchant"?: number;

    /**
     * @156 IsDyeable (DyeParts @160 holds the part count)
     */
    "dyeable"?: boolean;

    /**
     * @184 IsPersonalTrade — can be handed player-to-player (Beer, Purified Water, Star Anise Tea…; 329 items)
     */
    "personalTrade"?: boolean;

    /**
     * @190 — trade goods sellable without node connection
     */
    "nodeFreeTrade"?: boolean;

    /**
     * FamilyInventory is the client's checkPushFamilyInventory flag (icon-block
     * +13 == 2): the item can be stored in the account-wide Family Inventory to
     * share across your characters. Family Inventory is a restricted whitelist
     * (~1,089 items — mostly potions, cooked food, pearl goods, timed EXP/buff
     * scrolls like Book of Combat/Life and Mercenary's Life); most items default
     * to not-allowed.
     */
    "familyInventory"?: boolean;

    /**
     * ContributionCost is the Contribution Points required to rent or place the
     * item (the reference schema's NeedContribute), recovered when you return
     * it. Set on 233 items: "[CP]" rental gear (e.g. [CP] Nesser Longsword = 50,
     * [CP] Kaia/Carnage weapons) and placeable fences/tents ([CP] Strong Fence
     * = 10). Decoded from the type-dependent tail (a u32 after a marker); 0 = none.
     */
    "contributionCost"?: number;

    /**
     * header @8-13 — a cluster of boolean/enum flags (unknown11 is set on 26,406
     * items; unknown12 defaults to 2).
     */
    "unknown8"?: number | null;
    "unknown9"?: number | null;
    "unknown10"?: number | null;
    "unknown11"?: number | null;
    "unknown12"?: number | null;
    "unknown13"?: number | null;

    /**
     * header @85-88 — a single u32 bitfield of item property flags (set on 903
     * items, 29 distinct bit combos; 0x1ec28000 dominant on 287). Read as one u32,
     * not four bytes.
     */
    "unknown85"?: number | null;

    /**
     * header @93 — small enum (1|4); equals unknown98 on every one of the 105
     * items that set it (a duplicated field).
     */
    "unknown93"?: number | null;

    /**
     * header @98-100, @106-108 — small enums on ~100 items each.
     */
    "unknown98"?: number | null;
    "unknown99"?: number | null;
    "unknown100"?: number | null;
    "unknown106"?: number | null;
    "unknown107"?: number | null;
    "unknown108"?: number | null;

    /**
     * header @135 — reads 171 (the ContentsEventType "no-event" sentinel) on 104
     * items; likely part of the event struct at @134.
     */
    "unknown135"?: number | null;

    /**
     * header @144 (u16) — a per-item-class constant on ~381 Etc/material items
     * (trade loot 1000, fences 10, reforge stones 149); NOT the CP cost.
     */
    "unknown144"?: number | null;

    /**
     * Header @146-157 is a four-field block between event data and the
     * item-property flags: u32, u16, u16, u32. The first two use all-ones
     * sentinels; unknown152 is commonly 1000.
     */
    "unknown146"?: number | null;
    "unknown150"?: number | null;
    "unknown152"?: number | null;
    "unknown154"?: number | null;

    /**
     * Header @158-162 — @159/@161/@162 use 255 sentinels; @160 is a small enum.
     */
    "unknown158"?: number | null;
    "unknown159"?: number | null;
    "unknown160"?: number | null;
    "unknown161"?: number | null;
    "unknown162"?: number | null;

    /**
     * Header @166-167 (@167 weakly matched isGuildStockable, 74%), @169 default 1.
     */
    "unknown166"?: number | null;
    "unknown167"?: number | null;
    "unknown169"?: number | null;

    /**
     * Header @170-171 is an unidentified u16 value.
     */
    "unknown170"?: number | null;

    /**
     * Header @173-181 and @188-190. unknown180 + unknown188 are a PAIRED field
     * — they fire on the exact same 16,655 items (8 bytes apart, ~20 values each),
     * a strong candidate for a two-part record.
     */
    "unknown173"?: number | null;
    "unknown174"?: number | null;
    "unknown176"?: number | null;
    "unknown178"?: number | null;
    "unknown180"?: number | null;
    "unknown181"?: number | null;
    "unknown182"?: number | null;
    "unknown188"?: number | null;
    "unknown189"?: number | null;
    "unknown190"?: number | null;
    "unknown192"?: number | null;

    /**
     * Header @199, @203 (default 1) — flags.
     */
    "unknown199"?: number | null;
    "unknown203"?: number | null;

    /**
     * icon-block +1..+3 — small enums; unknownIcon2 defaults to 9 (its only
     * deviants are the currencies: Silver/Loyalties/Crow Coin/Hardcore Coin).
     */
    "unknownIcon1"?: number | null;
    "unknownIcon2"?: number | null;
    "unknownIcon3"?: number | null;

    /**
     * icon-block +8 (default 2): value 1 on 271 Cook items — both finished dishes
     * and effectless intermediate sauces/ingredients. Likely a cooking-product/
     * ingredient flag. NOT a food training-stat type (it's on effectless sauces
     * and doesn't track the dish's buff).
     */
    "unknownIcon8"?: number | null;
    "unknownIcon9"?: number | null;

    /**
     * icon-block +10 (default 0): value 15/85 on 52 finished foods. Likely a food
     * grade/tier or buff-duration bracket — constant (15) across dishes with very
     * different buffs, so NOT a per-stat training amount.
     */
    "unknownIcon10"?: number | null;
    "unknownIcon14"?: number | null;

    /**
     * icon-block +16 (default 1): a ternary. 2 = a raw gatherable/worker-node
     * resource (ore, timber, fish, hide, crops — Iron Ore, Coal, Rough Stone…);
     * 0 = special/pearl/cash goods (SpecialGoods, PearlGoods). Best guess: an
     * item resource/source class.
     */
    "unknownIcon16"?: number | null;

    /**
     * UnknownAfterMarketLimit0 begins the fixed property prefix after the three
     * variable strings and market registration limit.
     */
    "unknownAfterMarketLimit0"?: number | null;
    "unknownAfterMarketLimit79"?: number | null;
    "unknownAfterMarketLimit80"?: number | null;
    "unknownAfterMarketLimit81"?: number | null;
    "unknownAfterMarketLimit85"?: number | null;
    "unknownAfterMarketLimit89"?: number | null;
    "unknownAfterMarketLimit93"?: number | null;
    "unknownAfterMarketLimit97"?: number | null;
    "unknownAfterMarketLimit101"?: number | null;

    /**
     * Acquisition, from the per-item info XML (ui_html/xml/<lang>/<id>.xml). The XML
     * names entities in prose, so the build resolves them: <shop> character names to
     * NPC character templates (whose Spawns are the placed vendor variants), and
     * <node region="A - B"> to the "B" production sub-node under main node "A".
     * Vendors are NPC references resolved from <shop> character names.
     */
    "vendors"?: models$0.EntityRefList<NPC> | null;

    /**
     * UnresolvedVendors are <shop> names that could not be resolved to NPC references.
     */
    "unresolvedVendors"?: string[] | null;

    /**
     * RentalOffers are contribution-point rentals decoded from NPC dialogue actions.
     */
    "rentalOffers"?: ItemRentalOffer[] | null;

    /**
     * GatheredFrom contains <collect> source names such as "Wild Flax".
     */
    "gatheredFrom"?: string[] | null;

    /**
     * GatherNodes are world-node references resolved from <node region="..."> names.
     */
    "gatherNodes"?: models$0.EntityRefList<WorldNode> | null;

    /**
     * UnresolvedGatherNodes are <node region="..."> names that could not be resolved
     * to a world-node reference. The original client text is retained losslessly.
     */
    "unresolvedGatherNodes"?: string[] | null;

    /**
     * Consumable (food/elixir) buff info, decoded from the item->skill->buff
     * chain (skill.dbss + buff.dbss), named via loc table 5. Fully client-typed.
     */
    "effects"?: Effects | null;

    /**
     * itemmaxlevel.dbss
     */
    "maxEnhance"?: number | null;

    /**
     * enchantstaticstatus.dbss curve
     */
    "enhancement"?: Enhancement | null;
    "itemSets"?: models$0.EntityRefList<ItemSet> | null;
}

/**
 * ItemEnhancementType is a uint32-wide identifier. The zero-cost conversion ItemEnhancementType(x) is
 * intentional: the underlying value is the wire value.
 */
export enum ItemEnhancementType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemEnhancementTypeNone = 0,
    ItemEnhancementTypeEquipment = 1,
    ItemEnhancementTypeBlackstar = 2,
    ItemEnhancementTypeReserved3 = 3,
    ItemEnhancementTypeReserved4 = 4,
    ItemEnhancementTypeReserved5 = 5,
    ItemEnhancementTypeSlumberingOrigin = 6,
    ItemEnhancementTypeLifeSkillClothing = 7,
    ItemEnhancementTypeUtilityEquipment = 8,
    ItemEnhancementTypeCaravelGalleassEquipment = 9,
    ItemEnhancementTypeImprovedCaravelGalleassEquipment = 10,
    ItemEnhancementTypeCarrackPanokseonEquipment = 11,
    ItemEnhancementTypeChiroEquipment = 12,
    ItemEnhancementTypeAccessory = 13,
    ItemEnhancementTypeCapotiaAccessory = 14,
    ItemEnhancementTypeLifeSkillAccessory = 15,
    ItemEnhancementTypeTuvalaAccessory = 16,
    ItemEnhancementTypeSealedAsulaAccessory = 17,
    ItemEnhancementTypeQuestAccessory = 18,
    ItemEnhancementTypeSovereignWeapon = 19,
    ItemEnhancementTypeTarnishedSword = 20,
    ItemEnhancementTypeKharazadAccessory = 21,
    ItemEnhancementTypePreonneAccessory = 22,
    ItemEnhancementTypeTuvalaEquipment = 23,
    ItemEnhancementTypeEdanaArmor = 24,
    ItemEnhancementTypeImperfectAlchemyStone = 25,
    ItemEnhancementTypeSturdyAlchemyStone = 26,
    ItemEnhancementTypeSharpAlchemyStone = 27,
    ItemEnhancementTypeResplendentAlchemyStone = 28,
    ItemEnhancementTypeSplendidAlchemyStone = 29,
};

/**
 * ItemGrade is a int8-wide identifier. The zero-cost conversion ItemGrade(x) is
 * intentional: the underlying value is the wire value.
 */
export enum ItemGrade {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemGradeNone = -1,
    ItemGradeWhite = 0,
    ItemGradeGreen = 1,
    ItemGradeBlue = 2,
    ItemGradeYellow = 3,
    ItemGradeRed = 4,
    ItemGradePurple = 5,
};

/**
 * ItemRentalOffer is one NPC dialogue action that rents the containing item.
 */
export interface ItemRentalOffer {
    "vendor": models$0.EntityRef<NPC> | null;
    "dialogIndex"?: number;
    "conditionDsl"?: string;
    "count": number;
    "pointType": number;
    "pointCost": number;
    "itemSubKey": number;

    /**
     * Unknown0 separates the dialogue label from its action variant.
     */
    "unknown0": number;
}

/**
 * ItemSet is one skillpiece definition and the items linked to it.
 */
export interface ItemSet {
    "urn": urn$0.URN;
    "skillNo": number;
    "bonuses": ItemSetBonus[] | null;
    "items"?: models$0.EntityRefList<Item> | null;
    "membershipSources"?: ItemSetMembershipSource[] | null;
}

/**
 * ItemSetBonus is one piece-count tier displayed by the client.
 */
export interface ItemSetBonus {
    "pieces": number;
    "apply": number;
    "groupTitle"?: string;
    "descriptionTitle"?: string;
    "description"?: string;
}

/**
 * ItemSetMembershipSource describes how an item-to-set relation was recovered.
 */
export enum ItemSetMembershipSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ItemSetMembershipDSL is a relation carried by an enhancement DSL function.
     */
    ItemSetMembershipDSL = "dsl",

    /**
     * ItemSetMembershipExplicit is a confirmed family with no recovered client-side foreign key.
     */
    ItemSetMembershipExplicit = "explicit",
};

/**
 * ItemType is a uint8-wide identifier. The zero-cost conversion ItemType(x) is
 * intentional: the underlying value is the wire value.
 */
export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ItemTypeNormal = 0,
    ItemTypeEquip = 1,
    ItemTypeSkill = 2,
    ItemTypeTent = 3,
    ItemTypeInstallation = 4,
    ItemTypeJewel = 5,
    ItemTypeCannonBall = 6,
    ItemTypeMapae = 7,
    ItemTypeMaterial = 8,
    ItemTypeInteraction = 9,
    ItemTypeContentsEvent = 10,
    ItemTypeToVehicle = 11,
    ItemTypeReserved12 = 12,
    ItemTypeReserved13 = 13,
    ItemTypeReserved14 = 14,
    ItemTypeReserved15 = 15,
    ItemTypeReserved16 = 16,
    ItemTypeReserved17 = 17,
    ItemTypeReserved18 = 18,
    ItemTypeReserved19 = 19,
};

/**
 * KnowledgeEntry is one knowledge card (mentalcard.dbss): an entry under a theme,
 * with the favor/interest values used by the amity minigame. Item is the
 * single-entry knowledge item whose name matches this entry, if any.
 */
export interface KnowledgeEntry {
    "urn": urn$0.URN;
    "key": number;
    "theme"?: models$0.EntityRef<KnowledgeTheme> | null;
    "name"?: string;
    "description"?: string;

    /**
     * how the entry is obtained (loc table 34, column 2)
     */
    "acquisition"?: string;
    "image"?: string;
    "minFavor"?: number;
    "maxFavor"?: number;
    "interest"?: number;
    "item"?: models$0.EntityRef<Item> | null;

    /**
     * Character is the loc-6 entity (NPC/monster/statue/place) this entry is
     * about, matched by name; keyed by name slug (urn::character:<slug>).
     */
    "character"?: models$0.EntityRef<Character> | null;

    /**
     * Unknown20 (@20) is a flags bitfield we've mapped positionally but not yet
     * identified — obtain/display flags (its 18 values spread evenly across every
     * category, so it is NOT the subject kind; the kind is the theme category:
     * Characters / Ecology / Topography / Trade / …). Deviation-only, default 4.
     * (The @24–39 region after it is a packed sub-structure — u32 reads there come
     * back as `N<<8`, the item-RE misalignment tell — so it's read through, not
     * fielded, until its byte widths are cracked.)
     */
    "unknown20"?: number | null;
}

/**
 * KnowledgeTheme is one node of the knowledge category tree (mentaltheme.dbss) —
 * e.g. "Ecology" or "Residents of Velia". Ecology themes fall in the 10001..20000
 * key range. Item is the "You can learn about …" item whose name matches this
 * theme (a whole-category knowledge item), if any.
 */
export interface KnowledgeTheme {
    "urn": urn$0.URN;
    "key": number;
    "name"?: string;
    "parent"?: models$0.EntityRef<KnowledgeTheme> | null;
    "item"?: models$0.EntityRef<Item> | null;
}

/**
 * LifeSkillType is a uint8-wide identifier. The zero-cost conversion LifeSkillType(x) is
 * intentional: the underlying value is the wire value.
 */
export enum LifeSkillType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    LifeSkillTypeGathering = 0,
    LifeSkillTypeFishing = 1,
    LifeSkillTypeHunting = 2,
    LifeSkillTypeCooking = 3,
    LifeSkillTypeAlchemy = 4,
    LifeSkillTypeProcessing = 5,
    LifeSkillTypeTraining = 6,
    LifeSkillTypeTrading = 7,
    LifeSkillTypeFarming = 8,
    LifeSkillTypeSailing = 9,
    LifeSkillTypeQuest = 10,
    LifeSkillTypeBartering = 11,
    LifeSkillTypeReserved12 = 12,
    LifeSkillTypeReserved13 = 13,
    LifeSkillTypeReserved14 = 14,
    LifeSkillTypeCount = 15,
};

/**
 * NPC is an NPC character template keyed by the character key shared by
 * npcsimply, characterspawntype, exploration and region spawn records. Spawns
 * are its placed variants; one template can appear at several positions and
 * dialog indices. Names are localized from loc table 6.
 */
export interface NPC {
    "urn": urn$0.URN;
    "id": number;
    "name": string;

    /**
     * generic role label, e.g. "<Fruit Merchant>"
     */
    "title"?: string;

    /**
     * SpawnTypes are the NPC's client-defined map/navigation roles. Explorer
     * identifies node managers; the other values identify town services.
     */
    "spawnTypes"?: NPCSpawnTypes;
    "spawns"?: NPCSpawn[] | null;

    /**
     * ItemService describes the NPC's shop, exchange or similar item-service module.
     */
    "itemService"?: NPCItemService | null;
}

/**
 * NPCItemService is an NPC item service and its client-evaluated access condition.
 */
export interface NPCItemService {
    "name": string;
    "conditionDsl"?: string;

    /**
     * UnknownType appears to classify the surrounding character-function record.
     */
    "unknownType": number;

    /**
     * UnknownKey is the trailing key of the item-service module.
     */
    "unknownKey": number;
}

/**
 * NPCSpawn is one placed variant of an NPC template: the region it spawns in
 * (ref + key + its topography name), world position and dialog variant.
 */
export interface NPCSpawn {
    "region"?: models$0.EntityRef<WorldRegion> | null;
    "regionKey": number;

    /**
     * loc table 17, keyed by region
     */
    "regionName"?: string;
    "pos": number[];

    /**
     * DialogIndex distinguishes multiple placed variants of the same character.
     */
    "dialogIndex"?: number;
}

/**
 * NPCSpawnType is one of the client SpawnType role flags from
 * characterspawntype.dbss. Its numeric value is retained in JSON so the
 * frontend can use the same icon/category mapping as the game.
 */
export enum NPCSpawnType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * NPCSpawnTypeNormal is a normal NPC without a specialized service role.
     */
    NPCSpawnTypeNormal = 0,

    /**
     * NPCSpawnTypeSkillTrainer is a skill instructor.
     */
    NPCSpawnTypeSkillTrainer = 1,

    /**
     * NPCSpawnTypeItemRepairer repairs equipment.
     */
    NPCSpawnTypeItemRepairer = 2,

    /**
     * NPCSpawnTypeShopMerchant is a general shop merchant.
     */
    NPCSpawnTypeShopMerchant = 3,

    /**
     * NPCSpawnTypeImportantNPC is an important named NPC.
     */
    NPCSpawnTypeImportantNPC = 4,

    /**
     * NPCSpawnTypeTradeMerchant is a trade manager or merchant.
     */
    NPCSpawnTypeTradeMerchant = 5,

    /**
     * NPCSpawnTypeWarehouse is a storage keeper.
     */
    NPCSpawnTypeWarehouse = 6,

    /**
     * NPCSpawnTypeStable is a stable keeper.
     */
    NPCSpawnTypeStable = 7,

    /**
     * NPCSpawnTypeWharf is a wharf manager.
     */
    NPCSpawnTypeWharf = 8,

    /**
     * NPCSpawnTypeTransfer handles transport services.
     */
    NPCSpawnTypeTransfer = 9,

    /**
     * NPCSpawnTypeIntimacy participates in the amity system.
     */
    NPCSpawnTypeIntimacy = 10,

    /**
     * NPCSpawnTypeGuild provides guild services.
     */
    NPCSpawnTypeGuild = 11,

    /**
     * NPCSpawnTypeExplorer is a node manager.
     */
    NPCSpawnTypeExplorer = 12,

    /**
     * NPCSpawnTypeInn is an innkeeper.
     */
    NPCSpawnTypeInn = 13,

    /**
     * NPCSpawnTypeAuction provides auction services.
     */
    NPCSpawnTypeAuction = 14,

    /**
     * NPCSpawnTypeMating provides mount breeding services.
     */
    NPCSpawnTypeMating = 15,

    /**
     * NPCSpawnTypePotion sells potions.
     */
    NPCSpawnTypePotion = 16,

    /**
     * NPCSpawnTypeWeapon sells weapons.
     */
    NPCSpawnTypeWeapon = 17,

    /**
     * NPCSpawnTypeJewel sells crystals or jewelry.
     */
    NPCSpawnTypeJewel = 18,

    /**
     * NPCSpawnTypeFurniture sells furniture.
     */
    NPCSpawnTypeFurniture = 19,

    /**
     * NPCSpawnTypeCollect sells gathering supplies.
     */
    NPCSpawnTypeCollect = 20,

    /**
     * NPCSpawnTypeFish provides fishing services or supplies.
     */
    NPCSpawnTypeFish = 21,

    /**
     * NPCSpawnTypeWorker is a work supervisor.
     */
    NPCSpawnTypeWorker = 22,

    /**
     * NPCSpawnTypeAlchemy provides alchemy services.
     */
    NPCSpawnTypeAlchemy = 23,

    /**
     * NPCSpawnTypeGuildShop is a guild shop merchant.
     */
    NPCSpawnTypeGuildShop = 24,

    /**
     * NPCSpawnTypeItemMarket is a Central Market director.
     */
    NPCSpawnTypeItemMarket = 25,

    /**
     * NPCSpawnTypeTerritorySupply handles imperial supply delivery.
     */
    NPCSpawnTypeTerritorySupply = 26,

    /**
     * NPCSpawnTypeTerritoryTrade handles imperial trade delivery.
     */
    NPCSpawnTypeTerritoryTrade = 27,

    /**
     * NPCSpawnTypeSmuggle is a smuggler.
     */
    NPCSpawnTypeSmuggle = 28,

    /**
     * NPCSpawnTypeCook provides cooking services.
     */
    NPCSpawnTypeCook = 29,

    /**
     * NPCSpawnTypePC marks a player-character navigation category.
     */
    NPCSpawnTypePC = 30,

    /**
     * NPCSpawnTypeGrocery is a food or grocery merchant.
     */
    NPCSpawnTypeGrocery = 31,

    /**
     * NPCSpawnTypeRandomShop is a random shop merchant.
     */
    NPCSpawnTypeRandomShop = 32,

    /**
     * NPCSpawnTypeSupplyShop is a general supply merchant.
     */
    NPCSpawnTypeSupplyShop = 33,

    /**
     * NPCSpawnTypeRandomShopDay is a daytime random shop merchant.
     */
    NPCSpawnTypeRandomShopDay = 34,

    /**
     * NPCSpawnTypeFishSupplyShop is a fishing-supply merchant.
     */
    NPCSpawnTypeFishSupplyShop = 35,

    /**
     * NPCSpawnTypeGuildSupplyShop is a guild-supply merchant.
     */
    NPCSpawnTypeGuildSupplyShop = 36,

    /**
     * NPCSpawnTypeGuildStable is a guild stable keeper.
     */
    NPCSpawnTypeGuildStable = 37,

    /**
     * NPCSpawnTypeGuildWharf is a guild wharf manager.
     */
    NPCSpawnTypeGuildWharf = 38,

    /**
     * NPCSpawnTypePCRoomStable is an internet-cafe stable keeper.
     */
    NPCSpawnTypePCRoomStable = 39,

    /**
     * NPCSpawnTypeInstrument is an instrument merchant.
     */
    NPCSpawnTypeInstrument = 40,

    /**
     * NPCSpawnTypeUnknown41 is used by current client data but omitted from the
     * shipped CppEnums.SpawnType Lua table.
     */
    NPCSpawnTypeUnknown41 = 41,

    /**
     * NPCSpawnTypeTrainingVehicleShop is a training-vehicle merchant.
     */
    NPCSpawnTypeTrainingVehicleShop = 42,

    /**
     * NPCSpawnTypeAbyssOneEnterPositionGuide guides players to the Magnus.
     */
    NPCSpawnTypeAbyssOneEnterPositionGuide = 43,

    /**
     * NPCSpawnTypeChangeMarniStone exchanges Marni's Stones.
     */
    NPCSpawnTypeChangeMarniStone = 44,

    /**
     * NPCSpawnTypeChurchBuff provides church buffs.
     */
    NPCSpawnTypeChurchBuff = 45,
};

/**
 * NPCSpawnTypes is an NPC's set of client-defined map/navigation roles.
 */
export type NPCSpawnTypes = NPCSpawnType[] | null;

/**
 * NodeRef is the zone's waypoint/node: the key (links the node graph), the zone
 * name, and the nav position (present for nav-based zones).
 */
export interface NodeRef {
    /**
     * Node resolves to the worldmap node in world.json, when the key is one (6 of the
     * 105 zones point at a key with no exploration node behind it).
     */
    "urn"?: models$0.EntityRef<WorldNode> | null;
    "key": number;
    "name"?: string;
    "pos"?: number[] | null;
}

/**
 * QuestConditions contains the client expressions evaluated before a quest can
 * be accepted and when its objective is completed.
 */
export interface QuestConditions {
    "acceptDsl"?: string;
    "completeDsl"?: string;
}

/**
 * QuestRef is a "group-index" quest id resolved to its loc texts (filled by the build).
 */
export interface QuestRef {
    "id": string;
    "name"?: string;
    "desc"?: string;
    "giver"?: string;
    "objective"?: string;
    "conditions"?: QuestConditions | null;
}

/**
 * Ref is a numeric id resolved to its display name (filled by the build from
 * loc). Desc carries an optional description (e.g. a title's requirement text).
 * URN is the durable link to the referenced entity when it maps to a catalog
 * model (ecology → character, topography → world region); absent for refs with
 * no backing model (e.g. titles).
 */
export interface Ref {
    "id": number;
    "name"?: string;
    "desc"?: string;
    "urn"?: urn$0.URN | null;
}

/**
 * SlotName is a byte-wide identifier. The zero-cost conversion SlotName(x) is
 * intentional: the underlying value is the wire value.
 */
export enum SlotName {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SlotNameMainWeapon = 0,
    SlotNameSubWeapon = 1,
    SlotNameFishingChair = 2,
    SlotNameArmor = 3,
    SlotNameGloves = 4,
    SlotNameShoes = 5,
    SlotNameHelmet = 6,
    SlotNameNecklace = 7,
    SlotNameRingI = 8,
    SlotNameRingII = 9,
    SlotNameEarringI = 10,
    SlotNameEarringII = 11,
    SlotNameBelt = 12,
    SlotNameLantern = 13,
    SlotNameCostumeArmor = 14,
    SlotNameCostumeGloves = 15,
    SlotNameCostumeShoes = 16,
    SlotNameCostumeHelmet = 17,
    SlotNameCostumeMainWeapon = 18,
    SlotNameCostumeSubWeapon = 19,
    SlotNameUnderwear = 20,
    SlotNameCostumeEarring = 21,
    SlotNameCostumeHeadpiece = 22,
    SlotNameCostumePiercing = 23,
    SlotNameShipGear = 25,
    SlotNameShipGear2 = 26,
    SlotNameAlchemyStone = 27,
    SlotNameAwakeningWeapon = 29,
    SlotNameCostumeAwakeningWeapon = 30,
    SlotNameTome = 31,
    SlotNameArtifactI = 32,
    SlotNameArtifactII = 33,
    SlotNameLumberingAxe = 34,
    SlotNameFluidCollector = 35,
    SlotNameHoe = 36,
    SlotNameButcherKnife = 37,
    SlotNameTanningKnife = 38,
    SlotNamePickaxe = 39,
    SlotNameFishingRod = 40,
    SlotNameFishingFloat = 41,
    SlotNameFishingHarpoon = 42,
    SlotNameGatheringCarrier = 45,
    SlotNameNone = 46,
    SlotNameMAX = 47,
};

/**
 * SlotNameInfo is the static metadata attached to a SlotName.
 */
export interface SlotNameInfo {
    "SlotName": SlotName;
    "Name": string;
    "Title": string;
    "Desc": string;
    "OtherSlot": number;
}

/**
 * Spawn is one NPC/monster placement within a region: its character id, world
 * position, and dialog/spawn variant index. Placements live on WorldRegion.Spawns.
 */
export interface Spawn {
    "key": number;
    "pos": number[];
    "dialogIndex"?: number;
}

/**
 * StatId is a string-wide identifier. The zero-cost conversion StatId(x) is
 * intentional: the underlying value is the wire value.
 */
export enum StatId {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatIdMonsterAp = "monsterAp",
    StatIdAdventurerAp = "adventurerAp",
    StatIdHumanAp = "humanAp",
    StatIdDemihumanAp = "demihumanAp",
    StatIdKamasylvianAp = "kamasylvianAp",
    StatIdAllSpeciesAp = "allSpeciesAp",
    StatIdHiddenAp = "hiddenAp",
    StatIdDp = "dp",
    StatIdMeleeAp = "meleeAp",
    StatIdRangedAp = "rangedAp",
    StatIdMagicAp = "magicAp",
    StatIdCritDamage = "critDamage",
    StatIdSpecialAttackDamage = "specialAttackDamage",
    StatIdBackAttackDamage = "backAttackDamage",
    StatIdDownAttackDamage = "downAttackDamage",
    StatIdHuntingDamage = "huntingDamage",
    StatIdAccuracy = "accuracy",
    StatIdMeleeAccuracy = "meleeAccuracy",
    StatIdRangedAccuracy = "rangedAccuracy",
    StatIdMagicAccuracy = "magicAccuracy",
    StatIdMeleeEvasion = "meleeEvasion",
    StatIdRangedEvasion = "rangedEvasion",
    StatIdMagicEvasion = "magicEvasion",
    StatIdMeleeDamageReduction = "meleeDamageReduction",
    StatIdRangedDamageReduction = "rangedDamageReduction",
    StatIdMagicDamageReduction = "magicDamageReduction",
    StatIdDamageReductionRate = "damageReductionRate",
    StatIdAllResistance = "allResistance",
    StatIdStunResistance = "stunResistance",
    StatIdKnockdownResistance = "knockdownResistance",
    StatIdKnockbackResistance = "knockbackResistance",
    StatIdFearResistance = "fearResistance",
    StatIdIgnoreAllResistance = "ignoreAllResistance",
    StatIdIgnoreGrappleResistance = "ignoreGrappleResistance",
    StatIdIgnoreKnockbackResistance = "ignoreKnockbackResistance",
    StatIdIgnoreKnockdownResistance = "ignoreKnockdownResistance",
    StatIdIgnoreStunResistance = "ignoreStunResistance",
    StatIdAttackSpeed = "attackSpeed",
    StatIdCastingSpeed = "castingSpeed",
    StatIdMoveSpeed = "moveSpeed",
    StatIdLuck = "luck",
    StatIdMaxHp = "maxHp",
    StatIdHpRecovery = "hpRecovery",
    StatIdHpRecoveryOnHit = "hpRecoveryOnHit",
    StatIdHpRecoveryOnCriticalHit = "hpRecoveryOnCriticalHit",
    StatIdResourceRecovery = "resourceRecovery",
    StatIdResourceRecoveryOnHit = "resourceRecoveryOnHit",
    StatIdResourceRecoveryOnCriticalHit = "resourceRecoveryOnCriticalHit",
    StatIdMaxEnergy = "maxEnergy",
    StatIdEnergyRecovery = "energyRecovery",
    StatIdBlackSpiritRage = "blackSpiritRage",
    StatIdAllMastery = "allMastery",
    StatIdGatheringMastery = "gatheringMastery",
    StatIdHoeMastery = "hoeMastery",
    StatIdLumberingMastery = "lumberingMastery",
    StatIdFluidCollectorMastery = "fluidCollectorMastery",
    StatIdTanningMastery = "tanningMastery",
    StatIdButcherMastery = "butcherMastery",
    StatIdPickaxeMastery = "pickaxeMastery",
    StatIdFishingMastery = "fishingMastery",
    StatIdHuntingMastery = "huntingMastery",
    StatIdCookingMastery = "cookingMastery",
    StatIdAlchemyMastery = "alchemyMastery",
    StatIdProcessingMastery = "processingMastery",
    StatIdTrainingMastery = "trainingMastery",
    StatIdSailingMastery = "sailingMastery",
    StatIdLifeExp = "lifeExp",
    StatIdCombatExp = "combatExp",
    StatIdSkillExp = "skillExp",
    StatIdGatheringExp = "gatheringExp",
    StatIdHuntingExp = "huntingExp",
    StatIdCookingExp = "cookingExp",
    StatIdAlchemyExp = "alchemyExp",
    StatIdFishingExp = "fishingExp",
    StatIdProcessingExp = "processingExp",
    StatIdTrainingExp = "trainingExp",
    StatIdSailingExp = "sailingExp",
    StatIdBarteringExp = "barteringExp",
    StatIdTradingExp = "tradingExp",
    StatIdFarmingExp = "farmingExp",
    StatIdMountExp = "mountExp",
    StatIdMountSkillExp = "mountSkillExp",
    StatIdStrengthExp = "strengthExp",
    StatIdBreathExp = "breathExp",
    StatIdHealthExp = "healthExp",
    StatIdGatheringTime = "gatheringTime",
    StatIdCookingTime = "cookingTime",
    StatIdAlchemyTime = "alchemyTime",
    StatIdGatheringDropRate = "gatheringDropRate",
    StatIdAutoFishingTime = "autoFishingTime",
    StatIdRareFishChance = "rareFishChance",
    StatIdHorseCaptureRate = "horseCaptureRate",
    StatIdProcessingSuccessRate = "processingSuccessRate",
    StatIdAmity = "amity",
    StatIdDeathPenaltyResistance = "deathPenaltyResistance",
    StatIdDurabilityLossResistance = "durabilityLossResistance",
    StatIdFallDamage = "fallDamage",
    StatIdItemDropRate = "itemDropRate",
    StatIdItemDropAmount = "itemDropAmount",
    StatIdHigherGradeKnowledgeChance = "higherGradeKnowledgeChance",
    StatIdKarmaRecovery = "karmaRecovery",
    StatIdSwimmingSpeed = "swimmingSpeed",
    StatIdHeatstrokeResistance = "heatstrokeResistance",
    StatIdHypothermiaResistance = "hypothermiaResistance",
    StatIdJumpHeight = "jumpHeight",
    StatIdKnowledgeChance = "knowledgeChance",
    StatIdMermaidsWish = "mermaidsWish",
    StatIdUnderwaterBreathing = "underwaterBreathing",
    StatIdWeightLimit = "weightLimit",
    StatIdAp = "ap",
    StatIdAwakeningAp = "awakeningAp",
    StatIdTotalAp = "totalAp",
    StatIdTotalAwakeningAp = "totalAwakeningAp",
    StatIdBracketAp = "bracketAp",
    StatIdBracketAwakeningAp = "bracketAwakeningAp",
    StatIdBracketMonsterAp = "bracketMonsterAp",
    StatIdBracketMonsterAwakeningAp = "bracketMonsterAwakeningAp",
    StatIdApVsMonster = "apVsMonster",
    StatIdApVsAdventurer = "apVsAdventurer",
    StatIdApVsHuman = "apVsHuman",
    StatIdApVsDemihuman = "apVsDemihuman",
    StatIdApVsKamasylvian = "apVsKamasylvian",
    StatIdApVsEdania = "apVsEdania",
    StatIdApVsNormal = "apVsNormal",
    StatIdAwakeningApVsMonster = "awakeningApVsMonster",
    StatIdAwakeningApVsAdventurer = "awakeningApVsAdventurer",
    StatIdAwakeningApVsHuman = "awakeningApVsHuman",
    StatIdAwakeningApVsDemihuman = "awakeningApVsDemihuman",
    StatIdAwakeningApVsKamasylvian = "awakeningApVsKamasylvian",
    StatIdAwakeningApVsEdania = "awakeningApVsEdania",
    StatIdAwakeningApVsNormal = "awakeningApVsNormal",
    StatIdNormalAp = "normalAp",
    StatIdEdaniaAp = "edaniaAp",
    StatIdBeastAp = "beastAp",
    StatIdDamageReduction = "damageReduction",
    StatIdTotalDamageReduction = "totalDamageReduction",
    StatIdHiddenDamageReduction = "hiddenDamageReduction",
    StatIdMonsterDamageReduction = "monsterDamageReduction",
    StatIdMonsterDamageReductionRate = "monsterDamageReductionRate",
    StatIdMeleeMonsterDamageReduction = "meleeMonsterDamageReduction",
    StatIdRangedMonsterDamageReduction = "rangedMonsterDamageReduction",
    StatIdMagicMonsterDamageReduction = "magicMonsterDamageReduction",
    StatIdHiddenMeleeDamageReduction = "hiddenMeleeDamageReduction",
    StatIdHiddenRangedDamageReduction = "hiddenRangedDamageReduction",
    StatIdHiddenMagicDamageReduction = "hiddenMagicDamageReduction",
    StatIdEvasion = "evasion",
    StatIdHiddenEvasion = "hiddenEvasion",
    StatIdEvasionRate = "evasionRate",
    StatIdMeleeEvasionRate = "meleeEvasionRate",
    StatIdRangedEvasionRate = "rangedEvasionRate",
    StatIdMagicEvasionRate = "magicEvasionRate",
    StatIdHiddenMeleeEvasion = "hiddenMeleeEvasion",
    StatIdHiddenRangedEvasion = "hiddenRangedEvasion",
    StatIdHiddenMagicEvasion = "hiddenMagicEvasion",
    StatIdGrappleResistance = "grappleResistance",
    StatIdAirAttackDamage = "airAttackDamage",
    StatIdCounterAttackDamage = "counterAttackDamage",
    StatIdSpeedAttackDamage = "speedAttackDamage",
    StatIdFarmingMastery = "farmingMastery",
    StatIdTradingMastery = "tradingMastery",
    StatIdFilteringMastery = "filteringMastery",
    StatIdDryingMastery = "dryingMastery",
    StatIdGrindingMastery = "grindingMastery",
    StatIdHeatingMastery = "heatingMastery",
    StatIdChoppingMastery = "choppingMastery",
    StatIdShakingMastery = "shakingMastery",
    StatIdMaxResource = "maxResource",
    StatIdMaxStamina = "maxStamina",
    StatIdApMin = "apMin",
    StatIdApMax = "apMax",
    StatIdAwakeningApMin = "awakeningApMin",
    StatIdAwakeningApMax = "awakeningApMax",
    StatIdCritLevel = "critLevel",
    StatIdCritChance = "critChance",
    StatIdFishingSpeed = "fishingSpeed",
    StatIdAttackSpeedLevel = "attackSpeedLevel",
    StatIdCastingSpeedLevel = "castingSpeedLevel",
    StatIdMovementSpeedLevel = "movementSpeedLevel",
    StatIdGatheringSpeed = "gatheringSpeed",
    StatIdWorkerStaminaRecovery = "workerStaminaRecovery",
};

/**
 * StatMod is one parsed effect line, e.g. "Fishing EXP +10%" ->
 * {Stat:"Fishing EXP", Op:"+", Value:10, Unit:"%"}.
 */
export interface StatMod {
    "func": string;
    "args"?: number[] | null;
    "stat"?: string;

    /**
     * StatID is the canonical accumulator key for a single-stat effect.
     */
    "statId"?: StatId;

    /**
     * StatIDs contains canonical keys for effects that apply to several peers.
     */
    "statIds"?: StatId[] | null;
    "op"?: string;
    "value"?: number;
    "unit"?: string;
    "curveFields"?: string[] | null;

    /**
     * source buff Index (traceability)
     */
    "buff"?: number;

    /**
     * BuffModule identifies the buff.dbss EffectData layout.
     */
    "buffModule"?: number;

    /**
     * BuffGroup identifies mutually replacing variants of the same effect.
     */
    "buffGroup"?: number;

    /**
     * BuffCategory identifies the broader family used by reset/stacking rules.
     */
    "buffCategory"?: BuffStackingCategory;

    /**
     * DurationMs is this modifier's duration, independent of sibling effects.
     */
    "durationMs"?: number;

    /**
     * Instant identifies an immediate effect such as Energy or Health EXP gain.
     */
    "instant"?: boolean;

    /**
     * true if less is better, ie weight
     */
    "negate"?: boolean;

    /**
     * optional consumer-facing note (e.g. "hidden stat")
     */
    "note"?: string;

    /**
     * DerivedFrom identifies the raw DSL marker that implies a canonical effect.
     */
    "derivedFrom"?: string;
}

/**
 * TagInfo is one Monster Zone Info tag from dropuitaginfo.bss: its key, label
 * (filled from loc by the caller), and its UI colors.
 */
export interface TagInfo {
    "key": number;
    "name"?: string;

    /**
     * tooltip description (loc 117 desc field)
     */
    "desc"?: string;

    /**
     * texture/background color (ARGB)
     */
    "color"?: string;

    /**
     * text color (ARGB)
     */
    "fontColor"?: string;
}

/**
 * Territory is one of the game's world territories (Balenos, Serendia, Calpheon,
 * Mediah, …) in game order, decoded from territoryinfo.bss. Name/Nation hold the
 * game's embedded (Korean) strings until the loc join replaces them (loc table
 * 12, id == Index).
 * 
 * Nation is the parent realm shown above the territory name — Balenos, Serendia
 * and Calpheon all belong to the "Republic of Calpheon" (NationKey is that
 * realm's shared hash). Primary marks the nation's direct/seat territory
 * (칼페온 직할령 = direct-rule Calpheon), Autonomous the 자치령 territories
 * (Balenos, Serendia). Positions are worldmap territory-mark placements.
 * IconLarge/IconSmall are paths relative to the data dir, under
 * icons/territories/ (written by the icons command).
 * CrownItemID/ArmorItemID are the territory-conquest (siege) reward items;
 * post-siege-era territories reuse Valencia's pair.
 */
export interface Territory {
    "urn": urn$0.URN;
    "index": number;
    "name": string;
    "nation"?: string;
    "nationKey": number;

    /**
     * CapitalKey/CapitalName identify the territory's main region (Balenos →
     * Velia, Mediah → Altinova, …; every region record of the territory
     * carries this key, so it also distinguishes the two Edania territories).
     */
    "capitalKey"?: number;
    "capitalName"?: string;
    "primary"?: boolean;
    "autonomous"?: boolean;
    "positions"?: number[][] | null;
    "iconLarge"?: string;
    "iconSmall"?: string;
    "crownItemId"?: models$0.EntityRef<Item> | null;
    "armorItemId"?: models$0.EntityRef<Item> | null;

    /**
     * ExtraKey is an optional per-territory key present only on Serendia (114)
     * and Mediah (312); not a region/node/loc id — meaning not yet identified.
     */
    "extraKey"?: number;
}

/**
 * WorldNode is one worldmap node from exploration.bss (the node-manager
 * network: towns, gateways, farms, forests, mines, …). Key matches loc table
 * 29 (localized node names) and the node ids community sites use. Kind is the
 * game's node-kind enum (drives the worldmap icon). Position and Links come
 * from mapdata_realexplore2.bwp; the remaining fields come from exploration.bss.
 * Territory is derived from the nearest region because neither table stores it.
 */
export interface WorldNode {
    "urn": urn$0.URN;
    "key": number;
    "name": string;
    "kind": WorldNodeKind;

    /**
     * Territory is the world territory this node sits in (urn::world:territory:<idx>),
     * derived from the nearest region because the node record stores no territory.
     */
    "territory": models$0.EntityRef<Territory> | null;
    "position": number[];

    /**
     * ExplorationPosition is the family/label anchor at exploration.bss +104.
     * It is omitted when it already equals Position.
     */
    "explorationPosition"?: number[] | null;

    /**
     * LinkedKey is a second node reference; == Key in every current record (a redundant copy).
     */
    "linkedKey"?: number;

    /**
     * SubKey is the node's waypoint-space key.
     */
    "subKey"?: number;

    /**
     * Knowledge references every knowledge entry the game associates with this node — its NPCs, creatures and topography (urn::knowledge:entry:<key>, see knowledge.json).
     */
    "knowledge"?: models$0.EntityRefList<KnowledgeEntry> | null;

    /**
     * Main is the primary/sub node distinction (the byte at +116): true for towns, gateways,
     * farms and castles that carry knowledge; false for resource/sub nodes. Validated 100%
     * against bdolytics' `main` flag across 999 shared nodes.
     */
    "main": boolean;

    /**
     * Contribution is the contribution-point cost to activate this node (0 for towns, else 1-3).
     */
    "contribution"?: number;

    /**
     * Radius is the node's map influence radius (f32 at +31); +35 caches Radius² and is not
     * stored separately.
     */
    "radius"?: number;

    /**
     * Manager is the NPC template that manages this exact node. The build rejects
     * non-main kind-0 pseudo families and retains repeated character keys only on
     * the owner selected by characterfunction.dbss.
     */
    "manager"?: models$0.EntityRef<NPC> | null;

    /**
     * ManagerNode points from an affiliated node to the node that owns its
     * manager. Resolve that node's Manager to reach the NPC template.
     */
    "managerNode"?: models$0.EntityRef<WorldNode> | null;

    /**
     * TownRepresentative is the ruler or representative stored at exploration.bss +45.
     */
    "townRepresentative"?: models$0.EntityRef<NPC> | null;

    /**
     * Children are the non-main nodes directly connected to this main node in the
     * mapdata_realexplore2.bwp graph.
     */
    "children"?: models$0.EntityRefList<WorldNode> | null;

    /**
     * Links are the node's client-side graph edges from mapdata_realexplore2.bwp.
     */
    "links"?: models$0.EntityRefList<WorldNode> | null;

    /**
     * Products are the normal worker-production items available at this node.
     * Quantities and lucky bonus drops are not present in the client tables.
     */
    "products"?: models$0.EntityRefList<Item> | null;

    /**
     * Enabled is false on unused, unlocalized node records.
     */
    "enabled": boolean;

    /**
     * Unknown17 closely tracks Main but is false on three active main nodes.
     */
    "unknown17"?: boolean;

    /**
     * SubKey2 (a key at +27, == SubKey for 997/1037 nodes)
     */
    "subKey2"?: number;

    /**
     * GroupHash is list-0 (a coarser grouping hash, 33 distinct values)
     */
    "groupHash"?: number[] | null;
    "unknown2"?: number;
    "unknown8"?: number;

    /**
     * The +16..+22 bytes are a small "location/zone class" subsystem, mapped by testing values
     * against shrddr's dump and the in-game world map. The names are best-guess (the exact game
     * terms aren't confirmed. +18 is an exact copy of Main and is dropped.
     * 
     * Special marks the 119 non-network "special locations" (byte +16 == 0): every town
     * (kind 2), investment bank (kind 10), sea zone (Margoria/Ross/Juur), trade district and
     * battlefield. The other 918 nodes are standard, contribution-investable network nodes.
     */
    "special"?: boolean;

    /**
     * ZoneIndex is a unique index (7..247, byte +19) on 63 "special content" nodes — islands,
     * grind zones, castles, battlefields — a foreign key into an as-yet unidentified table.
     */
    "zoneIndex"?: number;

    /**
     * ZoneCategory classifies the ZoneIndex nodes (byte +20): 1 island · 2 coastal · 5 inland/
     * desert grind · 6 battlefield & ocean "Great Spot"; set on 47 of them.
     */
    "zoneCategory"?: number;

    /**
     * GrindZone marks the 25 monster grind zones (byte +21, the Marni/Elvia set: Manshaum,
     * Mirumok, Gyfin, Star's End, Hexe, …); the value is a unique index. Disjoint from zones.json
     * (the drop-UI hunting grounds).
     */
    "grindZone"?: number;

    /**
     * GrindTier is the difficulty tier (byte +22) of the 12 endgame grind zones the in-game world
     * map labels with a Recommended-AP value (2, or 3 for Star's End). A subset of GrindZone.
     */
    "grindTier"?: number;

    /**
     * Unknown39 is a small internal value (byte +39; 13 distinct: 1, 6, 10, 12, 18, 77, …) — still
     * unidentified.
     */
    "unknown39"?: number;

    /**
     * NodeIndex is a per-node enumeration id (the low bits of +47; +47 also carries a constant
     * 0x20000 flag that is masked off here). 0 for sub-nodes; a near-sequential id on the ~229
     * main nodes, assigned roughly in region order (Balenos low, the islands 606-642 consecutive,
     * Valencia/Land of Morning Light high). Looks like the node's index into another table.
     */
    "nodeIndex"?: number;

    /**
     * AreaID is a worldmap area/sector id (the high word of +51, which is stored as AreaID<<16).
     * 44 areas that group nodes geographically — the whole contiguous old-world landmass is one
     * 525-node sector, with islands, the Valencia desert and Land of Morning Light split into
     * their own. Finer than territory, coarser than region.
     */
    "areaId"?: number;
}

/**
 * WorldNodeKind is the exploration.bss worldmap node kind at record offset 5.
 * Its numeric value is retained in JSON for compatibility with the client data.
 */
export enum WorldNodeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * WorldNodeKindNormal is a generic field, location, island, or connecting node.
     */
    WorldNodeKindNormal = 0,

    /**
     * WorldNodeKindVillage is a town, village, settlement, or minor hub.
     */
    WorldNodeKindVillage = 1,

    /**
     * WorldNodeKindCity is a major city or capital.
     */
    WorldNodeKindCity = 2,

    /**
     * WorldNodeKindGate is a gateway, outpost, fort, or guard camp.
     */
    WorldNodeKindGate = 3,

    /**
     * WorldNodeKindFarm is a crop production sub-node.
     */
    WorldNodeKindFarm = 4,

    /**
     * WorldNodeKindTrade is a farm, ranch, or resource-camp main node.
     */
    WorldNodeKindTrade = 5,

    /**
     * WorldNodeKindCollect is a gathering production sub-node.
     */
    WorldNodeKindCollect = 6,

    /**
     * WorldNodeKindQuarry is a mining production sub-node.
     */
    WorldNodeKindQuarry = 7,

    /**
     * WorldNodeKindLogging is a lumbering production sub-node.
     */
    WorldNodeKindLogging = 8,

    /**
     * WorldNodeKindDangerous is a dangerous or combat-site main node.
     */
    WorldNodeKindDangerous = 9,

    /**
     * WorldNodeKindFinance is a town asset-management service node.
     */
    WorldNodeKindFinance = 10,

    /**
     * WorldNodeKindFishTrap is a fish-drying production sub-node.
     */
    WorldNodeKindFishTrap = 11,

    /**
     * WorldNodeKindMinorFinance is a worker investment-bank production sub-node.
     */
    WorldNodeKindMinorFinance = 12,

    /**
     * WorldNodeKindMonopolyFarm is a specialty production sub-node.
     */
    WorldNodeKindMonopolyFarm = 13,

    /**
     * WorldNodeKindCraft is an animal-product or other crafting production sub-node.
     */
    WorldNodeKindCraft = 14,

    /**
     * WorldNodeKindExcavation is an excavation or special-workshop production sub-node.
     */
    WorldNodeKindExcavation = 15,
};

/**
 * WorldRegion is one map region from regioninfo.bss: Velia, Heidel Pass, Evergart
 * Falls, … Key matches loc table 17 (localized place names), the regionclientdata
 * spawn regions and region_info.xml bounds. Territory indexes into
 * World.Territories (Velia → 0 Balenos, Heidel → 1 Serendia, …); the territory's
 * capital region lives on Territory.CapitalKey. Type 1 = major city, 2 = field.
 */
export interface WorldRegion {
    "urn": urn$0.URN;

    /**
     * Unknown11 is a small region-mode enum (observed 0, 1, 3 and 4).
     */
    "unknown11": number;

    /**
     * Unknown12 is an early region capability flag.
     */
    "unknown12": boolean;

    /**
     * Unknown13 is an early region capability flag.
     */
    "unknown13": boolean;

    /**
     * Unknown18 is part of the environment/capability flag bank.
     */
    "unknown18": boolean;

    /**
     * Unknown19 is part of the environment/capability flag bank.
     */
    "unknown19": boolean;

    /**
     * Unknown20 is part of the environment/capability flag bank.
     */
    "unknown20": boolean;

    /**
     * Unknown21 is part of the environment/capability flag bank.
     */
    "unknown21": boolean;

    /**
     * Unknown22 is part of the environment/capability flag bank.
     */
    "unknown22": boolean;

    /**
     * Unknown23 is part of the environment/capability flag bank.
     */
    "unknown23": boolean;

    /**
     * Unknown24 is part of the environment/capability flag bank.
     */
    "unknown24": boolean;

    /**
     * Unknown25 is part of the environment/capability flag bank.
     */
    "unknown25": boolean;

    /**
     * Unknown26 is part of the environment/capability flag bank.
     */
    "unknown26": boolean;

    /**
     * Unknown28 is a flag adjacent to the locator setting.
     */
    "unknown28": boolean;

    /**
     * Unknown29 is a short locator/region configuration value.
     */
    "unknown29": number;

    /**
     * Unknown31 is a locator-adjacent region flag.
     */
    "unknown31": boolean;

    /**
     * Unknown32 is a client configuration token, constant in the sampled build.
     */
    "unknown32": number;

    /**
     * Unknown37 is a flag adjacent to the primary respawn position.
     */
    "unknown37": boolean;

    /**
     * Unknown54 is part of the respawn/configuration flag bank.
     */
    "unknown54": boolean;

    /**
     * Unknown55 is part of the respawn/configuration flag bank.
     */
    "unknown55": boolean;

    /**
     * Unknown56 is part of the respawn/configuration flag bank.
     */
    "unknown56": boolean;

    /**
     * Unknown57 is part of the respawn/configuration flag bank.
     */
    "unknown57": boolean;

    /**
     * Unknown58 is part of the respawn/configuration flag bank.
     */
    "unknown58": boolean;

    /**
     * Unknown60 is a respawn/configuration reference or parameter.
     */
    "unknown60": number;

    /**
     * Unknown66 qualifies the configuration value at offset 68.
     */
    "unknown66": boolean;

    /**
     * Unknown68 is a region configuration reference or parameter.
     */
    "unknown68": number;

    /**
     * Unknown82 qualifies the configuration value at offset 84.
     */
    "unknown82": boolean;

    /**
     * Unknown84 is a region configuration reference or parameter.
     */
    "unknown84": number;

    /**
     * Unknown107 is a relation key near the town and exploration references.
     */
    "unknown107": number;

    /**
     * Unknown115 is a locality flag observed on Velia and Velia Beach.
     */
    "unknown115": boolean;

    /**
     * Unknown147 is a flag preceding the client configuration block.
     */
    "unknown147": boolean;

    /**
     * Unknown149 is an opaque client-build/configuration value.
     */
    "unknown149": number;

    /**
     * Unknown153 holds five world/environment scalar parameters.
     */
    "unknown153": number[];

    /**
     * Unknown173 is a world/environment configuration reference.
     */
    "unknown173": number;

    /**
     * Unknown177 is a world/environment configuration reference.
     */
    "unknown177": number;

    /**
     * Unknown181 is a sentinel field (0xffffffff in the sampled build).
     */
    "unknown181": number;

    /**
     * Unknown185 holds six optional town/configuration references.
     */
    "unknown185": number[];

    /**
     * Unknown209 is the final flag in the variable record head.
     */
    "unknown209": boolean;

    /**
     * UnknownTail1 is the first short parameter in the fixed tail.
     */
    "unknownTail1": number;

    /**
     * UnknownTail3 is the second short parameter in the fixed tail.
     */
    "unknownTail3": number;

    /**
     * UnknownTail5 is a world-space vector or three scalar parameters.
     */
    "unknownTail5": number[];

    /**
     * UnknownTail17 is a tail configuration reference or parameter.
     */
    "unknownTail17": number;

    /**
     * UnknownTail21 is the first byte in a four-byte mode/flag group.
     */
    "unknownTail21": number;

    /**
     * UnknownTail22 is the second byte in a four-byte mode/flag group.
     */
    "unknownTail22": number;

    /**
     * UnknownTail23 is the third byte in a four-byte mode/flag group.
     */
    "unknownTail23": number;

    /**
     * UnknownTail24 is the flag terminating the four-byte mode group.
     */
    "unknownTail24": boolean;

    /**
     * UnknownTail25 holds two world-space vectors or six scalar parameters.
     */
    "unknownTail25": number[];

    /**
     * UnknownTail49 is an opaque 64-bit key or bitfield.
     */
    "unknownTail49": number;

    /**
     * UnknownTail57 is a world/environment scalar parameter.
     */
    "unknownTail57": number;

    /**
     * UnknownTail61 is a world/environment scalar parameter.
     */
    "unknownTail61": number;

    /**
     * UnknownTail65 is a tail configuration reference or parameter.
     */
    "unknownTail65": number;

    /**
     * UnknownTail69 is a tail capability flag.
     */
    "unknownTail69": boolean;

    /**
     * UnknownTail70 is a tail capability flag.
     */
    "unknownTail70": boolean;

    /**
     * UnknownTail71 is a tail configuration reference or parameter.
     */
    "unknownTail71": number;

    /**
     * UnknownTail75 is a short tail configuration value.
     */
    "unknownTail75": number;

    /**
     * UnknownTail77 is a short tail configuration value.
     */
    "unknownTail77": number;

    /**
     * UnknownTail79 is a small mode or enum value.
     */
    "unknownTail79": number;

    /**
     * UnknownTail81 is a world/environment scalar parameter.
     */
    "unknownTail81": number;

    /**
     * UnknownTail85 holds six optional configuration references.
     */
    "unknownTail85": number[];

    /**
     * UnknownTail109 qualifies the following vector fields.
     */
    "unknownTail109": boolean;

    /**
     * UnknownTail110 is a world-space vector or three scalar parameters.
     */
    "unknownTail110": number[];

    /**
     * UnknownTail122 is a world-space vector or three scalar parameters.
     */
    "unknownTail122": number[];

    /**
     * UnknownTail134 is the first byte in a short mode/flag group.
     */
    "unknownTail134": number;

    /**
     * UnknownTail135 is the second byte in a short mode/flag group.
     */
    "unknownTail135": number;

    /**
     * UnknownTail136 is a flag in the short mode group.
     */
    "unknownTail136": boolean;

    /**
     * UnknownTail137 is the final byte in the short mode group.
     */
    "unknownTail137": number;

    /**
     * UnknownTail145 is a small tail mode or enum value.
     */
    "unknownTail145": number;

    /**
     * UnknownTail154 is a trailing configuration reference or parameter.
     */
    "unknownTail154": number;

    /**
     * UnknownTail158 is a trailing configuration reference or parameter.
     */
    "unknownTail158": number;

    /**
     * UnknownTail162 is a trailing configuration reference or parameter.
     */
    "unknownTail162": number;
    "key": number;
    "name": string;
    "type": number;

    /**
     * MapColor is the record's RGB world-map color.
     */
    "mapColor": number[];

    /**
     * VillageSiegeDay uses CppEnums.VillageSiegeType; 7 means no node-war day.
     */
    "villageSiegeDay": number;

    /**
     * Ocean marks an open-ocean region.
     */
    "ocean": boolean;

    /**
     * Desert marks a desert region.
     */
    "desert": boolean;

    /**
     * Prison marks a prison region.
     */
    "prison": boolean;

    /**
     * Sea marks a sea region.
     */
    "sea": boolean;

    /**
     * Locator reports whether the client locator includes this region.
     */
    "locator": boolean;

    /**
     * Territory is the world territory this region belongs to (urn::world:territory:<idx>).
     */
    "territory": models$0.EntityRef<Territory> | null;

    /**
     * AffiliatedTown is the town responsible for this region.
     */
    "affiliatedTown"?: models$0.EntityRef<WorldRegion> | null;

    /**
     * RegionGroupKey joins regiongroupinfo.bss.
     */
    "regionGroupKey"?: number;

    /**
     * Exploration is the world-map node associated with this region.
     */
    "exploration"?: models$0.EntityRef<WorldNode> | null;

    /**
     * VillainRespawn is the fallback node used for outlaw/death respawns.
     */
    "villainRespawn"?: models$0.EntityRef<WorldNode> | null;

    /**
     * VillainRespawnPosition is the position paired with VillainRespawn.
     */
    "villainRespawnPosition": number[];

    /**
     * WaypointPosition is the region's waypoint-interface position.
     */
    "waypointPosition": number[];

    /**
     * Position is the region's world position.
     */
    "position": number[];

    /**
     * ExtraPositions are additional worldmap mark placements for oversized
     * zones (only the Great Desert of Valencia carries them).
     */
    "extraPositions"?: number[][] | null;

    /**
     * WarehouseGroup (only on the 58 warehouse-bearing places) lists the region
     * keys of every warehouse in this place's storage/transport group,
     * including itself. The groups are disjoint and match the game's transport
     * topology: one big mainland cluster, Valencia City ↔ Ancado Inner Harbor,
     * the Morning Land villages, and isolated storages listing only themselves
     * (Iliya Island, Lema Island, Arehaza, Oquilla's Eye).
     */
    "warehouseGroup"?: number[] | null;

    /**
     * GuildWharfManager is the region's guild wharf service NPC.
     */
    "guildWharfManager"?: models$0.EntityRef<NPC> | null;

    /**
     * VariantOf groups spawn-phase variants of the same place: the game keeps
     * one region record per phase (quest states, Day/Night, …), all sharing a
     * name and position — e.g. Ancient Stone Chamber is keys 26/137/155.
     * 0/absent = the place's canonical (lowest-key) record; otherwise the
     * canonical record's key. Phase records stay separate because spawn data
     * references the specific phase keys.
     */
    "variantOf"?: number;

    /**
     * Bounds is the region's world-space AABB (union of its spatial boxes, from
     * region_info.xml); absent when the region has no box data.
     */
    "bounds"?: Bounds | null;

    /**
     * Spawns are the NPC/monster placements inside this region
     * (from regionclientdata.xml): character id, world position and dialog variant.
     */
    "spawns"?: Spawn[] | null;
}

/**
 * Zone is one monster/drop zone from dropuihuntinggroundinfo.bss — the data
 * behind the in-game "Monster Zone Info" window. The table holds 105 records,
 * one per zone, in name order. Each record is a packed sequence of length-
 * prefixed sections followed by a fixed stat block; this struct is the decoded
 * form.
 */
export interface Zone {
    "urn": urn$0.URN;

    /**
     * English (resolved from loc)
     */
    "name"?: string;

    /**
     * huntingGroundKey
     */
    "key"?: number;
    "mainCategory"?: Category | null;
    "subCategories"?: Category[] | null;
    "node"?: NodeRef | null;
    "sheetAP"?: number;
    "sheetDP"?: number;
    "totalAP"?: number;
    "totalDP"?: number;
    "effectiveLimit"?: number;

    /**
     * limited-AP apply percent
     */
    "apApplyPercent"?: number;

    /**
     * obtainable items -> items.json
     */
    "loot"?: models$0.EntityRefList<Item>;

    /**
     * repeat quests
     */
    "recurringQuests"?: QuestRef[] | null;

    /**
     * region quests
     */
    "regionQuests"?: QuestRef[] | null;

    /**
     * earnable titles
     */
    "titles"?: Ref[] | null;

    /**
     * zone tags (label, desc, colors)
     */
    "tags"?: TagInfo[] | null;

    /**
     * ecology creature knowledge (loc table 6)
     */
    "ecology"?: Ref[] | null;

    /**
     * place/topography knowledge (loc table 17)
     */
    "topography"?: Ref[] | null;
}
