// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../urn/models.js";

/**
 * BindType is the game's item binding behavior ("vestedType" internally — the
 * tooltip's bind label and the "will become bound" use-warning read it).
 */
export enum BindType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * never binds (boss gear stays market-listable after equipping)
     */
    BindNone = 0,

    /**
     * binds when obtained (season gear)
     */
    BindOnObtain = 1,

    /**
     * binds when equipped/used (Manos, Loggia, Tuvala)
     */
    BindOnEquip = 2,

    /**
     * obtain-bound variant (crow/abyss gear)
     */
    BindOnObtain2 = 3,
};

/**
 * CaphrasCategory is one Caphras-enhancement cost/stat chart from
 * cronenchant.bss ("CronEnchant" is the game's internal name for the Caphras
 * system). Items map to a category via the client's computed cronKey (the
 * mapping itself is not stored client-side); the chart is shared by every item
 * of the category. Key 1..10; categories with identical charts exist (1/2,
 * 7/8) — the game distinguishes them by slot kind.
 */
export interface CaphrasCategory {
    "urn": urn$0.URN;
    "key": number;
    "levels": CaphrasEnhancement[] | null;
}

/**
 * CaphrasEnhancement is a category's chart for one enhancement level
 * (18 = TRI, 19 = TET, 20 = PEN — the only levels Caphras applies to).
 */
export interface CaphrasEnhancement {
    "enchantLevel": number;
    "steps": CaphrasLevel[] | null;
}

/**
 * CaphrasLevel is one Caphras level step: Stones is the cost of this step
 * (from the previous level), TotalStones the cumulative cost to reach it (the
 * value the table stores), and Effects the total added stats while at it, in
 * the same DSL shape as EnchantLevel.Effects so one renderer computes both.
 * 
 * The func names reuse the enhancement DSL vocabulary where the game has one:
 * ALL_AP_INCRE (AP), ALL_HIT_INCRE (accuracy), ALL_EVA_INCRE (evasion),
 * ALL_DAM_REDUCE_INCRE (damage reduction), HP_UP, MP_WP_SP_UP. The two hidden
 * stats never appear in the game's DSL, so they use extension names following
 * the same pattern: HIDDEN_EVA_INCRE, HIDDEN_DAM_REDUCE_INCRE (in-game they
 * display as a second All Evasion / Damage Reduction line).
 */
export interface CaphrasLevel {
    "level": number;
    "stones": number;
    "totalStones": number;
    "effects"?: EffectGroup[] | null;
}

/**
 * Category is a Monster Zone Info main/sub category: its key, display name (from
 * loc, filled by the build) and UI icon id (from the dropui*categoryinfo table).
 */
export interface Category {
    "id": number;
    "name"?: string;
    "icon"?: string;
}

/**
 * Character is a knowledge subject — the loc-table-6 entity(-ies) a knowledge card
 * is about, keyed by name slug (urn::character:<slug>). loc table 6 mixes many
 * entity kinds under one id space and has duplicate names, so a subject can't be a
 * single NPC id; it's name-keyed and aggregates the same-named entities.
 * 
 * Kind is the subject's entity kind (the most character-like of its entities'
 * kinds; from the characterstatic npcKind field where clean, else the render model
 * prefix) — empty when no entity carries a model (a place/abstract). Npcs are the
 * same-named entities that also have an npcsimply record (spawns/dialogue) — so
 * "Islin Bartali" carries npc 40001 while "Kzarka Statue" is a kind=object subject
 * (npcKind 8) with no npcs. Entities is the full per-entity characterstatic data.
 */
export interface Character {
    "urn": urn$0.URN;
    "name"?: string;
    "kind"?: CharacterKind;
    "npcs"?: models$0.EntityRefList<NPC> | null;
    "entities"?: CharacterEntity[] | null;
}

/**
 * CharacterEntity is one characterstatic.dbss record behind a subject (a subject
 * aggregates same-named loc-6 entities). It carries everything we currently read
 * from the record, including still-unidentified fields, so nothing is lost.
 */
export interface CharacterEntity {
    "id": number;

    /**
     * Kind is this entity's kind (from NpcKind where clean, else the Model prefix).
     */
    "kind"?: CharacterKind;

    /**
     * NpcKind is the raw characterstatic semantic-type bitfield (low values are the
     * clean kinds; higher values carry undecoded flags for combat entities). 0 when
     * the record's id didn't land cleanly.
     */
    "npcKind"?: number;

    /**
     * Model is the asset model path (render classification / kind fallback).
     */
    "model"?: string;

    /**
     * Scripts are the entity's interaction scripts verbatim (e.g. "getknowledge(1);").
     */
    "scripts"?: string[] | null;

    /**
     * Card is the knowledge card key from a getknowledge(N) script (id-based
     * entity→card link), 0 if none.
     */
    "card"?: number;

    /**
     * Fields are the still-unidentified structured u32s that follow npcKind, captured
     * raw for future RE.
     */
    "fields"?: number[] | null;
}

/**
 * CharacterKind is the coarse entity kind of a knowledge subject, derived from the
 * characterstatic.dbss model-path prefix. A typed string so Wails emits a TS union.
 */
export enum CharacterKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CharacterKindNPC = "npc",
    CharacterKindMonster = "monster",
    CharacterKindCreature = "creature",
    CharacterKindObject = "object",
    CharacterKindGatherable = "gatherable",
    CharacterKindStructure = "structure",
    CharacterKindMount = "mount",
    CharacterKindCash = "cash",
    CharacterKindSummon = "summon",
    CharacterKindPC = "pc",
};

/**
 * CrystalGroup is a socket crystal's transfusion group: at most Max crystals of
 * the same group can be transfused at once (Max 1000 = no limit).
 */
export interface CrystalGroup {
    "name": string;
    "max": number;
}

export interface EffectGroup {
    "title": string;
    "stats": StatMod[] | null;
}

/**
 * Effects is what a consumable applies on use: a shared cooldown/duration, the
 * shown stat modifiers, and any hidden buffs the client doesn't display (kept
 * separate; their names may still be untranslated Korean pending a future map).
 */
export interface Effects {
    /**
     * item-use cooldown (skill.dbss)
     */
    "cooldownMs"?: number;

    /**
     * buff duration (shared)
     */
    "durationMs"?: number;
    "stats"?: EffectGroup;
    "hidden"?: EffectGroup;
}

/**
 * EnchantLevel is the gear stats + effects at one enhancement level.
 * 
 * Caphras is the Caphras chart for this level — the 20 Caphras step stats
 * stacked on top of the level's base stats. Only levels 18/19/20 (TRI/TET/PEN)
 * of a Caphras-enhanceable item carry it; nil otherwise. It lives here (rather
 * than as a parallel per-level array on Enhancement) because a Caphras chart is
 * inherently the stats added at a given enhancement level.
 */
export interface EnchantLevel {
    "level": number;

    /**
     * Name is the scheme-aware display label — "Base", "+1"…"+15", or a roman tier
     * "PRI (I)"…"DEC (X)" (accessories/endgame lines start at PRI, gear runs +1..+15
     * first). Precomputed so consumers don't re-derive the scheme.
     */
    "name": string;
    "apMin"?: number;
    "apMax"?: number;

    /**
     * display AP = round((min+max)/2)
     */
    "ap"?: number;

    /**
     * weapon accuracy (post-DSL tail; hidden in the tooltip for most weapons)
     */
    "accuracy"?: number;
    "evasion"?: number;
    "damageReduction"?: number;

    /**
     * = evasion + damageReduction
     */
    "dp"?: number;

    /**
     * AddedEvasion / AddedDamageReduction are the extra defense a sub-weapon/armor
     * piece grants on top of its own Evasion/DamageReduction (the "(+N)" in the
     * tooltip, e.g. Blackstar Horn Bow "Evasion 11 (+33)"). From the post-DSL tail.
     */
    "addedEvasion"?: number;
    "addedDamageReduction"?: number;
    "maxHp"?: number;

    /**
     * Durability is the item's max durability at this enhancement level — it rises
     * with enhancement (base 100 through TRI 160 / TET 180 / PEN 200), so it's a
     * real per-level value, not constant.
     */
    "durability"?: number;

    /**
     * EnhanceChance is the base success probability (0 failstacks) to enhance at this
     * level — a fraction 0..1 (@41 ÷ 1,000,000). Follows the game's curve: 1.0 for
     * +1..+7, then dropping (PRI ~0.13, TET ~0.005, PEN ~0.002).
     */
    "enhanceChance"?: number;

    /**
     * item + set effects (DSL formulas)
     */
    "effects"?: EffectGroup[] | null;

    /**
     * Caphras steps at this level (18/19/20 only)
     */
    "caphras"?: CaphrasLevel[] | null;

    /**
     * @4  u32 per-record value (hash/id-like)
     */
    "unknown4"?: number | null;

    /**
     * @8  u32
     */
    "unknown8"?: number | null;

    /**
     * @25 u32 (rises with enhancement — likely material/cron cost)
     */
    "unknown25"?: number | null;

    /**
     * @45 u32 (often 1,000,000 — rate-like)
     */
    "unknown45"?: number | null;

    /**
     * @55 u16 (10, steps to 20 at PRI — enhancement param)
     */
    "unknown55"?: number | null;

    /**
     * @57 u16 (constant 10)
     */
    "unknown57"?: number | null;

    /**
     * @60 u16 (rises +8→+15 then caps at 100 — enhancement param)
     */
    "unknown60"?: number | null;

    /**
     * @70 f32 — the one populated slot of the @66-165 per-species-AP band (5-10 on ~336 records, specific gear at TRI/PEN)
     */
    "unknown70"?: number | null;

    /**
     * @167 tri-block (tracks minAP-1)
     */
    "unknown167"?: number | null;

    /**
     * post-DSL constant (usually 1,000,000)
     */
    "unknownRate1"?: number | null;

    /**
     * post-DSL constant (usually 700,000)
     */
    "unknownRate2"?: number | null;
}

/**
 * Enhancement is an item's full per-level curve, linked via its EnchantKey (baseId).
 * 
 * CaphrasCategory keys the Caphras chart (caphras.json) the item follows at
 * enhancement 18-20; 0 = not Caphras-enhanceable. The game computes this key
 * inside the client executable, so it is DERIVED here from client-side fields
 * (slot kind x a buy-price tier: boss >= 10M, blue >= 2M, else green) --
 * validated chart-exact against 1,315 community-labeled items with no false
 * positives in the eligibility domain (max level 20 weapons/armor).
 */
export interface Enhancement {
    "urn": urn$0.URN;
    "baseId": number;
    "caphrasCategory"?: models$0.EntityRef<CaphrasCategory> | null;

    /**
     * the lowest level in Levels (usually 0, sometimes 1)
     */
    "minLevel": number;

    /**
     * the index of the EnchantLevel matching MinLevel
     */
    "minLevelIdx": number;

    /**
     * the highest level in Levels (usually 15, sometimes 20)
     */
    "maxLevel": number;

    /**
     * the index of the EnchantLevel matching MaxLevel
     */
    "maxLevelIdx": number;
    "levels"?: EnchantLevel[] | null;
}

/**
 * EquipInfo groups an equippable item's slot taxonomy. Kind is the broad gear class
 * (Weapon/Armor/Other, itemenchant @15); Slot is the normalized, class-independent
 * equip slot (@14) — the only slot source for artifacts, life/gathering tools and
 * costume accessories whose Type is blank; Type is the specific EquipType (@7), the
 * weapon class for weapons. Slots lists every slot the item occupies (@14 + @16-18)
 * for multi-slot items like functional costumes; absent = single-slot.
 */
export interface EquipInfo {
    "slot"?: string;
    "kind"?: string;
    "type"?: string;
    "slots"?: string[] | null;
}

/**
 * Item is the merged view of one game item, assembled from several decoded
 * client tables. Fields are omitted from JSON when empty/unknown so the output
 * stays compact. All values come from the client files (no scraping).
 */
export interface Item {
    "urn": urn$0.URN;
    "id": number;

    /**
     * languagedata_<lang>.loc
     */
    "name"?: string;

    /**
     * VariantOf groups reissued copies of the same item: the game mints bound
     * reward/season/box variants under new ids (e.g. Nouver Kunai exists 8x:
     * the tradeable base + 7 untradeable copies, some carrying slightly older
     * stat-curve snapshots). Copies matching on (name, itemType, category,
     * grade, icon) point at the canonical record — the tradeable/market item
     * when one exists. 0/absent = canonical. Ghost marks name-only records
     * (a localization entry with no item data behind it — retired/re-id'd
     * items); ghosts are kept for id coverage but carry nothing.
     */
    "variantOf"?: models$0.EntityRef<Item> | null;
    "ghost"?: boolean;

    /**
     * languagedata_<lang>.loc
     */
    "description"?: string;

    /**
     * languagedata_<lang>.loc  use/open confirmation; lists box/chest contents
     */
    "useText"?: string;

    /**
     * languagedata_<lang>.loc  NPC exchange offers (location + rate)
     */
    "exchangeInfo"?: string;

    /**
     * itemenchant.dbss  (embedded path)
     */
    "icon"?: string;

    /**
     * itemenchant.dbss  GradeType
     */
    "grade"?: string;

    /**
     * itemenchant.dbss  ItemClassify (game category)
     */
    "category"?: string;

    /**
     * itemenchant.dbss  ItemType
     */
    "itemType"?: string;

    /**
     * itemenchant.dbss  equip slot/kind/type (equipment)
     */
    "equipInfo"?: EquipInfo | null;

    /**
     * central-market main category (@188, or derived — see Marketable)
     */
    "marketCategory"?: string;

    /**
     * central-market sub category (@189, or derived)
     */
    "marketSubCategory"?: string;

    /**
     * the game's central-market-allowed flag (itemenchant iconEnd+0); a market category with marketable=false is derived for unlistable gear (Tuvala/boss gear)
     */
    "marketable"?: boolean;

    /**
     * BindType is the game's vestedType (binding behavior) — see the BindType
     * constants.
     */
    "bindType"?: BindType;

    /**
     * max units per market registration (gear 5, potions 500, mem frags 1000); absent = not listable
     */
    "marketRegisterLimit"?: number;

    /**
     * itemenchant.dbss  (LT)
     */
    "weight": number;

    /**
     * itemenchant.dbss  OriginalPrice
     */
    "buyPrice": number;

    /**
     * itemenchant.dbss  SellPriceToNpc
     */
    "sellPrice": number;

    /**
     * itemenchant.dbss  RepairPrice
     */
    "repairPrice": number;

    /**
     * itemenchant.dbss  (u16 @185, equipment)
     */
    "maxDurability"?: number;

    /**
     * class restriction (itemenchant mask @77); absent = all classes
     */
    "classes"?: string[] | null;

    /**
     * timed items, e.g. "(7 Days)" = 10080 (u32 @69)
     */
    "expirationMinutes"?: number;

    /**
     * required character level, e.g. 56 for awakening weapons (@97)
     */
    "requiredLevel"?: number;

    /**
     * explicit stack limit (u32 @101); absent = unlimited/default
     */
    "maxStack"?: number;

    /**
     * dyeable part count (@160)
     */
    "dyeParts"?: number;

    /**
     * crystal transfusion group (record footer + loc table 121)
     */
    "crystalGroup"?: CrystalGroup | null;

    /**
     * a raw/gathered material (itemmaking.xml node/collect/fishing)
     */
    "gathered"?: boolean;

    /**
     * ItemMaterial (@62) groups gear into material/model families: melee &
     * staff weapons 40, longbow 42, kunai 51, classic boss armor 71 vs other
     * armor 72, accessories by slot (necklace 73, ring 74, earring 75,
     * belt 76), horse gear 123. Named by reference-dictionary correlation
     * (99% match; previously misattributed to NewEquipType — see FORMATS §3).
     */
    "itemMaterial"?: number;

    /**
     * The following were identified by correlating itemenchant rows against a
     * labeled reference field dictionary over the ~28k shared item ids
     * (two-sided agreement ≥93% unless noted; FORMATS §3).
     * @67 IsStack
     */
    "stackable"?: boolean;

    /**
     * @68 DoApplyDirectly — consumed/applied on obtain
     */
    "applyDirectly"?: boolean;

    /**
     * @73 — the classic binding enum; distinct from BindType (icon+15), which the tooltip/bind-warning UI reads
     */
    "vestedType"?: number;

    /**
     * @74 IsUserVested — character/family-bound
     */
    "userVested"?: boolean;

    /**
     * @75 IsForTrade — a trading-skill goods item (crates, trade packs)
     */
    "forTrade"?: boolean;

    /**
     * @76 — trade-goods subtype
     */
    "tradeType"?: number;

    /**
     * @105 — life-skill XP family
     */
    "lifeExpType"?: number;

    /**
     * @134 ContentsEventType (u8; 171/0 = none, omitted)
     */
    "eventType"?: number;

    /**
     * @136 ContentsEventParam1 (u32; often a content ref id)
     */
    "eventParam1"?: number;

    /**
     * @140 ContentsEventParam2 (u32)
     */
    "eventParam2"?: number;

    /**
     * @151 == 0 (inverse of HideFromNote; most items are hidden from the note UI)
     */
    "shownInNote"?: boolean;

    /**
     * @152 IsCash — pearl-shop item
     */
    "cash"?: boolean;

    /**
     * @153 CronEnchantcontrol
     */
    "cronEnchant"?: number;

    /**
     * @156 IsDyeable (DyeParts @160 holds the part count)
     */
    "dyeable"?: boolean;

    /**
     * @184 IsPersonalTrade — can be handed player-to-player (Beer, Purified Water, Star Anise Tea…; 329 items)
     */
    "personalTrade"?: boolean;

    /**
     * @190 — trade goods sellable without node connection
     */
    "nodeFreeTrade"?: boolean;

    /**
     * FamilyInventory is the client's checkPushFamilyInventory flag (icon-block
     * +13 == 2): the item can be stored in the account-wide Family Inventory to
     * share across your characters. Family Inventory is a restricted whitelist
     * (~1,089 items — mostly potions, cooked food, pearl goods, timed EXP/buff
     * scrolls like Book of Combat/Life and Mercenary's Life); most items default
     * to not-allowed.
     */
    "familyInventory"?: boolean;

    /**
     * ContributionCost is the Contribution Points required to rent or place the
     * item (the reference schema's NeedContribute), recovered when you return
     * it. Set on 233 items: "[CP]" rental gear (e.g. [CP] Nesser Longsword = 50,
     * [CP] Kaia/Carnage weapons) and placeable fences/tents ([CP] Strong Fence
     * = 10). Decoded from the type-dependent tail (a u32 after a marker); 0 = none.
     */
    "contributionCost"?: number;

    /**
     * header @8-13 — a cluster of boolean/enum flags (unknown11 is set on 26,406
     * items; unknown12 defaults to 2).
     */
    "unknown8"?: number | null;
    "unknown9"?: number | null;
    "unknown10"?: number | null;
    "unknown11"?: number | null;
    "unknown12"?: number | null;
    "unknown13"?: number | null;

    /**
     * header @85-88 — a single u32 bitfield of item property flags (set on 903
     * items, 29 distinct bit combos; 0x1ec28000 dominant on 287). Read as one u32,
     * not four bytes.
     */
    "unknown85"?: number | null;

    /**
     * header @93 — small enum (1|4); equals unknown98 on every one of the 105
     * items that set it (a duplicated field).
     */
    "unknown93"?: number | null;

    /**
     * header @98-100, @106-108 — small enums on ~100 items each.
     */
    "unknown98"?: number | null;
    "unknown99"?: number | null;
    "unknown100"?: number | null;
    "unknown106"?: number | null;
    "unknown107"?: number | null;
    "unknown108"?: number | null;

    /**
     * header @135 — reads 171 (the ContentsEventType "no-event" sentinel) on 104
     * items; likely part of the event struct at @134.
     */
    "unknown135"?: number | null;

    /**
     * header @144 (u16) — a per-item-class constant on ~381 Etc/material items
     * (trade loot 1000, fences 10, reforge stones 149); NOT the CP cost.
     */
    "unknown144"?: number | null;

    /**
     * header @146-150 — @148 small enum; @149/@150 default 255.
     */
    "unknown146"?: number | null;
    "unknown148"?: number | null;
    "unknown149"?: number | null;
    "unknown150"?: number | null;

    /**
     * header @154-155 (@155 weakly matched isGuildStockable, 74%), @157 default 1.
     */
    "unknown154"?: number | null;
    "unknown155"?: number | null;
    "unknown157"?: number | null;

    /**
     * header @161, @168-169, @176-178. unknown168 + unknown176 are a PAIRED field
     * — they fire on the exact same 16,655 items (8 bytes apart, ~20 values each),
     * a strong candidate for a two-part record.
     */
    "unknown161"?: number | null;
    "unknown168"?: number | null;
    "unknown169"?: number | null;
    "unknown176"?: number | null;
    "unknown177"?: number | null;
    "unknown178"?: number | null;

    /**
     * header @187, @191 (default 1) — flags.
     */
    "unknown187"?: number | null;
    "unknown191"?: number | null;

    /**
     * icon-block +1..+3 — small enums; unknownIcon2 defaults to 9 (its only
     * deviants are the currencies: Silver/Loyalties/Crow Coin/Hardcore Coin).
     */
    "unknownIcon1"?: number | null;
    "unknownIcon2"?: number | null;
    "unknownIcon3"?: number | null;

    /**
     * icon-block +8 (default 2): value 1 on 271 Cook items — both finished dishes
     * and effectless intermediate sauces/ingredients. Likely a cooking-product/
     * ingredient flag. NOT a food training-stat type (it's on effectless sauces
     * and doesn't track the dish's buff).
     */
    "unknownIcon8"?: number | null;
    "unknownIcon9"?: number | null;

    /**
     * icon-block +10 (default 0): value 15/85 on 52 finished foods. Likely a food
     * grade/tier or buff-duration bracket — constant (15) across dishes with very
     * different buffs, so NOT a per-stat training amount.
     */
    "unknownIcon10"?: number | null;
    "unknownIcon14"?: number | null;

    /**
     * icon-block +16 (default 1): a ternary. 2 = a raw gatherable/worker-node
     * resource (ore, timber, fish, hide, crops — Iron Ore, Coal, Rough Stone…);
     * 0 = special/pearl/cash goods (SpecialGoods, PearlGoods). Best guess: an
     * item resource/source class.
     */
    "unknownIcon16"?: number | null;
    "unknownIcon19"?: number | null;
    "unknownIcon27"?: number | null;

    /**
     * Acquisition, from the per-item info XML (ui_html/xml/<lang>/<id>.xml):
     * NPCs that sell it (<shop>)
     */
    "vendors"?: string[] | null;

    /**
     * gather/collect sources, e.g. "Wild Flax" (<collect>)
     */
    "gatheredFrom"?: string[] | null;

    /**
     * gathering node regions (<node region="…">)
     */
    "gatherNodes"?: string[] | null;

    /**
     * Consumable (food/elixir) buff info, decoded from the item->skill->buff
     * chain (skill.dbss + buff.dbss), named via loc table 5. Fully client-typed.
     */
    "effects"?: Effects | null;

    /**
     * itemmaxlevel.dbss
     */
    "maxEnhance"?: number | null;

    /**
     * enchantstaticstatus.dbss curve
     */
    "enhancement"?: Enhancement | null;
}

/**
 * KnowledgeEntry is one knowledge card (mentalcard.dbss): an entry under a theme,
 * with the favor/interest values used by the amity minigame. Item is the
 * single-entry knowledge item whose name matches this entry, if any.
 */
export interface KnowledgeEntry {
    "urn": urn$0.URN;
    "key": number;
    "theme"?: models$0.EntityRef<KnowledgeTheme> | null;
    "name"?: string;
    "description"?: string;

    /**
     * how the entry is obtained (loc table 34, column 2)
     */
    "acquisition"?: string;
    "image"?: string;
    "minFavor"?: number;
    "maxFavor"?: number;
    "interest"?: number;
    "item"?: models$0.EntityRef<Item> | null;

    /**
     * Character is the loc-6 entity (NPC/monster/statue/place) this entry is
     * about, matched by name; keyed by name slug (urn::character:<slug>).
     */
    "character"?: models$0.EntityRef<Character> | null;

    /**
     * Unknown20 (@20) is a flags bitfield we've mapped positionally but not yet
     * identified — obtain/display flags (its 18 values spread evenly across every
     * category, so it is NOT the subject kind; the kind is the theme category:
     * Characters / Ecology / Topography / Trade / …). Deviation-only, default 4.
     * (The @24–39 region after it is a packed sub-structure — u32 reads there come
     * back as `N<<8`, the item-RE misalignment tell — so it's read through, not
     * fielded, until its byte widths are cracked.)
     */
    "unknown20"?: number | null;
}

/**
 * KnowledgeTheme is one node of the knowledge category tree (mentaltheme.dbss) —
 * e.g. "Ecology" or "Residents of Velia". Ecology themes fall in the 10001..20000
 * key range. Item is the "You can learn about …" item whose name matches this
 * theme (a whole-category knowledge item), if any.
 */
export interface KnowledgeTheme {
    "urn": urn$0.URN;
    "key": number;
    "name"?: string;
    "parent"?: models$0.EntityRef<KnowledgeTheme> | null;
    "item"?: models$0.EntityRef<Item> | null;
}

/**
 * NPC is one row of npcsimply.bss: an NPC's id and its in-client name/title.
 * Names are the client's own (Korean) strings; English names live in .loc and
 * can be joined later by ID.
 */
export interface NPC {
    "urn": urn$0.URN;
    "id": number;
    "name": string;

    /**
     * generic role label, e.g. "<Fruit Merchant>"
     */
    "title"?: string;
    "spawns"?: NPCSpawn[] | null;
}

/**
 * NPCSpawn is one placement of an NPC: the region it spawns in (key + its
 * topography name, e.g. "Calpheon City") and its world position.
 */
export interface NPCSpawn {
    "region": number;

    /**
     * loc table 17, keyed by region
     */
    "regionName"?: string;
    "pos": number[];
}

/**
 * NodeRef is the zone's waypoint/node: the key (links the node graph), the zone
 * name, and the nav position (present for nav-based zones).
 */
export interface NodeRef {
    "key": number;
    "name"?: string;
    "pos"?: number[] | null;
}

/**
 * QuestRef is a "group-index" quest id resolved to its loc texts (filled by the build).
 */
export interface QuestRef {
    "id": string;
    "name"?: string;
    "desc"?: string;
    "giver"?: string;
    "objective"?: string;
}

/**
 * Ref is a numeric id resolved to its display name (filled by the build from
 * loc). Desc carries an optional description (e.g. a title's requirement text).
 */
export interface Ref {
    "id": number;
    "name"?: string;
    "desc"?: string;
}

/**
 * StatMod is one parsed effect line, e.g. "Fishing EXP +10%" ->
 * {Stat:"Fishing EXP", Op:"+", Value:10, Unit:"%"}.
 */
export interface StatMod {
    "func": string;
    "args"?: number[] | null;
    "stat"?: string;
    "op"?: string;
    "value"?: number;
    "unit"?: string;

    /**
     * source buff Index (traceability)
     */
    "buff"?: number;

    /**
     * true if less is better, ie weight
     */
    "negate"?: boolean;

    /**
     * optional consumer-facing note (e.g. "hidden stat")
     */
    "note"?: string;
}

/**
 * TagInfo is one Monster Zone Info tag from dropuitaginfo.bss: its key, label
 * (filled from loc by the caller), and its UI colors.
 */
export interface TagInfo {
    "key": number;
    "name"?: string;

    /**
     * tooltip description (loc 117 desc field)
     */
    "desc"?: string;

    /**
     * texture/background color (ARGB)
     */
    "color"?: string;

    /**
     * text color (ARGB)
     */
    "fontColor"?: string;
}

/**
 * Territory is one of the game's world territories (Balenos, Serendia, Calpheon,
 * Mediah, …) in game order, decoded from territoryinfo.bss. Name/Nation hold the
 * game's embedded (Korean) strings until the loc join replaces them (loc table
 * 12, id == Index).
 * 
 * Nation is the parent realm shown above the territory name — Balenos, Serendia
 * and Calpheon all belong to the "Republic of Calpheon" (NationKey is that
 * realm's shared hash). Primary marks the nation's direct/seat territory
 * (칼페온 직할령 = direct-rule Calpheon), Autonomous the 자치령 territories
 * (Balenos, Serendia). Positions are worldmap territory-mark placements.
 * IconLarge/IconSmall are paths relative to the data dir, under
 * icons/territories/ (written by the icons command).
 * CrownItemID/ArmorItemID are the territory-conquest (siege) reward items;
 * post-siege-era territories reuse Valencia's pair.
 */
export interface Territory {
    "urn": urn$0.URN;
    "index": number;
    "name": string;
    "nation"?: string;
    "nationKey": number;

    /**
     * CapitalKey/CapitalName identify the territory's main region (Balenos →
     * Velia, Mediah → Altinova, …; every region record of the territory
     * carries this key, so it also distinguishes the two Edania territories).
     */
    "capitalKey"?: number;
    "capitalName"?: string;
    "primary"?: boolean;
    "autonomous"?: boolean;
    "positions"?: number[][] | null;
    "iconLarge"?: string;
    "iconSmall"?: string;
    "crownItemId"?: models$0.EntityRef<Item> | null;
    "armorItemId"?: models$0.EntityRef<Item> | null;

    /**
     * ExtraKey is an optional per-territory key present only on Serendia (114)
     * and Mediah (312); not a region/node/loc id — meaning not yet identified.
     */
    "extraKey"?: number;
}

/**
 * WorldRegion is one map region from regioninfo.bss: Velia, Heidel Pass, Evergart
 * Falls, … Key matches loc table 17 (localized place names), the regionclientdata
 * spawn regions and region_info.xml bounds. Territory indexes into
 * World.Territories (Velia → 0 Balenos, Heidel → 1 Serendia, …); the territory's
 * capital region lives on Territory.CapitalKey. Type 1 = major city, 2 = field.
 */
export interface WorldRegion {
    "urn": urn$0.URN;
    "key": number;
    "name": string;
    "type": number;
    "territory": number;
    "position": number[];

    /**
     * ExtraPositions are additional worldmap mark placements for oversized
     * zones (only the Great Desert of Valencia carries them).
     */
    "extraPositions"?: number[][] | null;

    /**
     * WarehouseGroup (only on the 58 warehouse-bearing places) lists the region
     * keys of every warehouse in this place's storage/transport group,
     * including itself. The groups are disjoint and match the game's transport
     * topology: one big mainland cluster, Valencia City ↔ Ancado Inner Harbor,
     * the Morning Land villages, and isolated storages listing only themselves
     * (Iliya Island, Lema Island, Arehaza, Oquilla's Eye).
     */
    "warehouseGroup"?: number[] | null;

    /**
     * VariantOf groups spawn-phase variants of the same place: the game keeps
     * one region record per phase (quest states, Day/Night, …), all sharing a
     * name and position — e.g. Ancient Stone Chamber is keys 26/137/155.
     * 0/absent = the place's canonical (lowest-key) record; otherwise the
     * canonical record's key. Phase records stay separate because spawn data
     * (regions.json) references the specific phase keys.
     */
    "variantOf"?: number;
}

/**
 * Zone is one monster/drop zone from dropuihuntinggroundinfo.bss — the data
 * behind the in-game "Monster Zone Info" window. The table holds 105 records,
 * one per zone, in name order. Each record is a packed sequence of length-
 * prefixed sections followed by a fixed stat block; this struct is the decoded
 * form.
 */
export interface Zone {
    "urn": urn$0.URN;

    /**
     * English (resolved from loc)
     */
    "name"?: string;

    /**
     * huntingGroundKey
     */
    "key"?: number;
    "mainCategory"?: Category | null;
    "subCategories"?: Category[] | null;
    "node"?: NodeRef | null;
    "sheetAP"?: number;
    "sheetDP"?: number;
    "totalAP"?: number;
    "totalDP"?: number;
    "effectiveLimit"?: number;

    /**
     * limited-AP apply percent
     */
    "apApplyPercent"?: number;

    /**
     * obtainable items -> items.json
     */
    "loot"?: models$0.EntityRefList<Item>;

    /**
     * repeat quests
     */
    "recurringQuests"?: QuestRef[] | null;

    /**
     * region quests
     */
    "regionQuests"?: QuestRef[] | null;

    /**
     * earnable titles
     */
    "titles"?: Ref[] | null;

    /**
     * zone tags (label, desc, colors)
     */
    "tags"?: TagInfo[] | null;

    /**
     * ecology creature knowledge (loc table 6)
     */
    "ecology"?: Ref[] | null;

    /**
     * place/topography knowledge (loc table 17)
     */
    "topography"?: Ref[] | null;
}
