// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Artifact describes the file to download for a Release on the running platform.
 */
export interface Artifact {
    "filename": string;
    "filetype"?: string;
    "size"?: number;
    "platform"?: string;
    "arch"?: string;
}

/**
 * Release is what a Provider returns from Check when there is something newer.
 */
export interface Release {
    "version": string;
    "channel"?: string;
    "name"?: string;
    "notes"?: string;
    "publishedAt"?: string;
    "artifact": Artifact;
    "verification"?: Verification | null;
    "metadata"?: { [_ in string]?: any } | null;

    /**
     * Provider is set by the Updater after Check; provider implementations
     * should leave it empty. Used to route a follow-up Download back to the
     * same source.
     */
    "provider"?: string;
}

/**
 * Verification carries everything the Updater needs to authenticate the
 * downloaded bytes. A Provider populates this from the release source; the
 * Updater verifies against it using its configured trust root.
 * 
 * Either Digest+DigestAlgo, Signature+SignatureAlgo, or both may be present.
 * When both are present, both are checked; either failing fails the update.
 * 
 * Signature verification always uses Config.PublicKey as the trust root. The
 * release source has no say in which key authenticates it — that is the entire
 * point of pinning a key out-of-band at build time. Releases that ship a
 * Signature without a configured Config.PublicKey fail closed.
 */
export interface Verification {
    /**
     * "sha256", "sha512"
     */
    "digestAlgo"?: string;

    /**
     * raw digest bytes
     */
    "digest"?: string | null;

    /**
     * "ed25519", "ed25519ph", "ecdsa-p256"
     */
    "signatureAlgo"?: string;

    /**
     * raw signature bytes
     */
    "signature"?: string | null;
}
