// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export interface ListSourceEntry {
    "id": number;
    "urn"?: string;
    "title": string;
    "subtitle"?: string;
    "icon"?: string;
    "extra"?: { [_ in string]?: any } | null;
}

export interface ListSourceParams {
    "query"?: string;
    "source"?: SourceKind;
    "category"?: string;
    "sub_category"?: string;
    "path_parts"?: string[] | null;

    /**
     * Sort is a key from the source's SortOptions (see BaseSource.Sorts); empty
     * keeps the source's default (query-ranked) order. SortDir is "asc" or "desc"
     * (default asc). Each source applies these after filtering.
     */
    "sort"?: string;
    "sort_dir"?: string;
    "filters"?: json$0.RawMessage;
}

export type Source = any;

export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Unknown = "unknown",

    /**
     * All is not a source: it asks ListSourceEntries for a cross-source search
     * instead of dispatching to one source (see SearchAll).
     */
    All = "all",
    Item = "item",
    GrindSpot = "grindspot",
    Recipe = "recipe",
    Npc = "npc",
    Knowledge = "knowledge",
    Region = "region",
    Character = "character",
    Mastery = "mastery",
};

export interface SourceNavigationNode {
    "id": string;
    "urn"?: string;
    "path": string;
    "source": SourceKind;
    "title": string;
    "count"?: number;
    "children"?: SourceNavigationNode[] | null;
}

export interface UntypedSourceEntry {
    "type": SourceKind;
    "urn"?: string;
    "value": any;
}
