// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "../stats/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as urn$0 from "../../../github.com/idevelopthings/bdo-data-extractor/src/urn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllSources(): $CancellablePromise<$models.Source[] | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetAllSources");
}

export function GetEntry(kind: $models.SourceKind, id: number): $CancellablePromise<$models.UntypedSourceEntry | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetEntry", kind, id);
}

export function GetEntryByURN(raw: string): $CancellablePromise<$models.UntypedSourceEntry | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetEntryByURN", raw);
}

export function GetEntryDetails(kind: $models.SourceKind, id: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetEntryDetails", kind, id);
}

export function GetEntryDetailsByURN(raw: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetEntryDetailsByURN", raw);
}

export function GetNavigationTree(): $CancellablePromise<$models.SourceNavigationNode[] | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetNavigationTree");
}

export function GetSource(kind: $models.SourceKind): $CancellablePromise<$models.Source> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetSource", kind);
}

export function GetStatsByURN(ref: urn$0.URN, level: number, caphrasStep: number): $CancellablePromise<stats$0.StatGroup[] | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.GetStatsByURN", ref, level, caphrasStep);
}

export function ListSourceEntries(params: $models.ListSourceParams): $CancellablePromise<$models.ListSourceEntry[] | null> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.ListSourceEntries", params);
}

/**
 * LoadAll runs every source's Load() (call once at startup, after config is
 * loaded). Sources still backed by the catalog return nil here today; new
 * sources (character) own their data via Load — the convention we're moving to.
 */
export function LoadAll(): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.LoadAll");
}

/**
 * RegisterSource wails:internal
 */
export function RegisterSource(source: $models.Source): $CancellablePromise<void> {
    return $Call.ByName("bdo-viewer/internal/sources.SourceRegistry.RegisterSource", source);
}
